### ISSUE TITLE
Consider splitting unused_import's glob re-export visibility warning into its own lint

### ISSUE THREAD

**Issue by arifd** [rust-lang/rust#123210]
### Code

```Rust
mod foo {
    pub use bar::*;
    mod bar {
        pub(crate) fn baz() {}
    }
}

fn main() {
    foo::baz();
}
```

### Current output

```Shell
warning: glob import doesn't reexport anything because no candidate is public enough
 --> src/main.rs:2:13
  |
2 |     pub use bar::*;
  |             ^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

### Rationale and extra context

An unused import lint feels wrong to be because i am using `baz`.

### Rust Version

```Shell
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: aarch64-apple-darwin
release: 1.75.0
LLVM version: 17.0.6
```

**Comment by workingjubilee** [comment]
cc https://github.com/rust-lang/rust/issues/122759

Not an exact duplicate but is related.

**Comment by workingjubilee** [comment]
Gonna call this one a bug because it seems simply incorrect in this case, yeah. :thinking:

**Comment by petrochenkov** [comment]
This was addressed recently, the message and suggestion on nightly is different.
```
warning: glob import doesn't reexport anything with visibility `pub` because no imported item is public enough
 --> src/main.rs:2:13
  |
2 |     pub use bar::*;
  |             ^^^^^^
  |
note: the most public imported item is `pub(crate)`
 --> src/main.rs:2:13
  |
2 |     pub use bar::*;
  |             ^^^^^^
  = help: reduce the glob import's visibility or increase visibility of imported items
  = note: `#[warn(unused_imports)]` on by default
```

**Comment by arifd** [comment]
That is much better, as I can see now it's`bar` whose pub export is triggering the "unused", rather than `baz` which is patently being used. (Although that second code example??)

It's still wrong to me that the lint this falls under the category called "unused imports" but if it's one of those unfortunate grey areas that just doesn't have a nice solution. I'm happy enough to close this.
