### ISSUE TITLE
nightly rustdoc on doc.rust-lang.org has broken search and missing colours

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#123399]
This is what I see from this page on Firefox: https://doc.rust-lang.org/nightly/std/mem/fn.zeroed.html

![screenshot of std::mem::zeroed](https://github.com/rust-lang/rust/assets/15850505/f3068338-1bde-4737-8e6d-9534f89c150d)

Looking in the inspector, it appears that all of the CSS variables corresponding to the colours are missing from the actual CSS. For example, hovering over one of the elements from the syntax highlighting:
![hovering over a span.kw element, over "use" keyword](https://github.com/rust-lang/rust/assets/15850505/3f74fcc1-3147-4547-8dcf-245bbfcae1cd)

The inspector says the colour variable isn't set:
![pre.rust .kw style in inspector says --code-highlight-kw-color was never set](https://github.com/rust-lang/rust/assets/15850505/bc59e3eb-1204-4334-80a9-995d38bb4a46)

**Comment by fmease** [comment]
The search functionality (JS-based) doesn't work either. Certain static JS files don't get loaded leading to the `theme` not getting set in turn leading to the CSS variables not being defined.

**Comment by fmease** [comment]
Setting the priority to critical, this is not acceptable.

**Comment by fmease** [comment]
Over at `https://doc.rust-lang.org/nightly/settings.html`, I get the following errors:

```
error: GET https://doc.rust-lang.org/nightly/static.files/storage-4c98445ec4002617.js [HTTP/3 404  23ms]
error: GET https://doc.rust-lang.org/nightly/static.files/main-12cf3b4f4f9dc36d.js [HTTP/3 404  20ms]
warning: Loading failed for the <script> with source “https://doc.rust-lang.org/nightly/static.files/storage-4c98445ec4002617.js”. settings.html:1:1502
error: GET https://doc.rust-lang.org/nightly/static.files/main-12cf3b4f4f9dc36d.js [HTTP/3 404  8ms]
warning: Loading failed for the <script> with source “https://doc.rust-lang.org/nightly/static.files/main-12cf3b4f4f9dc36d.js”. settings.html:1:1571
error: Uncaught ReferenceError: getVar is not defined
    buildSettingsPage https://doc.rust-lang.org/nightly/static.files/settings-4313503d2e1961c2.js:17
    <anonymous> https://doc.rust-lang.org/nightly/static.files/settings-4313503d2e1961c2.js:17
    <anonymous> https://doc.rust-lang.org/nightly/static.files/settings-4313503d2e1961c2.js:17
warning: The resource at “https://doc.rust-lang.org/nightly/static.files/SourceCodePro-Regular-562dcc5011b6de7d.ttf.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. settings.html
warning: The resource at “https://doc.rust-lang.org/nightly/static.files/SourceCodePro-Semibold-d899c5a5c4aeb14a.ttf.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. settings.html

​
```

**Comment by fmease** [comment]
Locally with master `rustdoc` (rev 8938f887d3d52327d086511131c70add1ae4773c), when I try to search anything, I get:

```
Uncaught TypeError: this.string is undefined
    next file:///home/fmease/programming/rust/doc/static.files/search-ffac13a0df2b1870.js:5
    buildIndex file:///home/fmease/programming/rust/doc/static.files/search-ffac13a0df2b1870.js:5
    initSearch file:///home/fmease/programming/rust/doc/static.files/search-ffac13a0df2b1870.js:5
    <anonymous> file:///home/fmease/programming/rust/doc/static.files/search-ffac13a0df2b1870.js:5
    <anonymous> file:///home/fmease/programming/rust/doc/static.files/search-ffac13a0df2b1870.js:5
```

**Comment by fmease** [comment]
Ah but when I clear `doc/` and rebuild the docs again, it works. Might have something to do with the hash? Not sure what's going on.

cc @GuillaumeGomez @notriddle

**Comment by RalfJung** [comment]
Yeah nightly rustdoc is pretty broken, affects both nightly std docs and rustc API docs.
Cc @rust-lang/rustdoc

**Comment by Nemo157** [comment]
The version number on the settings page is `1.79.0-nightly (8df7e723e 2024-03-30)` so it seems like it might have only partially updated and there's an inconsistent set of files available (old html but new js).

**Comment by GuillaumeGomez** [comment]
Just tested locally and everything works. Checking if I can reproduce the search bug @fmease mentioned.

**Comment by GuillaumeGomez** [comment]
Can't reproduce search bug either...

**Comment by fmease** [comment]
Hey that might've been a weird edge case? Basically I had a preexisting dirty `doc/` folder.

**Comment by GuillaumeGomez** [comment]
That was my theory: an existing search index would get updated and not be working because the new search index version is completely different.

**Comment by fmease** [comment]
But surely y'all can't search over at https://doc.rust-lang.org/nightly/nightly-rustc/ either?

**Comment by GuillaumeGomez** [comment]
No but it seems like the linked JS files are not even present on the server. We might need the infra team to figure out what's going on.

**Comment by GuillaumeGomez** [comment]
[Discussion on zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/nightly.20std.20docs.20are.20missing.20JS.20files)

**Comment by Mark-Simulacrum** [comment]
Discussed on Zulip. It looks like the root cause of this is https://github.com/rust-lang/rust/pull/123246, which adjusted our tarballs to have old modification timestamps. That broke the doc upload in promote-release, which currently relies on modification timestamps being newer in the new nightly (otherwise that file isn't replaced in S3).

@Kobzol is going to work on a patch and I'm testing against dev-static a manual upload (and will apply it to proper static if it works) now.

**Comment by clarfonthey** [comment]
Presumably the modification timestamps for files could instead be set to the maximum modification time of their sources, rather than just a set low time point? It's more difficult to do that, but that way you preserve the usefulness of the times without losing the reproducibility. You could start broad, just maxing the update time of all JS/CSS/Rust files, then maybe going finer if you need it.

Or, the upload check could just go by checksums instead of timestamps, since I know S3 already stores those for you and supports using ETags for you update-if-changed too.

**Comment by clarfonthey** [comment]
Right, I had just added an edit between making that post and seeing yours that clarifies that git has settings to ensure checked out files have mtimes set to the times for the commits, not when they're checked out, ensuring it's the same for the repo if no changes are made in the meantime.

**Comment by Kobzol** [comment]
`aws s3 sync` sadly cannot compare checksums at the moment. Right now we have decided to simply `touch` all doc files that we upload to S3, therefore the modification times should be always updated.

**Comment by clarfonthey** [comment]
That's fair, and I do see that the docs are fixed now. Since we confirmed this is just an infra issue and it was fixed, I guess we should close this?

**Comment by RalfJung** [comment]
https://doc.rust-lang.org/nightly/nightly-rustc/?search=NullOp is still broken.

**Comment by Mark-Simulacrum** [comment]
I only fixed the std docs through a manual copy. Rustc docs should be fixed in a few hours with the next nightly.

**Comment by RalfJung** [comment]
The nightly should have happened but https://doc.rust-lang.org/nightly/nightly-rustc/?search=NullOp is still broken.

**Comment by Kobzol** [comment]
Should be working properly now.

**Comment by RalfJung** [comment]
It does, thanks. :)
