### ISSUE TITLE
Drop the dereferenceable attribute when a reference is passed in an enum

### ISSUE THREAD

**Issue by DianQK** [rust-lang/rust#131834]
Considering [the following code](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=d3fe55772eb8ed60ebd5ad31f7e57b02), it should print 0 with a release build, but I get a segmentation violation.

```rust
#![feature(rustc_attrs)]
#![allow(internal_features)]
#![allow(dead_code)]

#[rustc_layout_scalar_valid_range_start(1)]
#[rustc_layout_scalar_valid_range_end(0xfffffffffffffff0)]
pub struct RestrictedAddress(&'static i8);

enum E {
    A(RestrictedAddress),
    B,
    C,
}

#[no_mangle]
#[inline(never)]
fn foo(a: E) -> i8 {
    match a {
        E::A(v) => *v.0,
        _ => 0,
    }
}

fn main() {
    println!("{}", foo(std::hint::black_box(E::B)));
}
```

This is because we are adding the `dereferenceable` attribute, which allows LLVM to hoist the load instruction. In this case, we need to drop the `dereferenceable` attribute.

@rustbot label +requires-nightly +I-miscompile +A-codegen

**Comment by RalfJung** [comment]
It's less about the niche and more about the enum. The logic that computes the attribute has to just stop at the enum.

**Comment by clubby789** [comment]
While looking into this I noticed that
```rs
#![feature(rustc_attrs)]
#![allow(internal_features)]
#![allow(dead_code)]

#[rustc_layout_scalar_valid_range_start(1)]
#[rustc_layout_scalar_valid_range_end(0xfffffffffffffff0)]
pub struct RestrictedAddress(&'static i8);

enum E {
    A(RestrictedAddress),
    B,
    C,
}

fn main() {
    std::hint::black_box(E::B);
}
```
causes a debug-only ICE (`only allows integer types in const_uint_big`) when codegenning the discriminant set.

**Comment by the8472** [comment]
> causes a debug-only ICE (`only allows integer types in const_uint_big`) when codegenning the discriminant set.

#131698 should fix that

**Comment by RalfJung** [comment]
I have a fix for this up at https://github.com/rust-lang/rust/pull/132745

**Comment by RalfJung** [comment]
Turns out there is already another PR related to this issue, but it was never linked either way: https://github.com/rust-lang/rust/pull/131739. However, it doesn't fix this issue -- see the comment I posted there.

**Comment by RalfJung** [comment]
This is a very good catch btw, a really subtle bug to spot!
