### ISSUE TITLE
Linker-plugin-based LTO with -flto in clang not working

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#138910]
The original issue title was "Implement cross-language ThinLTO," #49879 but when it was stabilized, the PR title became "Stabilize linker-plugin based LTO (aka cross-language LTO)," #58057 which seems to imply that fullLTO is available. The Rustc book states, "In both cases the Rust code has to be compiled with -C linker-plugin-lto and the C/C++ code with -flto or -flto=thin so that object files are emitted as LLVM bitcode," https://doc.rust-lang.org/rustc/linker-plugin-lto.html which also seems to confirm this. However, the documentation does not provide an example of fullLTO, and simply replacing "-flto=thin" with "-flto" does not work. Therefore, this should be considered a bug.
```
// with clang -flto=thin
// works
000000000005e054 <c_func_in_rust>:
   5e054:	52800540 	mov	w0, #0x2a                  	// #42
   5e058:	d65f03c0 	ret
```
```
// with clang -flto
// doesn't work
000000000005e09c <c_func_in_rust>:
   5e09c:	17ffffd9 	b	5e000 <c_func_in_c>

000000000005e000 <c_func_in_c>:
   5e000:	52800540 	mov	w0, #0x2a                  	// #42
   5e004:	d65f03c0 	ret
```
```
$ rustc --version --verbose
rustc 1.85.1 (4eb161250 2025-03-15)
binary: rustc
commit-hash: 4eb161250e340c8f48f66e2b929ef4a5bed7c181
commit-date: 2025-03-15
host: aarch64-unknown-linux-gnu
release: 1.85.1
LLVM version: 19.1.7
```
```shell
# build.sh
# copied from https://doc.rust-lang.org/rustc/linker-plugin-lto.html
clang ./clib.c -flto=thin -c -o ./clib.o -O2
#                   ^^^^^ remove this and it will not work
ar crus ./libxyz.a ./clib.o
RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang -Clink-arg=-fuse-ld=lld" cargo build --release
objdump -d target/release/x > dump
```
```rust
// main.rs
use std::ffi::c_int;

fn main() {
    println!("{}", c_func_in_rust());
}

#[inline(never)]
#[unsafe(no_mangle)]
pub extern "C" fn c_func_in_rust() -> c_int {
    unsafe { c_func_in_c() }
}

unsafe extern "C" {
    fn c_func_in_c() -> c_int;
}
```
```rust
// build.rs
fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-link-search=.");
    println!("cargo:rustc-link-lib=xyz")
}
```
```c
// clib.c
int c_func_in_c() {
    return 42;
}
```
```toml
# Cargo.toml
[package]
name = "x"
version = "0.1.0"
edition = "2024"
```
```
x
├── build.rs
├── build.sh
├── Cargo.toml
├── clib.c
└── src
    └── main.rs
```

**Comment by dianqk** [comment]
https://github.com/rust-lang/rust/pull/136840#issuecomment-2733575860 should fix this.

**Comment by foxtran** [comment]
I've tested linker-plugin-based LTO with some setup (see below) and it does not work with `-flto=full`. And used compiler still lacks full support of `-lto=thin`. Briefly, I still see the described issue with `nigthly` Rust compiler.


Compilation of Fortran part (with some scientific code computing `arg**(4/3)`):
```
flang -O3 -flto test.f90 -c -o test.f90.o
```
Note: `-flto=thin` is not fully supported yet for Fortran compiler

Creating archive:
```
ar crus ./libDFT.a ./test.f90.o
```

Compiling Rust binary:
```
rustc -Clinker-plugin-lto -L. -lDFT-thin -Copt-level=3 -Clinker=clang -Clink-arg=-fuse-ld=lld ./main.rs
```

Then, in binary, I see only unrolled calls:
```
000000000005b500 <slater>:
   5b56a:	67 e8 90 ff ff ff    	addr32 call 5b500 <slater>
   5b5f5:	67 e8 05 ff ff ff    	addr32 call 5b500 <slater>
   5b65c:	67 e8 9e fe ff ff    	addr32 call 5b500 <slater>
```
and only single `pow` (I've expected three of them):
```
   5b509:	e8 a2 02 00 00       	call   5b7b0 <pow@plt>
000000000005b7b0 <pow@plt>:
```




I've used the following combination:

rust compiler:
```
$ rustc -Vv
rustc 1.92.0-nightly (dd7fda570 2025-09-20)
binary: rustc
commit-hash: dd7fda570040e8a736f7d8bc28ddd1b444aabc82
commit-date: 2025-09-20
host: x86_64-unknown-linux-gnu
release: 1.92.0-nightly
LLVM version: 21.1.1
```

flang compiler:
```
$ flang --version
flang version 21.1.1 (https://github.com/llvm/llvm-project.git 5a86dc996c26299de63effc927075dcbfb924167)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /somewhere/rust/.llvm-bin/bin
```

**Comment by eggyal** [comment]
> This behaviour should be documented :-)

You mean like the documentation for [`-Clto`](https://doc.rust-lang.org/rustc/codegen-options/index.html#lto) ?  😉

See also [`embed-bitcode`](https://doc.rust-lang.org/rustc/codegen-options/index.html#embed-bitcode) and [`linker-plugin-lto`](https://doc.rust-lang.org/rustc/codegen-options/index.html#linker-plugin-lto).
