### ISSUE TITLE
presence of `compiler_builtins` in the std doc crate sidebar on beta

### ISSUE THREAD

**Issue by cyrgani** [rust-lang/rust#143215]
On beta (https://doc.rust-lang.org/beta/compiler_builtins/index.html), `compiler_builtins` is shown as a crate alongside `std`, `core`, `alloc`, `proc_macro` and `test`. It does not document itself as being an unstable feature, but it does not seem to be usable without `#![feature(rustc_private)]`. 
Is it a bug that it is displayed there or am I missing something else?
(might be caused by #141993)

**Comment by tgross35** [comment]
If I had to guess, it’s because it’s (accidentally) not marked a private dependency in rustc-std-workspace-core. I’ll double check this soon

**Comment by tgross35** [comment]
https://github.com/rust-lang/rust/commit/1e6e4bb95ab7879283e4274bd80c3e04b1ea3f7c (from https://github.com/rust-lang/rust/pull/143038) should fix this, beta backport was accepted at that PR.

**Comment by cuviper** [comment]
AFAICS, 1e6e4bb95ab7879283e4274bd80c3e04b1ea3f7c does not fix this issue. I still see `compiler_builtins` in the sidebar after that PR in my `./x doc library` output, and same on beta having locally cherry-picked that commit.

**Comment by tgross35** [comment]
Oh no, I thought rustdoc hid private dependencies unless `--document-private-items` was passed. Hmm...

**Comment by tgross35** [comment]
I think it might still be getting marked public somewhere. There seems to be an easy fix adding `compiler_builtins` to https://github.com/rust-lang/rust/blob/48aee7e383503c234cce4206dee9f19f57edb617/src/bootstrap/src/core/build_steps/doc.rs#L742. Maybe that's enough for beta?

However, `requested_crates = ["alloc", "compiler_builtins", "core", "panic_abort", "panic_unwind", "proc_macro", "std", "sysroot", "test", "unwind"]` at that call, so I don't know why builtins would be showing up while the other `panic*` crates aren't, unless it's still public at this point.

**Comment by cuviper** [comment]
Note that it's still in the official nightly docs too, as of `1.90.0-nightly (da58c0513 2025-07-03)`, so let's figure out nightly for sure before we backport anything to beta.

**Comment by cuviper** [comment]
> `requested_crates = ["alloc", "compiler_builtins", "core", "panic_abort", "panic_unwind", "proc_macro", "std", "sysroot", "test", "unwind"]`

Note that `panic_abort`, `panic_unwind`, and `unwind` all have `[lib] doc = false`. So does `profiler_builtins`, although it apparently wasn't enabled in your build anyway. Maybe that's what `compiler_builtins` needs?
(That's probably cleaner for `sysroot` too)

**Comment by tgross35** [comment]
Sorry I didn't get back to this yet, thank you for continuing to look into it!

**Comment by tgross35** [comment]
Reopening for the backport

**Comment by cuviper** [comment]
Backported in #143757, and public docs look good in 1.89.0-beta.4.
