### ISSUE TITLE
ARM64EC static libraries fail when linked into ARM64X DLLs

### ISSUE THREAD

**Issue by thantthet** [rust-lang/rust#145154]
## Summary

Rust-generated ARM64EC static libraries cause crashes (0xc0000096 - privileged instruction) when statically linked into ARM64X DLLs and loaded by x64 processes on ARM64 Windows. The same scenario works correctly with MSVC-compiled ARM64EC static libraries.

## Environment

- **Rust version**: rustc 1.88.0 (6b00bc388 2025-06-23)
- **Platform**: Windows 11 ARM64 (10.0.26100)
- **Target**: `arm64ec-pc-windows-msvc`
- **Toolchain**: Visual Studio 2022 17.11+ with ARM64/ARM64EC build tools

## Steps to Reproduce

1. Create a minimal Rust library with C FFI exports
2. Build it as static library for both `aarch64-pc-windows-msvc` and `arm64ec-pc-windows-msvc`
3. Link both static libraries into an ARM64X DLL using `/machine:arm64x`
4. Load the DLL from an x64 process on ARM64 Windows
5. Process crashes with 0xc0000096

Attached [arm64x-rust-test.zip](https://github.com/user-attachments/files/21697200/arm64x-rust-test.zip) for minimal reproducible example

## Expected Behavior

The ARM64X DLL should load successfully in x64 processes, with the ARM64EC code handling the x64 emulation layer properly, just as it does with MSVC-compiled ARM64EC static libraries.

## Actual Behavior

x64 processes crash immediately upon loading the ARM64X DLL with error 0xc0000096 (privileged instruction).

## Additional Context

- **Works**: Standalone ARM64EC DLL (not ARM64X) loads fine in x64 processes
- **Works**: ARM64X DLL without Rust (pure C++) loads fine in x64 processes  
- **Works**: Same ARM64X DLL with Rust loads fine in ARM64 processes
- **Fails**: Only fails when x64 process loads ARM64X DLL containing Rust ARM64EC static lib

This suggests the issue is specific to the static library format and how the ARM64X linker processes Rust-generated ARM64EC objects.

## Workarounds

1. Build separate architecture-specific DLLs instead of ARM64X
2. Use dynamic linking (Rust as separate DLL)
3. Avoid Rust in ARM64X components

---

This issue affects any Windows on ARM application trying to use Rust in system components that must support both ARM64 and x64 processes (like Text Services Framework, shell extensions, COM servers, etc.).

**Comment by dpaoliello** [comment]
Can you please try with Nightly: LLVM 21 contains a bunch of fixes to Arm64EC that may help with this.

**Comment by kenjiuno** [comment]
If you need a simpler repro, please try:

`hello.rs`

```rs
// Platform detection
#[cfg(target_arch = "arm64ec")]
fn get_platform() -> &'static str {
    "ARM64EC"
}

#[cfg(target_arch = "aarch64")]
fn get_platform() -> &'static str {
    "ARM64"
}

#[cfg(target_arch = "x86_64")]
fn get_platform() -> &'static str {
    "x64"
}

#[cfg(not(any(
    target_arch = "arm64ec",
    target_arch = "aarch64",
    target_arch = "x86_64"
)))]
fn get_platform() -> &'static str {
    "?"
}

#[no_mangle]
pub fn main() {
    let platform = get_platform();
    println!("Hello from Rust ({})", platform);
}
```

```
# aarch64 static lib
rustc --target aarch64-pc-windows-msvc --crate-type=staticlib -C opt-level=3 hello.rs -o hello.arm64.lib

# arm64ec static lib
rustc --target arm64ec-pc-windows-msvc --crate-type=staticlib -C opt-level=3 hello.rs -o hello.arm64ec.lib

# link
link.exe ^
 /machine:arm64x ^
 /subsystem:console ^
 /out:hello.arm64x.exe ^
 hello.arm64.lib ^
 hello.arm64ec.lib ^
 kernel32.lib advapi32.lib msvcrt.lib ws2_32.lib ntdll.lib userenv.lib bcrypt.lib
```

Built with `rustc 1.94.1 (e408947bf 2026-03-25)` and test

```
C:\Proj\RustAndArm64X1\hello1>start /wait /b /machine AMD64 hello.arm64x.exe

C:\Proj\RustAndArm64X1\hello1>start /wait /b /machine arm64 hello.arm64x.exe
Hello from Rust (ARM64)
```

Built with `rustc 1.95.0-nightly (66af8be05 2026-01-27)` and test:

```
C:\Proj\RustAndArm64X1\hello1>start /wait /b /machine AMD64 \\H270\Shared\valid-arm64x-hello1\hello.arm64x.exe
Hello from Rust (ARM64EC)

C:\Proj\RustAndArm64X1\hello1>start /wait /b /machine arm64 \\H270\Shared\valid-arm64x-hello1\hello.arm64x.exe
Hello from Rust (ARM64)
```

**Comment by kenjiuno** [comment]
For reference, `LLVM 22.1.0` (lld-link.exe) or later is required to build a valid executable binary of both types, Arm64EC and Arm64X.

Fixed confirmed on LLVM 22.1.0 (21.1.8 still has the problem):

- https://github.com/llvm/llvm-project/issues/168119

The current stable rustc points to LLVM version: 21.1.8

```
rustc 1.94.1 (e408947bf 2026-03-25)
binary: rustc
commit-hash: e408947bfd200af42db322daf0fadfe7e26d3bd1
commit-date: 2026-03-25
host: aarch64-pc-windows-msvc
release: 1.94.1
LLVM version: 21.1.8
```

pr 148799 version

```
rustc 1.95.0-nightly (66af8be05 2026-01-27)
binary: rustc
commit-hash: 66af8be05b364c91853090fa4c963a30c88b26e5
commit-date: 2026-01-27
host: x86_64-pc-windows-gnu
release: 1.95.0-nightly
LLVM version: 21.1.8
```

**Comment by LeonarddeR** [comment]
@kenjiuno I've been trying to produce a working build on current stable, which is based on LLVM 22.1.2, but it still doesn't seem to work. Are you sure that LLVM 22.1.0 fixed this for real?

**Comment by kenjiuno** [comment]
> [@kenjiuno](https://github.com/kenjiuno) I've been trying to produce a working build on current stable, which is based on LLVM 22.1.2, but it still doesn't seem to work. Are you sure that LLVM 22.1.0 fixed this for real?

The answer is No.

And what kind of problem have you encountered? Is it a DLL loading error?

I know that the pull request #148799 is the only workaround to fix this problem for now (by replacing TLS callback with FLS callback)

The points of this issue:

- Rust std lib uses TLS callback → will be fixed by #148799
- llvm-link won't generate a valid Hybrid Code Address Range Table if it is using a function pointed by `-arm64xsameaddress:__dyn_tls_init` which causes DLL load crash of Arm64EC side → fixed by 22.1.0  and later https://github.com/llvm/llvm-project/issues/168119

It is better that both issues are fixed.

**Comment by LeonarddeR** [comment]
@kenjiuno wrote:
> And what kind of problem have you encountered? Is it a DLL loading error?

It's just the same (0xc0000096 error. I misread your https://github.com/rust-lang/rust/issues/145154#issuecomment-4224123167. I will wait for #148799 to be merged first.

**Comment by LeonarddeR** [comment]
Now https://github.com/rust-lang/rust/pull/148799 is merged, I was able to build a working ARM64X dll with nightly successfully.
