### ISSUE TITLE
Multiple-file example in guide

### ISSUE THREAD

**Issue by planck0** [rust-lang/rust#18533]
The guide, at [section 14.1](http://doc.rust-lang.org/guide.html#set-up), mentions

> We'll talk about multiple-file projects later on in the guide.

But that never happens. It almost seem to happen in [section 15 Crates and Modules](http://doc.rust-lang.org/guide.html#crates-and-modules), but doesn't. 

It would be nice to have a minimal example of a multiple-project setup with a library and an executable, e.g. with a lib crate project_a that prints "I am crate A", and an executable crate project_b with a subdir/helper.rs file that prints "I am a helper module"  and a main.rs file that calls these functions in both the helper file and the other crate. At least, that was what I was missing.

The other option, for keeping the guide short, would be removing the unfulfilled promise.

**Comment by steveklabnik** [comment]
The crates guide is now in the book, so this is fixed.

**Comment by luxspes** [comment]
This is far from fixed, the crates guide does not explain at all how to find the way to  use more than one file on your project. 
It explains how to call files from one project into another project, but if if you try to have 2 files in one crate call a function from each other you will fail and the guide will not help you at all

**Comment by Sogomn** [comment]
I still can't find any resource that explains how to use multiple files. I don't want to create a library - I just want to split my code!

**Comment by steveklabnik** [comment]
It works the exact same way. All Rust programs are crates.

**Comment by Sogomn** [comment]
Figured it out now. Apparently source files wrap the content implicitly into a module with the same name.

**Comment by tengwar** [comment]
I just wanted a clear and simple answer for that question and I found it on StackOverflow: http://stackoverflow.com/a/25590515/2436687
