### ISSUE TITLE
Statics should not be able to take the address of a thread_local static

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#18712]
Not sure if this is a codegen bug or just something that's not supported by LLVM

``` rust
#![feature(thread_local)]

#[thread_local]
static FOO: uint = 0;
static BAR: &'static uint = &FOO;

fn main() {
    println!("{}", *BAR);
}
```

```
$ rustc foo.rs && ./foo
282584257676671
$ rustc foo.rs --opt-level=3 && ./foo
0
```

**Comment by steveklabnik** [comment]
I'm now getting zero even with `-O`, so this is fixed, I think.

**Comment by alexcrichton** [comment]
Ah I believe this is still an issue, the results here should be deterministic. The right answer is happening in the optimized case I believe due to LLVM being able to inline everything.

**Comment by steveklabnik** [comment]
Oh, I was getting zero in all cases no matter what. how do you trigger the bug?

**Comment by alexcrichton** [comment]
Interesting, if I compile without optimizations then I get the bogus answer above. That being said, this is semantically just not a correct operation as there is no statically known global value for the address of a thread local (it varies per thread!)

**Comment by steveklabnik** [comment]
Triage: updated code:

```
#![feature(thread_local)]

#[thread_local]
static FOO: usize = 0;
static BAR: &'static usize = &FOO;

fn main() {
    println!("{}", *BAR);
}

```

I still get zero in both cases here.

**Comment by Mark-Simulacrum** [comment]
This bug is still present. Updated title to correspond to the fact that statics can reference thread locals, but they shouldn't be able to.

**Comment by alexcrichton** [comment]
This has now been fixed on nightly
