### ISSUE TITLE
Unify SyntaxExtension::Decorator and SyntaxExtension::Modifier

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#19083]
With a signature like

``` rust
fn expand(&self, ecx: &mut ExtCtxt, span: Span, meta_item: &MetaItem, orig_item: P<Item>) -> SmallVector<P<Item>>;
```

to match `MacResult::make_items`.

**Comment by kmcallister** [comment]
We now have `Decorator`, `Modifier`, *and* `MultiModifier`.  Can we remove the first two?

**Comment by steveklabnik** [comment]
Grepping around, I think this is fixed. I vaguely remember @nrc sending a PR to unify this stuff as well. Can anyone else confirm?

**Comment by nrc** [comment]
This is still an issue, we're basically waiting on the procedural macros changes to fix this (currently in RFC).

**Comment by steveklabnik** [comment]
procedural macros are stable; closing!

**Comment by petrochenkov** [comment]
Procedural macros 1.2 are stabilized, but this cleanup of legacy plugins is still not done.
I don't think it makes sense to track it with an issue though.
