### ISSUE TITLE
cfg_attr doesn't work in all contexts

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#19372]
It's implemented as a syntax extension, so it only works when attached to an item. It should really be folded into the strip_cfg pass until syntax extensions are powerful enough to handle all the cases.

**Comment by huonw** [comment]
@sfackler is this fixed by https://github.com/rust-lang/rust/pull/18634?

**Comment by sfackler** [comment]
Not entirely. It's still not going to handle attributes on patterns, fields, or variants AFAIKT.

**Comment by SergioBenitez** [comment]
This doesn't appear to be fixed when cfg_attr is used inside of a macro:

```rust
macro_rules! borked {
    () => {
        #[derive(Debug)] pub struct Good;
        #[cfg_attr(not(test), derive(Debug))] pub struct Bad;
    }
}

borked!();

fn main() {
    println!("{:?}", Good);
    println!("{:?}", Bad);
}
```

(via curmet @ IRC)

**Comment by kmcallister** [comment]
Thanks, I've opened #22250 about that issue.
