### ISSUE TITLE
missing-copy-implementations warning only triggers on externally-reachable types.

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#19712]
example, `foo.rs`:

``` rust
#![crate_type = "lib"]
mod inner {
    pub struct Foo {
        pub field: i32
    }
}

pub fn foo() -> inner::Foo {
    inner::Foo { field: 42 }
}
```

`bar.rs`:

``` rust
extern crate foo;

fn main() {
    let f = foo::foo();
    drop(f);
    println!("{}", f.field);
}
```

`foo` compiles cleanly, `bar` doesn't compile because oh no! I've forgotten to make `foo::inner::Foo` `Copy`able.

**Comment by steveklabnik** [comment]
Triage: this compiles today. Closing.

**Comment by tbu-** [comment]
What compiles today? The examples give me
```
bar.rs:6:20: 6:27 error: use of moved value: `f.field` [E0382]
bar.rs:6     println!("{}", f.field);
                            ^~~~~~~
<std macros>:2:25: 2:56 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
bar.rs:6:5: 6:29 note: in this expansion of println! (defined in <std macros>)
bar.rs:6:20: 6:27 help: run `rustc --explain E0382` to see a detailed explanation
bar.rs:5:10: 5:11 note: `f` moved here because it has type `foo::inner::Foo`, which is non-copyable
bar.rs:5     drop(f);
                  ^
error: aborting due to previous error
```
without a `missing-copy-implementation` in the `foo.rs` compilation.

**Comment by steveklabnik** [comment]
Whoops! I don't know what I did wrong, but when I had typed that, the example verbatim compiled. Trying again, I get the same error as you.

**Comment by petrochenkov** [comment]
This is a legitimate bug, `rustc_privacy::EmbargoVisitor` has a large piece of functionality missing - function return types and other things available through everything except for reexports and type aliases are not marked as reachable. This leads to many kinds of problems for such types.

**Comment by petrochenkov** [comment]
Fixed by https://github.com/rust-lang/rust/pull/31641, needs a test.

**Comment by topecongiro** [comment]
The topmost example still fails. Tested on`rustc 1.17.0-nightly (691eba135 2017-03-01)` and `rustc 1.15.1 (021bd294c 2017-02-08)`.

**Comment by petrochenkov** [comment]
@topecongiro 
`missing_copy_implementations` is allow-by-default, you need to explicitly enable it to test this:
```rust
#![deny(missing_copy_implementations)]

mod inner {
    pub struct Foo {
        pub field: i32
    }
}

pub fn foo() -> inner::Foo {
    inner::Foo { field: 42 }
}

fn main() {}
```
Result:
```
rustc 1.17.0-nightly (b1e31766d 2017-03-03)
error: type could implement `Copy`; consider adding `impl Copy`
 --> <anon>:4:5
  |
4 |       pub struct Foo {
  |  _____^ starting here...
5 | |         pub field: i32
6 | |     }
  | |_____^ ...ending here
  |
note: lint level defined here
 --> <anon>:1:9
  |
1 | #![deny(missing_copy_implementations)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by topecongiro** [comment]
I see. I should have searched other issues before commenting. Thank you for you reply!
