### ISSUE TITLE
rustdoc --test looking for non-existent shared object

### ISSUE THREAD

**Issue by mrobinson** [rust-lang/rust#21246]
In Servo, we use very few rustdoc examples. In one particular crate `util` there is a single rustdoc example, so Cargo runs `rustdoc --test`.  `util` depends on an external crate `rust-layers`, which in turn depends on an external crate `rust-azure`. Although, a compiled rlib of libazure is available, rustc will try to link against both the libazure rlib and `-lazure`. Since `-lazure` doesn't exist, linking fails.

The rustdoc command-line (apologies for the long command):
```
rustdoc
--test lib.rs
--crate-name util
-L /home/martin/work/servo/components/servo/target
-L /home/martin/work/servo/components/servo/target/deps
--extern task_info=/home/martin/work/servo/components/servo/target/deps/libtask_info-5be8a31f468e0e09.rlib
--extern time=/home/martin/work/servo/components/servo/target/deps/libtime-ad4e077cbdd35a18.rlib
--extern xxhash=/home/martin/work/servo/components/servo/target/deps/libxxhash-245c85292ece0c63.rlib
--extern encoding-index-korean=/home/martin/work/servo/components/servo/target/deps/libencoding-index-korean-7f619e1decbc8e76.rlib
--extern skia-sys=/home/martin/work/servo/components/servo/target/deps/libskia-sys-a0c97fb5e4120410.rlib
--extern script_traits=/home/martin/work/servo/components/servo/target/deps/libscript_traits-4a5ed80e950d9f94.rlib
--extern layers=/home/martin/work/servo/components/servo/target/deps/liblayers-d7491f1d2aeed9ac.rlib
--extern io_surface=/home/martin/work/servo/components/servo/target/deps/libio_surface-5397fd6555ddcd0c.rlib
--extern openssl-sys=/home/martin/work/servo/components/servo/target/deps/libopenssl-sys-8d5618621883f42c.rlib
--extern encoding-index-tradchinese=/home/martin/work/servo/components/servo/target/deps/libencoding-index-tradchinese-47f074fd879a44ba.rlib
--extern text_writer=/home/martin/work/servo/components/servo/target/deps/libtext_writer-83aeadef5ad6c975.rlib
--extern mucell=/home/martin/work/servo/components/servo/target/deps/libmucell-15aa001c80416321.rlib
--extern url=/home/martin/work/servo/components/servo/target/deps/liburl-e5595358222a824d.rlib
--extern stb_image=/home/martin/work/servo/components/servo/target/deps/libstb_image-8789d241efd7f3ef.rlib
--extern hyper=/home/martin/work/servo/components/servo/target/deps/libhyper-890ae9892b5e4aec.rlib
--extern png=/home/martin/work/servo/components/servo/target/deps/libpng-2a5686ec81c888ef.rlib
--extern glfw=/home/martin/work/servo/components/servo/target/deps/libglfw-0fe09eeb0e447723.rlib
--extern html5ever_macros=/home/martin/work/servo/components/servo/target/deps/libhtml5ever_macros-eafc84b872baff98.so
--extern mime=/home/martin/work/servo/components/servo/target/deps/libmime-4b114bc7d7856ad5.rlib
--extern core_graphics=/home/martin/work/servo/components/servo/target/deps/libcore_graphics-68ea1861802926eb.rlib
--extern cgl=/home/martin/work/servo/components/servo/target/deps/libcgl-f832515e1e91a735.rlib
--extern gl_common=/home/martin/work/servo/components/servo/target/deps/libgl_common-66a5d21dea94490e.rlib
--extern plugins=/home/martin/work/servo/components/servo/target/deps/libplugins-46498ed719ee555c.so
--extern devtools=/home/martin/work/servo/components/servo/target/deps/libdevtools-94abee49a4652e76.rlib
--extern freetype-sys=/home/martin/work/servo/components/servo/target/deps/libfreetype-sys-2000ed3efd86d8e0.rlib
--extern compositing=/home/martin/work/servo/components/servo/target/deps/libcompositing-c013b590201fd820.rlib
--extern core_foundation=/home/martin/work/servo/components/servo/target/deps/libcore_foundation-81f453a644bdecba.rlib
--extern servo=/home/martin/work/servo/components/servo/target/libservo-855886321a28c984.rlib
--extern encoding-index-japanese=/home/martin/work/servo/components/servo/target/deps/libencoding-index-japanese-78d9d2f7567be380.rlib
--extern gleam=/home/martin/work/servo/components/servo/target/deps/libgleam-e5559c03c0bebfba.rlib
--extern gl_generator=/home/martin/work/servo/components/servo/target/deps/libgl_generator-14b70861eb330221.so
--extern unsafe-any=/home/martin/work/servo/components/servo/target/deps/libunsafe-any-3d2f45b7c92200ea.rlib
--extern devtools_traits=/home/martin/work/servo/components/servo/target/deps/libdevtools_traits-8c99a10e26f4a822.rlib
--extern string_cache_macros=/home/martin/work/servo/components/servo/target/deps/libstring_cache_macros-c486c481d0b8fc2d.so
--extern js=/home/martin/work/servo/components/servo/target/deps/libjs-7a5e44e37945e142.rlib
--extern cssparser=/home/martin/work/servo/components/servo/target/deps/libcssparser-7a9a471368ea9b30.rlib
--extern lazy_static=/home/martin/work/servo/components/servo/target/deps/liblazy_static-518089d616e0fe56.rlib
--extern xml-rs=/home/martin/work/servo/components/servo/target/deps/libxml-a9be98b4dd785d98.rlib
--extern freetype=/home/martin/work/servo/components/servo/target/deps/libfreetype-f9e33152a2a3bfec.rlib
--extern encoding=/home/martin/work/servo/components/servo/target/deps/libencoding-5d9283f8df6a2add.rlib
--extern semver=/home/martin/work/servo/components/servo/target/deps/libsemver-7a9674597d634bab.rlib
--extern xlib=/home/martin/work/servo/components/servo/target/deps/libxlib-ecde648e63fc4987.rlib
--extern mozjs-sys=/home/martin/work/servo/components/servo/target/deps/libmozjs-sys-c58a7d09513f4944.rlib
--extern cookie=/home/martin/work/servo/components/servo/target/deps/libcookie-03a3f41cb989f010.rlib
--extern azure=/home/martin/work/servo/components/servo/target/deps/libazure-83ae91b5b2ebf272.rlib
--extern geom=/home/martin/work/servo/components/servo/target/deps/libgeom-92d0f13f38b09c46.rlib
--extern layout=/home/martin/work/servo/components/servo/target/deps/liblayout-3ca85d45132c804e.rlib
--extern layout_traits=/home/martin/work/servo/components/servo/target/deps/liblayout_traits-be835a4136e0cd58.rlib
--extern phf_mac=/home/martin/work/servo/components/servo/target/deps/libphf_mac-3d2c5d82d0785fb6.so
--extern png-sys=/home/martin/work/servo/components/servo/target/deps/libpng-sys-ea1e7c315521d32b.rlib
--extern phf=/home/martin/work/servo/components/servo/target/deps/libphf-987a440fbd694b69.rlib
--extern encoding_index_tests=/home/martin/work/servo/components/servo/target/deps/libencoding_index_tests-9b89d508f8de6115.rlib
--extern style=/home/martin/work/servo/components/servo/target/deps/libstyle-2978bbcc267713b3.rlib
--extern glx=/home/martin/work/servo/components/servo/target/deps/libglx-525f8d390c2e2b0a.rlib
--extern encoding-index-singlebyte=/home/martin/work/servo/components/servo/target/deps/libencoding-index-singlebyte-e8309dce7b73ab02.rlib
--extern gcc=/home/martin/work/servo/components/servo/target/deps/libgcc-aad54793e4efcc66.rlib
--extern msg=/home/martin/work/servo/components/servo/target/deps/libmsg-20eac35e27b67ccc.rlib
--extern glfw-sys=/home/martin/work/servo/components/servo/target/deps/libglfw-sys-362ff9a8d4dbbbbe.rlib
--extern glfw_app=/home/martin/work/servo/components/servo/target/deps/libglfw_app-788e77e5e6af1978.rlib
--extern uuid=/home/martin/work/servo/components/servo/target/deps/libuuid-7c7b259bcfa9d945.rlib
--extern khronos_api=/home/martin/work/servo/components/servo/target/deps/libkhronos_api-e6fe334e9439e073.rlib
--extern html5ever=/home/martin/work/servo/components/servo/target/deps/libhtml5ever-80898f0002ba0361.rlib
--extern encoding-index-simpchinese=/home/martin/work/servo/components/servo/target/deps/libencoding-index-simpchinese-2d7c8c32f7e9f2b2.rlib
--extern script=/home/martin/work/servo/components/servo/target/deps/libscript-220adde19382d644.rlib
--extern fontconfig-sys=/home/martin/work/servo/components/servo/target/deps/libfontconfig-sys-4770bf8b8048ff82.rlib
--extern egl=/home/martin/work/servo/components/servo/target/deps/libegl-90ba2a473034ea1d.rlib
--extern core_text=/home/martin/work/servo/components/servo/target/deps/libcore_text-4b909a19bc1f7938.rlib
--extern harfbuzz=/home/martin/work/servo/components/servo/target/deps/libharfbuzz-d615f1063bc88db4.rlib
--extern canvas=/home/martin/work/servo/components/servo/target/deps/libcanvas-c458de241a3c060e.rlib
--extern openssl=/home/martin/work/servo/components/servo/target/deps/libopenssl-089fe2b2f27936a4.rlib
--extern fontconfig=/home/martin/work/servo/components/servo/target/deps/libfontconfig-c046fa4ca41605a4.rlib
--extern net=/home/martin/work/servo/components/servo/target/deps/libnet-d859c8cdb0b02e68.rlib
--extern gfx=/home/martin/work/servo/components/servo/target/deps/libgfx-97756b549a7d8f02.rlib
--extern pkg-config=/home/martin/work/servo/components/servo/target/deps/libpkg-config-0d932ed646ef39a5.rlib
--extern string_cache=/home/martin/work/servo/components/servo/target/deps/libstring_cache-1cf14970ab03ef33.rlib
--extern util=/home/martin/work/servo/components/servo/target/deps/libutil-6e3cdc53c8c7e07c.rlib
--extern expat-sys=/home/martin/work/servo/components/servo/target/deps/libexpat-sys-3543c70bfcd7875f.rlib
```

The failing linking line produced by rustc:
```
error: linking with `cc` failed: exit code: 1 note:
    cc '-Wl,--as-needed' '-m64' '-L'
    '/home/martin/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib'
    '-o' '/tmp/rs-3179-0-rustdoctest/rust-out'
    '/tmp/rs-3179-0-rustdoctest/rust_out.o'
    '-Wl,--whole-archive'
    '-lmorestack'
    '-Wl,--no-whole-archive'
    '-Wl,--gc-sections'
    '-pie'
    '-nodefaultlibs'
    '/home/martin/work/servo/components/servo/target/deps/libutil-6e3cdc53c8c7e07c.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libcssparser-7a9a471368ea9b30.rlib'
    '/home/martin/work/servo/components/servo/target/deps/liblayers-d7491f1d2aeed9ac.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libazure-83ae91b5b2ebf272.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libgleam-e5559c03c0bebfba.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libgl_common-66a5d21dea94490e.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libencoding-5d9283f8df6a2add.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libencoding-index-simpchinese-2d7c8c32f7e9f2b2.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libencoding-index-tradchinese-47f074fd879a44ba.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libxlib-ecde648e63fc4987.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libencoding-index-singlebyte-e8309dce7b73ab02.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libglx-525f8d390c2e2b0a.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libtext_writer-83aeadef5ad6c975.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libtime-ad4e077cbdd35a18.rlib'
    '/home/martin/work/servo/components/servo/target/deps/liburl-e5595358222a824d.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libencoding-index-korean-7f619e1decbc8e76.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libfreetype-f9e33152a2a3bfec.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libencoding-index-japanese-78d9d2f7567be380.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libstring_cache-1cf14970ab03ef33.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libphf-987a440fbd694b69.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libxxhash-245c85292ece0c63.rlib'
    '/home/martin/work/servo/components/servo/target/deps/libgeom-92d0f13f38b09c46.rlib'
    '-L' '/home/martin/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib'
    '-ltest-4e7c5e5c'
    '-L' '/home/martin/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib'
    '-lterm-4e7c5e5c'
    '-L' '/home/martin/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib'
    '-lserialize-4e7c5e5c'
    '-L' '/home/martin/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib'
    '-llog-4e7c5e5c'
    '-L' '/home/martin/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib'
    '-lregex-4e7c5e5c'
    '-L' '/home/martin/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib'
    '-lgetopts-4e7c5e5c'
    '-L' '/home/martin/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib'
    '-lstd-4e7c5e5c'
    '-L' '/home/martin/.servo/rust/2cfb5acb5a2751c759627377e602bac4f88f2d19/rust-0.13.0-dev-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib'
    '-lrustrt-4e7c5e5c'
    '-L' '/home/martin/work/servo/components/servo/target'
    '-L' '/home/martin/work/servo/components/servo/target/deps'
    '-L' '/home/martin/work/servo/components/util/.rust'
    '-L' '/home/martin/work/servo/components/util'
    '-Wl,--whole-archive'
    '-Wl,-Bstatic'
    '-Wl,--no-whole-archive'
    '-Wl,-Bdynamic'
    '-lGL'
    '-lstdc++'
    '-lfreetype'
    '-lbz2'
    '-lfontconfig'
    '-lexpat'
    '-lX11'
    '-lazure'
    '-lX11'
    '-lrt'
    '-lfreetype'
    '-ldl'
    '-lpthread'
    '-lrt'
    '-lgcc_s'
    '-lpthread'
    '-lc'
    '-lm'
    '-lcompiler-rt'
note: /usr/bin/ld: cannot find -lazure
```

**Comment by alexcrichton** [comment]
This looks like it may just be missing `-L` to the library, is this a Cargo bug?

**Comment by jgilchrist** [comment]
I'm seeing a similar error when attempting to run doctests with tcod-rs as a dependency.

```
---- engine::actor::new_0 stdout ----
	error: linking with `cc` failed: exit code: 1
note: cc '-Wl,--as-needed' '-m64' '-L' '/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-o' '/tmp/rustdoctest.NXfYvYNp7cWR/rust-out' '/tmp/rustdoctest.NXfYvYNp7cWR/rust_out.o' '-Wl,--whole-archive' '-lmorestack' '-Wl,--no-whole-archive' '-Wl,--gc-sections' '-pie' '-nodefaultlibs' '/home/jonny/code/rslike/target/librslike-33665a348a9c0d5a.rlib' '/home/jonny/code/rslike/target/deps/libtcod-672eed4d6de26d21.rlib' '/home/jonny/code/rslike/target/deps/libbitflags-57b03d5337bba57b.rlib' '/home/jonny/code/rslike/target/deps/libtcod-sys-62882c83ff6a5d9c.rlib' '-L' '/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lstd-4e7c5e5c' '-L' '/home/jonny/code/rslike/target' '-L' '/home/jonny/code/rslike/target/deps' '-L' '/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-L' '/home/jonny/code/rslike/.rust/lib/x86_64-unknown-linux-gnu' '-L' '/home/jonny/code/rslike/lib/x86_64-unknown-linux-gnu' '-Wl,--whole-archive' '-Wl,-Bstatic' '-Wl,--no-whole-archive' '-Wl,-Bdynamic' '-ltcod' '-ltcod' '-ltcod' '-ldl' '-lpthread' '-lrt' '-lgcc_s' '-lpthread' '-lc' '-lm' '-lcompiler-rt'
note: /usr/bin/ld: cannot find -ltcod
/usr/bin/ld: cannot find -ltcod
/usr/bin/ld: cannot find -ltcod
collect2: error: ld returned 1 exit status

error: aborting due to previous error
thread 'engine::actor::new_0' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:151
```

**Comment by alexcrichton** [comment]
There have been a number of Cargo-related fixes to this recently, so I'm going to close this as likely having been fixed by those. Please feel free to reopen if it reproduces though!

**Comment by jgilchrist** [comment]
@alexcrichton I can't re-open the issue, but I'm still seeing the same error in the same situation here.

**Comment by alexcrichton** [comment]
Could you describe in a bit more detail how you're running tests? Are you using Cargo? (if so, which version?)

**Comment by jgilchrist** [comment]
I'm using the Cargo I got from using the `rustup.sh` script

```
$ cargo --version
cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-03-31)
```

31st March is a while ago, were the fixes merged since then?

**Comment by jgilchrist** [comment]
Oops, I didn't realise `rustup` gets the beta by default now. I updated to the nightly, and I compiled a version of the latest Cargo (`c3259e0`) from source but in both instances the doctests still fail.

There's one path which is being passed into `rustc` which isn't being passed for doc-tests, that I can see:

```
-L /Users/jonny/code/rslike/target/debug/build/tcod-sys-101f3066d68732c8/out
```

If I paste this into the `rustdoc` invocation, I get this output:

```
rustdoc --test /Users/jonny/code/rslike/src/lib.rs --crate-name rslike -L dependency=/Users/jonny/code/rslike/target/debug/deps --extern tcod=/Users/jonny/code/rslike/target/debug/deps/libtcod-77d31af52492579f.rlib --extern rslike=/Users/jonny/code/rslike/target/debug/librslike-a5edd6cfc864fa5b.rlib -L dependency=/Users/jonny/code/rslike/target/debug/build/tcod-sys-101f3066d68732c8/out

running 3 tests
test engine::actor::Actor_0 ... FAILED
test engine::map::new_0 ... FAILED
test engine::map::new_1 ... FAILED

failures:

---- engine::actor::Actor_0 stdout ----
	thread 'engine::actor::Actor_0' panicked at 'test executable failed:

dyld: Library not loaded: libtcod.dylib
  Referenced from: /var/folders/6h/4xvb2jn91m5cj7p4wrrpl3c00000gn/T/rustdoctest.emkHOt9oudMQ/rust_out
  Reason: image not found
', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librustdoc/test.rs:245


---- engine::map::new_0 stdout ----
	thread 'engine::map::new_0' panicked at 'test executable failed:

dyld: Library not loaded: libtcod.dylib
  Referenced from: /var/folders/6h/4xvb2jn91m5cj7p4wrrpl3c00000gn/T/rustdoctest.2LCMGcOqRjTO/rust_out
  Reason: image not found
', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librustdoc/test.rs:245


---- engine::map::new_1 stdout ----
	thread 'engine::map::new_1' panicked at 'test executable failed:

dyld: Library not loaded: libtcod.dylib
  Referenced from: /var/folders/6h/4xvb2jn91m5cj7p4wrrpl3c00000gn/T/rustdoctest.V9OwlASfiVVM/rust_out
  Reason: image not found
', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librustdoc/test.rs:245



failures:
    engine::actor::Actor_0
    engine::map::new_0
    engine::map::new_1

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured
```

But `libtcod.dylib` is present in that directory.

**Comment by alexcrichton** [comment]
Hm ok, I think I have a few ideas of what to do here, reopening!

**Comment by jgilchrist** [comment]
This appears to have been fixed by rust-lang/cargo#1530

**Comment by alexcrichton** [comment]
Thank @jgilchrist!

**Comment by Kerosene2000** [comment]
I don't know If it's a similar bug, I got an infinite loop when I `cargo test` my project
![screen shot 2016-05-24 at 5 15 22 pm](https://cloud.githubusercontent.com/assets/3610253/15509601/51ea57ca-21d4-11e6-966f-dbc26dcdee94.png)
![screen shot 2016-05-24 at 5 15 31 pm](https://cloud.githubusercontent.com/assets/3610253/15509605/569e50a0-21d4-11e6-994c-909b5ac4b864.png)

**Comment by Kerosene2000** [comment]
@alexcrichton You can test, on OS X 10.11.4 with [this commit (roulette-wheel)](https://github.com/Kerosene2000/roulette-wheel-rs/commit/dffe7634723c28c2f8a8246685765830a9861cfa), executing `cargo test` will always go on an infinite loop !

**Comment by alexcrichton** [comment]
@Kerosene2000 it appears to be because the doc tests have an infinite loop of some form

**Comment by Kerosene2000** [comment]
Ho ! I am so sorry 😞 That was me, you are right !
