### ISSUE TITLE
Bootstrap failure with Clang

### ISSUE THREAD

**Issue by kirbyfan64** [rust-lang/rust#22316]
Output:

```
make[2]: Entering directory `/media/ryan/stuff/rust/x86_64-unknown-linux-gnu/llvm/lib/Support'
llvm[2]: Compiling APFloat.cpp for Release+Asserts build
In file included from /media/ryan/stuff/rust/src/llvm/lib/Support/APFloat.cpp:17:
In file included from /media/ryan/stuff/rust/src/llvm/include/llvm/ADT/FoldingSet.h:21:
/media/ryan/stuff/rust/src/llvm/include/llvm/Support/Allocator.h:425:65: error: 
      'S' does not refer to a value
      Size, std::min((size_t)llvm::NextPowerOf2(Size), offsetof(S, x)));
                                                                ^
/media/ryan/stuff/rust/src/llvm/include/llvm/Support/Allocator.h:415:10: note: 
      declared here
  struct S {
         ^
/media/ryan/stuff/rust/src/llvm/include/llvm/Support/Allocator.h:425:68: error: 
      use of undeclared identifier 'x'
      Size, std::min((size_t)llvm::NextPowerOf2(Size), offsetof(S, x)));
                                                                   ^
2 errors generated.
make[2]: *** [/media/ryan/stuff/rust/x86_64-unknown-linux-gnu/llvm/lib/Support/Release+Asserts/APFloat.o] Error 1
make[2]: Leaving directory `/media/ryan/stuff/rust/x86_64-unknown-linux-gnu/llvm/lib/Support'
make[1]: *** [all] Error 1
make[1]: Leaving directory `/media/ryan/stuff/rust/x86_64-unknown-linux-gnu/llvm'
make: *** [/home/ryan/stuff/rust/x86_64-unknown-linux-gnu/llvm/Release+Asserts/bin/llvm-config] Error 2
ryan@DevPC-LX:~/stuff/rust$ 
```

Using Clang 3.6 SVN.

**Comment by kirbyfan64** [comment]
I put this at the beginning of Allocator.h:

```
#define offsetof __builtin_offsetof
```

and it works. Likely related to [this](http://lists.cs.uiuc.edu/pipermail/llvmdev/2014-May/072836.html).

**Comment by kirbyfan64** [comment]
Interestingly, almost every other file said that the macro was being redefined. I also encountered the same issue in llvm/lib/DebugInfo/DWARFAcceleratorTable.cpp.

**Comment by dotdash** [comment]
I just bootstrapped with both clang-3.5 and clang-3.6. Can you confirm that this has been fixed?

**Comment by bsdunx** [comment]
This bug is still active in the official 1.2.0 release and kirbyfan64's fix seems to be the correct fix, perhaps it's time to rebase the in-tree LLVM.

**Comment by steveklabnik** [comment]
> I just built LLVM trunk last night and no errors occurred...so this might be because Rust's version of LLVM has the issue, and it was fixed later on.

Given this comment and the replies after, as well as our many updates to LLVM in the past 18 months, I'm going to give this one a close. If there's still something wrong, please open a new issue with the new context, thanks!
