### ISSUE TITLE
Rust Book broken editor configuration link

### ISSUE THREAD

**Issue by bejar37** [rust-lang/rust#22900]
it seems like #22365 should fix this, but it's generating a link to "CONFIGS.html" instead of "CONFIGS.md"

**Comment by JeroenDeDauw** [comment]
Also just noticed this. Looking for where the source is now so I can submit a fix.

**Comment by JeroenDeDauw** [comment]
This has been fixed in 336dd6c8f03db7d70731da18d89040b1cb7d4765

**Comment by steveklabnik** [comment]
That doesn't fix it, that was the problem: the generated link uses .html instead of the .md, as the source says.

**Comment by bejar37** [comment]
No, it's not fixed there. That is deployed and it's still broken. I think it might have to do something with Pandoc changing that MD extension to HTML
