### ISSUE TITLE
Not giving the right value to a variable in the book 

### ISSUE THREAD

**Issue by tmtwd** [rust-lang/rust#25635]
At the end of bar(), it calls baz():

In the code baz is passed f  whose value is the address of d which is 9.

However, in the diagram, it is given a value of 4.
```
Address	Name	Value
230		20
(230) - 1		5
...	...	...
12	g	100
11	f	4
10	e	9
9	d	(230) - 1
8	c	5
7	b	4
6	a	0
5	z	4
4	y	10
3	x	0
2	j	0
1	i	230
0	h	3
```

**Comment by steveklabnik** [comment]
I believe this is fixed on master, can you confirm?

**Comment by tmtwd** [comment]
I believe it should say 
11 f 9

not

11 f 4

**Comment by ralexstokes** [comment]
@steveklabnik not fixed on master but just filed a PR to do so
