### ISSUE TITLE
Operator bound breaks type inference

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#28118]
I would expect this to compile, but it doesn't:

```
use std::ops::{Mul};

pub fn calc<X>(x: X) -> f64 where f64: Mul<X, Output=X> {
    2. * 3.
}

fn main() {
}
```

https://play.rust-lang.org/?gist=4c8550ad70d41976729f&version=nightly

In math the convention is to write scalar-vector multiplication as `c * V`, where `V` is the vector, so I would like to get this working.

**Comment by eefriedman** [comment]
You can write it out using UFCS:
```rust
pub fn calc<X>() -> f64 where f64: Mul<X, Output=X> {
    <f64 as Mul<f64>>::mul(2.0f64, 3.0f64)
}
```
But yes, it would be nice if type inference were a bit smarter here.

**Comment by yongqli** [comment]
Thanks, that's a good workaround.

**Comment by arielb1** [comment]
this is the annoying "inference leaps of logic" problem. It will probably be solved by the new trait system aka TS3 aka TIR.

**Comment by steveklabnik** [comment]
Triage; no comments in a long while. Seems like it's not a bug today. I'm going to give it a close. Thanks!

**Comment by yongqli** [comment]
The code still doesn't compile on the nightly on the Rust playground.
