### ISSUE TITLE
i686-pc-windows-gnu package missing required DLLs

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#29208]
This package used to include `libgcc_s_dw2-1.dll` and `libstdc++-6.dll` in the `rustc/bin` folder. In the latest releases these DLLs are missing, which results in rustc failing to start.

This is possibly a result of #29009

**Comment by alexcrichton** [comment]
I believe this should be fixed by https://github.com/rust-lang/rust/pull/29195

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust/pull/29195

**Comment by Diggsey** [comment]
:+1:

**Comment by tikue** [comment]
Still experiencing this on 1.5.0-nightly (1210fb9bc 2015-10-23)

**Comment by alexcrichton** [comment]
@tikue are you sure? Can you show the steps you're reproducing with? Downloading the nightly shows that the DLLs are in the right locations for me.

**Comment by iliekturtles** [comment]
@alexcrichton I can reproduce with today's 1.5 nightly installer. libstdc++-6.dll is missing:

```
mikeb@asdf /c/Program Files/Rust nightly 1.5/bin$ ls -1
arena-10cbabc2.dll*
cargo.exe*
flate-10cbabc2.dll*
fmt_macros-10cbabc2.dll*
getopts-10cbabc2.dll*
graphviz-10cbabc2.dll*
log-10cbabc2.dll*
rbml-10cbabc2.dll*
rustc.exe*
rustc_back-10cbabc2.dll*
rustc_borrowck-10cbabc2.dll*
rustc_data_structures-10cbabc2.dll*
rustc_driver-10cbabc2.dll*
rustc_front-10cbabc2.dll*
rustc_lint-10cbabc2.dll*
rustc_llvm-10cbabc2.dll*
rustc_mir-10cbabc2.dll*
rustc_platform_intrinsics-10cbabc2.dll*
rustc_privacy-10cbabc2.dll*
rustc_resolve-10cbabc2.dll*
rustc_trans-10cbabc2.dll*
rustc_typeck-10cbabc2.dll*
rustc-10cbabc2.dll*
rustdoc.exe*
rustdoc-10cbabc2.dll*
rustlib/
serialize-10cbabc2.dll*
std-10cbabc2.dll*
syntax-10cbabc2.dll*
term-10cbabc2.dll*
test-10cbabc2.dll*
```

**Comment by alexcrichton** [comment]
@iliekturtles are you sure you also downloaded the most recent nightly? I just downloaded the 32-bit gnu msi and the files were installed.

**Comment by tikue** [comment]
[Steps to reproduce](https://drive.google.com/file/d/0B5eZD-cOTwJFczhnTjJ5MHp1SWc/view?usp=sharing).

**Comment by iliekturtles** [comment]
```
C:\Users\mikeb\Documents>rustc --version && cargo --version
rustc 1.5.0-nightly (1210fb9bc 2015-10-23)
cargo 0.6.0-nightly (e1ed995 2015-10-22)
```

![image](https://cloud.githubusercontent.com/assets/5081378/10713375/579c3e00-7a8a-11e5-8d78-66326d3dbddd.png)

**Comment by tikue** [comment]
Using Windows' STR tool:
```
Recording Session: ‎10/‎24/‎2015 5:04:23 PM - 5:05:22 PM

Recorded Steps: 12, Missed Steps: 0, Other Errors: 0

Operating System: 10240.16545.amd64fre.th1.150930-1750 10.0.0.0.2.48

Step 1: User left click on "Chrome Legacy Window (pane)" in "Downloads · The Rust Programming Language - Google Chrome"
Program: Google Chrome, 46.0.2490.80, Google Inc., CHROME.EXE, CHROME.EXE
UI Elements: Chrome Legacy Window, Chrome_RenderWidgetHostHWND, Downloads · The Rust Programming Language - Google Chrome, Chrome_WidgetWin_1

Step 2: User left click on " rust-nightly-x86_64-pc-windows-gnu (4).msi (button)" in "Downloads · The Rust Programming Language - Google Chrome"
Program: Google Chrome, 46.0.2490.80, Google Inc., CHROME.EXE, CHROME.EXE
UI Elements:  rust-nightly-x86_64-pc-windows-gnu (4).msi, Google Chrome, Downloads · The Rust Programming Language - Google Chrome, Chrome_WidgetWin_1

Step 3: User left click on "I understand the risk and want to run this app. (check box)" in "Windows protected your PC"
Program: Google Chrome, 46.0.2490.80, Google Inc., CHROME.EXE, CHROME.EXE
UI Elements: I understand the risk and want to run this app., TouchCheckBox, Element, Element, Dialog window, FlyoutElement, Windows protected your PC, Shell_Dialog, Shell_Dim

Step 4: User left click on "Run anyway (button)" in "Windows protected your PC"
Program: Google Chrome, 46.0.2490.80, Google Inc., CHROME.EXE, CHROME.EXE
UI Elements: Run anyway, TouchButton, Element, Dialog window, FlyoutElement, Windows protected your PC, Shell_Dialog, Shell_Dim

Step 5: User left click on "Install (button)" in "Rust nightly 1.5 (64-bit) Setup"
Program: Windows® installer, 5.0.10240.16384 (th1.150709-1700), Microsoft Corporation, MSIEXEC.EXE  /I  T:\USERS\TIM\DOWNLOADS\RUST-NIGHTLY-X86_64-PC-WINDOWS-GNU (4).MSI, MSIEXEC.EXE
UI Elements: Install, Button, Rust nightly 1.5 (64-bit) Setup, MsiDialogCloseClass

Step 6: User left click on "Finish (button)" in "Rust nightly 1.5 (64-bit) Setup"
Program: Windows® installer, 5.0.10240.16384 (th1.150709-1700), Microsoft Corporation, MSIEXEC.EXE  /I  T:\USERS\TIM\DOWNLOADS\RUST-NIGHTLY-X86_64-PC-WINDOWS-GNU (4).MSI, MSIEXEC.EXE
UI Elements: Finish, Button, Rust nightly 1.5 (64-bit) Setup, MsiDialogCloseClass

Step 7: User left click on "Start (list)"
Program: Windows Explorer, 10.0.10240.16384 (th1.150709-1700), Microsoft Corporation, EXPLORER.EXE, EXPLORER.EXE
UI Elements: Start, Start, Shell_TrayWnd

Step 8: User keyboard input on "Cortana (window)" in "Cortana" [...]
Program: Search and Cortana application, 10.0.10240.16515 (th1.150916-2039), Microsoft Corporation, SEARCHUI.EXE  -SERVERNAME:CORTANAUI.APPXA50DQQA5GQV4A428C9Y1JJW7M3BTVEPJ.MCA, SEARCHUI.EXE
UI Elements: Cortana, Windows.UI.Core.CoreWindow

Step 9: User left click on "Cortana (window)" in "Cortana"
Program: Search and Cortana application, 10.0.10240.16515 (th1.150916-2039), Microsoft Corporation, SEARCHUI.EXE  -SERVERNAME:CORTANAUI.APPXA50DQQA5GQV4A428C9Y1JJW7M3BTVEPJ.MCA, SEARCHUI.EXE
UI Elements: Cortana, Windows.UI.Core.CoreWindow

Step 10: User keyboard input on "Rust nightly 1.5 (64-bit) Shell (window)" in "Rust nightly 1.5 (64-bit) Shell" [... Enter]
Program: Windows Command Processor, 10.0.10240.16384 (th1.150709-1700), Microsoft Corporation, CMD.EXE  /K PATH C:\PROGRAM FILES\RUST NIGHTLY 1.5\BIN;C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES (X86)\NVIDIA CORPORATION\PHYSX\COMMON;T:\PROGRAM FILES (X86)\MIKTEX 2.9\MIKTEX\BIN\;C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES (X86)\SKYPE\PHONE\;T:\PROGRAM FILES\GIT\CMD;, CMD.EXE
UI Elements: Rust nightly 1.5 (64-bit) Shell, ConsoleWindowClass

Step 11: User left click on "OK (button)" in "rustc.exe - System Error"
Program: 
UI Elements: OK, Button, rustc.exe - System Error, #32770

Step 12: User left click on "OK (button)" in "rustc.exe - System Error"
Program: 
UI Elements: OK, Button, rustc.exe - System Error, #32770
```

**Comment by Diggsey** [comment]
This seems to have fixed it for me: the latest nightly works both on appveyor and locally.

**Comment by tikue** [comment]
@Diggsey try uninstalling any other versions of rust before testing

**Comment by rouge8** [comment]
I'm having what I think is the same issue with the 64bit installers on Appveyor:

```
Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Rust"
SET PATH=%PATH%;C:\Rust\bin
SET PATH=%PATH%;C:\MinGW\bin
rustc -V
*hangs indefinitely*
```

**Comment by iliekturtles** [comment]
I just noticed that this patch fixed the i686 installer. There is also an issue with the x86_64 installer.

@rouge8 Definitely, the missing DLL pops up a dialog box.

**Comment by Diggsey** [comment]
@alexcrichton The problem @tikue is having is different in that it only occurs with the 64-bit versions: libstdc++6.dll is missing there. I didn't encounter a problem because windows was finding it elsewhere on the system (my msys's mingw installation).

**Comment by alexcrichton** [comment]
Ah yep, thanks for the sharp eyes everyone! I forgot that libstdc++ is needed even for x86_64... This should get fixed up in https://github.com/rust-lang/rust/pull/29306.

Again, though, sorry for the inconvenience!
