### ISSUE TITLE
Rust Nightly (Windows 64bit) - Application Error

### ISSUE THREAD

**Issue by rossmuir** [rust-lang/rust#29246]
On Windows 7 (64bit) after installing the latest nightly - running commands in the Rust Shell gives the following error.

![rustc_nightly_error_2](https://cloud.githubusercontent.com/assets/6030823/10689105/b4ac8c6e-7970-11e5-81b5-f1255a0729e6.png)

![rustc_nightly_error](https://cloud.githubusercontent.com/assets/6030823/10688966/ece2e49e-796f-11e5-8075-e977dc9d026d.png)

**Comment by retep998** [comment]
This was likely fixed by https://github.com/rust-lang/rust/pull/29195

**Comment by alexcrichton** [comment]
Yes and the final mistake I believe is covered by https://github.com/rust-lang/rust/pull/29255, so closing in favor of that.

**Comment by rossmuir** [comment]
Can this please be re-opened as I have re-tested and still get the same issue

**Comment by alexcrichton** [comment]
@rossmuir this didn't make it into the last nightly, but the next nightly should be fixed.

**Comment by rossmuir** [comment]
Thanks @alexcrichton

**Comment by rossmuir** [comment]
@alexcrichton could this please be re-opened as Windows 7 (64bit) latest nightly still has an issue. 
![rustc_nightly_error_4](https://cloud.githubusercontent.com/assets/6030823/10791513/9ebd0e56-7d80-11e5-889b-93e83f05f1de.png)

**Comment by retep998** [comment]
That issue will be fixed by https://github.com/rust-lang/rust/pull/29403 which has not yet landed.
