### ISSUE TITLE
const indexing broken in nightly with bit shift (<<)

### ISSUE THREAD

**Issue by Johnson-A** [rust-lang/rust#30226]
```rust
const index: usize = 1;

fn main() {
    let array = [1,2,3];
    let test = 1 + array[index]; // This works fine
    let error = 1 << array[index]; // error: const indexing is an unstable feature
}
```
For some reason, indexing an array with a const requires an unstable feature when there is a bit shift operator. help: in Nightly builds, add `#![feature(const_indexing)]` to the crate attributes to enable. When adding the feature, there are no more errors but this feature shouldn't be necessary.

rustc 1.6.0-nightly (d49e36552 2015-12-05)

**Comment by eddyb** [comment]
What's happening here is that there are const evaluations attempted to determine whether the shift is statically known to be overly long (`array[index] >= 32`, presumably), and that's hitting the `const_indexing` feature-gate *without* actually being in an explicit `const` context.
cc @oli-obk

**Comment by bluss** [comment]
This is the fix: #30202

**Comment by frewsxcv** [comment]
This can be closed?

**Comment by bluss** [comment]
Yep, the issue is fixed and has tests. Fixed in #30202.

**Comment by Johnson-A** [comment]
I still get the same compiler error using the latest nightly, however, it looks like the fix has already been merged

**Comment by mitaa** [comment]
On the current nightly, `rustc --version` outputs for me `rustc 1.6.0-nightly (aad4e5665 2015-12-05)`

This does not yet include the fix.

**Comment by oli-obk** [comment]
it was merged yesterday, so it should probably be in today's nightly (2015-12-08)
