### ISSUE TITLE
doc: Book uses Result::expect() but still makes reference to Option::expect()

### ISSUE THREAD

**Issue by Sgeo** [rust-lang/rust#31912]
https://doc.rust-lang.org/book/guessing-game.html contains statements like

> If we leave off calling these two methods, our program will compile, but we’ll get a warning:

> Luckily, if we just want to crash if there’s a problem, we can use these two little methods. 

The book used to use `.ok().expect(...)`, but has switched to `.expect(...)`, from two methods for error handling/crashing to one.

**Comment by steveklabnik** [comment]
This has been fixed in nightly: https://doc.rust-lang.org/nightly/book/guessing-game.html

> If we leave off calling this method, our program will compile, but we’ll get a warning:

**Comment by Sgeo** [comment]
The first line looks fixed, but the second doesn't, "we can use these two little methods" is still present.

**Comment by steveklabnik** [comment]
I thought I accepted PRs for all of it, will double check. Thanks.
