### ISSUE TITLE
No nightlies for several consecutive days

### ISSUE THREAD

**Issue by alexbool** [rust-lang/rust#34572]
<img width="491" alt="screen shot 2016-06-30 at 10 15 07" src="https://cloud.githubusercontent.com/assets/1283792/16479914/541055f2-3eb4-11e6-87e4-36f399bbe2ae.png">
By the way, nice dashboard!

**Comment by Stebalien** [comment]
Apparently a known issue. Should be fixed now? @alexcrichton

**Comment by alexcrichton** [comment]
Indeed still a problem. [Two days' ago fix](https://github.com/rust-lang/rust/pull/34519) wasn't enough, and [yesterday's fix](https://github.com/rust-lang/rust/pull/34553) also wasn't enough. Looking into the next failure.
