### ISSUE TITLE
Build error with proc_macro crates and cross-compilation

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#37958]
In https://github.com/servo/servo/pull/14292, cross compilation fails with the following log: https://gist.github.com/jdm/ba11e5fe48fcbc186aecb15a857b54a6

xml5ever is a crate that depends on html5ever-atoms, which itself depends on heapsize_derive if the heap_size feature is selected. heapsize_derive defines `#[derive(HeapSizeOf)]` which xml5ever makes no use of.

**Comment by nox** [comment]
Cc @alexcrichton @jseyfried

**Comment by alexcrichton** [comment]
This may have been fixed by https://github.com/rust-lang/rust/pull/37846, unsure. @jseyfried would know for sure

**Comment by nox** [comment]
This landed 5 days ago so I doubt it. Will soon retry the branch with today's nightly.

**Comment by nox** [comment]
http://build.servo.org/builders/arm64/builds/4334/steps/compile/logs/stdio Still broken.

**Comment by jseyfried** [comment]
Now that ordinary crates can reexport proc-macros, rustc needs to load other `extern crate`s' `proc-macro` dependencies. During cross compilation, `proc-macro` dependencies are in a separate directory from ordinary dependencies, but cargo only links the ordinary dependencies.

**Comment by nox** [comment]
Could it just be [this typo](https://github.com/rust-lang/cargo/blob/1877f59d6b2cb057f7ef6c6b34b926fd96a683c1/src/cargo/core/manifest.rs#L75)?

**Comment by nox** [comment]
@jseyfried Did the build directory of `proc-macro` dependencies change after the `2016-11-02` nightly? Servo already uses `proc-macro` on that nightly and we have no cross-compilation build errors.

**Comment by jseyfried** [comment]
@nox 

> Could it just be [this typo](https://github.com/rust-lang/cargo/blob/1877f59d6b2cb057f7ef6c6b34b926fd96a683c1/src/cargo/core/manifest.rs#L75)?

I don't think that's related but it would be a good idea to fix regardless.
> Did the build directory of `proc-macro` dependencies change after the `2016-11-02` nightly? Servo already uses `proc-macro` on that nightly and we have no cross-compilation build errors.

No, but the `2016-11-02` doesn't support proc macro reexports, so rustc doesn't need to load other `extern crate`s' `proc-macro` dependencies when compiling a crate. Rustc was able to load a crate's own `proc-macro` dependencies because cargo passes these dependencies directly with `--extern proc_macro_crate=path/to/crate`.

@alexcrichton said this should be fairly simple to fix on cargo's end.

**Comment by emk** [comment]
At Faraday, we're trying to deploy our first Rust-based service into production, and it's blocking on this issue. (We cross-compile from Ubuntu to Docker containers running Alpine Linux, and we need `proc_macro` because our [BigML Rust client bindings](https://github.com/faradayio/bigml-rs) need to mix `serde` and `macro_rules` to avoid code duplication.) 

Here's an example. In `Cargo.toml`:

```toml
[package]
name = "cross_proc_macro_example"
version = "0.1.0"

[dependencies]
serde = "0.8"
serde_derive = "0.8"
```

In `src/lib.rs`:

```rust
#![feature(proc_macro)]

#[macro_use]
extern crate serde_derive;

#[derive(Serialize)]
pub struct Point {
    x: f64,
    y: f64,
}
```

In `examples/example.rs`:

```rust
extern crate cross_proc_macro_example;

fn main() {}
```

Error:

```
     Running `rustc src/lib.rs --crate-name cross_proc_macro_example --crate-type lib -g -C metadata=e2ae6c3617222432 -C extra-filename=-e2ae6c3617222432 --out-dir /home/emk/w/src/pr/cross_proc_macro_example/target/x86_64-unknown-linux-musl/debug/deps --emit=dep-info,link --target x86_64-unknown-linux-musl -L dependency=/home/emk/w/src/pr/cross_proc_macro_example/target/x86_64-unknown-linux-musl/debug/deps --extern serde=/home/emk/w/src/pr/cross_proc_macro_example/target/x86_64-unknown-linux-musl/debug/deps/libserde-05bbf4d3437164cb.rlib --extern serde_derive=/home/emk/w/src/pr/cross_proc_macro_example/target/debug/deps/libserde_derive-4c72d69e014dae87.so`
     Running `rustc examples/example.rs --crate-name example --crate-type bin -g -C metadata=e2ae6c3617222432 -C extra-filename=-e2ae6c3617222432 --out-dir /home/emk/w/src/pr/cross_proc_macro_example/target/x86_64-unknown-linux-musl/debug/examples --emit=dep-info,link --target x86_64-unknown-linux-musl -L dependency=/home/emk/w/src/pr/cross_proc_macro_example/target/x86_64-unknown-linux-musl/debug/deps --extern serde=/home/emk/w/src/pr/cross_proc_macro_example/target/x86_64-unknown-linux-musl/debug/deps/libserde-05bbf4d3437164cb.rlib --extern serde_derive=/home/emk/w/src/pr/cross_proc_macro_example/target/debug/deps/libserde_derive-4c72d69e014dae87.so --extern cross_proc_macro_example=/home/emk/w/src/pr/cross_proc_macro_example/target/x86_64-unknown-linux-musl/debug/deps/libcross_proc_macro_example-e2ae6c3617222432.rlib`
error[E0463]: can't find crate for `serde_derive` which `cross_proc_macro_example` depends on
 --> examples/example.rs:1:1
  |
1 | extern crate cross_proc_macro_example;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: Could not compile `cross_proc_macro_example`.
```

Are there any workarounds for this issue that might get us unstuck? If not, we could modify our build system to deploy on an Ubuntu container instead of cross-compiling to Alpine.

**Comment by jseyfried** [comment]
I fixed this in #38024 when no proc macros are reexported (in particular, both @nox's and @emk's use cases). The fix will probably be in the `2016-11-27` nightly.

This is still an issue (opened https://github.com/rust-lang/cargo/issues/3334) when proc macros are reexported, either via `pub extern crate proc_macros;`, `#![feature(macro_reexport)]`, or `#![feature(use_extern_macros)]`.

**Comment by jseyfried** [comment]
As we wait for #38024 to land, this can be worked around workaround by setting `RUSTFLAGS="-L dependency=/path/to/proj/target/(debug|release)/deps"`.

**Comment by emk** [comment]
@jseyfried Thank you for looking into this! I can confirm that your workaround works. I get a clean build using:

```sh
env RUSTFLAGS="-L dependency=target/debug/deps" cargo build --verbose --example=example --target=x86_64-unknown-linux-musl
```

**Comment by alexcrichton** [comment]
Cargo fix submitted as https://github.com/rust-lang/cargo/pull/3335
