### ISSUE TITLE
Add alias 'nonstandard_style' for 'bad_style'

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#41646]
@ashleygwilliams mentioned this in her talk today; `#[allow(bad_style)]` is a rather rebuke-y shame-y annotation on code.

While we do want people to use proper style, it's a useful tool whilst learning to be able to turn off all the _extra_ friction that you deal with that you don't have to. Let's be nicer about it; could we rename this to `nonstandard_style` and keep `bad_style` as a backcompat alias?

Unsure if this requires an RFC.

**Comment by Manishearth** [comment]
(Actual name of alias very bikesheddable, I just picked the first thing that came to mind.)

**Comment by skade** [comment]
Bikeshed: "relaxed_style" sounds good.

**Comment by leonardo-m** [comment]
"bad_style" sounds better than "nonstandard_style" because "nonstandard" sounds un-opinionated. The point of a "bad_style" annotation is to help people feel guilty.

**Comment by Manishearth** [comment]
Right, I'm questioning if that's a good thing. Do we need to? Even nonstandard_style (or in general, any warning-allow) does make you feel guilty, bad_style is just very much like a shaming and feels bad.

**Comment by mgattozzi** [comment]
Her talk was great. I think using something like relaxed_style or permissive_style would be a better choice then bad_style

**Comment by tumdum** [comment]
I think that 'any_style' is short and is not passive aggressive at all :)

**Comment by steveklabnik** [comment]
marking as both @rust-lang/compiler and @rust-lang/lang ; not sure who this falls under, really. Also nominating for discussion; I'm not sure if this requires an RFC or not.

**Comment by retep998** [comment]
As one of the heaviest users of `bad_style` (https://github.com/retep998/winapi-rs/blob/dev/src/lib.rs#L8), I'd like to voice my lack of opinion on this matter.

**Comment by ashleygwilliams** [comment]
i have no opinion on what we alias it as, but i would be very interested in an alias that is less shame-y. i am also very happy to implement once we decide what a good alias is!

**Comment by nikomatsakis** [comment]
For those readers who (like me) were not familiar with the `bad_style` group, it refers to a collection of 3 lints that enforce various capitalization conventions (e.g., `snake_case` methods, `SHOUTY_GLOBALS`, etc).

I'm in favor of renaming. I like `any_style` because it's short and easy to spell, but `#[deny(any_style)]` doesn't make any sense to me. =) 

Regarding whether this ought to have an RFC -- I could go either way; if we opt for no RFC, then we ought to at least do a "mini-FCP" here in the issue. TBH I'm not sure what team has ownership of lints though. =) I guess @rust-lang/lang?

**Comment by aturon** [comment]
I definitely don't feel this needs an RFC. I also wholeheartedly agree that we should change the name.

`nonstandard_style` or `alternative_style` seem good to me.

**Comment by whitequark** [comment]
> alternative_style seem good to me

Do we *really* want the "alternative facts" connotation? I can already see someone writing that awful snark and the HN frontpage it'll hit and I'd really rather not have it.

**Comment by aturon** [comment]
@whitequark 

Heh, I hadn't realized that the term "alternative" had gotten quite so poisoned! Anyway my preferences here aren't very strong.

**Comment by withoutboats** [comment]
I'm happy with any non-judgmental name, we can FCP the PR

**Comment by whitequark** [comment]
FWIW I like the `any_style` suggestion as it makes no statement about the particular style in question. I am not worried at all about this change leading to more deviation from conventions because:

  * humans are very good on exerting conformance pressure on their own, no need for the compiler assist;
  * the fact that warnings are emitted by default already make anyone new to Rust stop and think;
  * most Rust code is already uniform to a degree that I have not seen elsewhere, and there's no clear reason why that would suddenly change;
  * rustfmt isn't going to be very configurable, further fossilizing the conventional style.

If something I'm worried there's *too* much friction for even minor deviations; I don't think I'll ever use rustfmt, for example.

**Comment by joshtriplett** [comment]
Given that this comes up often in code translators (such as corrode), and potentially in binding generators as well, then having a more neutral alias for this seems appropriate.  I also don't think adding an alias needs an RFC.

I'm not going to add to the bikeshedding on the name itself.

**Comment by jseyfried** [comment]
`any_style` seems too broad -- it includes the standard style, so `#![deny(any_style)]` is weird.

I prefer `nonstandard_style` -- I think it's clearer than `alternative_style` since the latter could sound like we have an alternative in mind and isn't clear about to which it is alternative.

**Comment by est31** [comment]
As someone who has been annoyed by some C++ codebases that despite having official casing rules use different casing styles in parallel (including libraries using different casing styles), I am glad of those checks to be in the compiler and default on, because they create consistency. I believe this wish of consistency in this issue to be universal, so this isn't just a style issue where everyone can have its own, as your choice of casing gets forced upon the users of your library as well. I use tabs in my codebase and am writing `let v :Type = try!(foo())` instead of `let v: Type = foo()?` so I'm not "mainstream" regarding style, but those choices don't escape my codebase.

This check has many positive side effects. Like when reading code, you get accustomed to differentiate things inside lists of `use` clauses by their cases.

Looking at the issue from the other perspective, renaming the lint to `nonstandard_style` makes you feel intolerant when you type `#![forbid(nonstandard_style)]`. So one group gets always shamed.

Also, for beginners its important to see that the style they are doing is not fine, but rather something that is bad for the community of crates, especially their users, due to the inconsistency to the other crates on crates.io.

Overall though I don't feel very strongly about a rename, as long as the lint stays a warning by default.

**Comment by Manishearth** [comment]
> renaming the lint to nonstandard_style makes you feel intolerant when you type `#![forbid(nonstandard_style)]`. So one group gets always shamed.

No more than `#![forbid(bad_style)]`.

Beginners _already_ see that the style is not great. This is just about making it possible to design your own beginner experience without feeling bad about it. This doesn't change the warning's existence, it just changes the name so that it isn't discouraging when disabled.

**Comment by est31** [comment]
One example for how the snake case style helps you to identify a bug: https://is.gd/XArdpj

You need to look twice to see that the last case in the match is creating a new variable instead of being an actual enum variant.

**Comment by skade** [comment]
@est31 I find this example rather contrived (it switches off multiple layers of safety _and_ imports the matching shorthand).

Sure, "nonstandard_style" brings you half-way there, but the option is in the compiler and supported, this discussion is about an alias only.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

I agree we don't need an RFC. I'm moving that we agree to change the name to `nonstandard_style` (and deprecate -- but naturally not remove! -- the old name `bad_style`).

**Comment by est31** [comment]
> contrived

Its not a contrived example: I have encountered it in one of my programs. Luckily I had the `bad_style` lint turned on, so I didn't actually encounter the bug itself.

> Sure, "nonstandard_style" brings you half-way there, but the option is in the compiler and supported, this discussion is about an alias only.

No, its about deprecation as well, and probably a Rust 2.0 or something will remove the name.

**Comment by Manishearth** [comment]
Most lints prevent bugs. That isn't an argument for giving it a name like that.

> its about deprecation as well

deprecating the name, not the lint.

**Comment by alteous** [comment]
My opinion on this, which is clearly unpopular, is that `bad_style` should not have an alternative. `nonstandard_style` does not convey the same message to the author of the code of which other people may depend upon in their 'good style' projects. Unless I'm mistaken, the whole point of this RFC is to replace `bad_style` with something that doesn't hurt people's feelings, which I think is a bit ridiculous.

**Comment by Havvy** [comment]
I rather like `#[allow(any_style)]` because the standard style is still technically a part of any style, while it's obviously not a part of `nonstandard_style`.

@alteous Avoiding unnecessarily hurting peoples' feelings is a good thing. The compiler is supposed to be helpful, not a drill sergeant.

**Comment by internetionals** [comment]
I just wanted to offer a few different alternative names:

    arbitrary_style

Or:

    other_styles

The last one would read correctly in pragmas:

    #[allow(other_styles)]
    #[forbid(other_styles)]

**Comment by est31** [comment]
When I had to use C/C++ libraries with inconsistent styling, I really felt horrible. I haven't yet used any non standard named Rust library, as fortunately there are only a very few, but if I did, I would certainly feel horrible as well, as I'd most likely would have to mix naming styles in my program.

`any_style` (or `arbitrary` or `other`) is even worse than `nonstandard_style`. `nonstandard` at least says that the style is not the standard from the compiler message.

**Comment by chris-morgan** [comment]
I’m slightly in favour of renaming `bad_style` to `nonstandard_style` on its own merits (it’s more precise), but strongly against any of the other proposed directions of alteration.

**Comment by sunjay** [comment]
How about `nondefault_style` or `nonrecommended_style` (or some other synonym of default/recommended)?

```rust
#[allow(nondefault_style)]
// Or
#[allow(nonrecommended_style)]
```

I think this name makes sense because the style being enforced is literally the default. It's just the standard we "recommend" people use, but otherwise there's no reason why someone else couldn't have their own "standard" that they follow in their project or organization. 

Saying "allow nonstandard style" could cause confusion for people unfamiliar with the lints. If they don't know that we're talking about the "Rust recommended standard", they might look at that and wonder why someone would try to allow breaking their team's standards. I can't say how likely that is, I'm just commenting on the connotation of the word. 

The real issue stated in my own words is that there is currently a default/recommended style that sometimes shouldn't be abided by and we want to allow people not to use that without getting shamed. Default and recommended are both unopinionated words and also honest about what we're talking about.

I'm open to other synonyms of these words too. They're just the first ones that came to mind. :)

**Comment by dpc** [comment]
As a devoted tab user, I swallowed my pride and gave up tabs for spaces in Rust. I configured all my tools to use spaces in `*.rs`. All that to help make our shared ecosystem is a better place: one with a standard, uniform style. I consider that to be one of many important strengths of Rust: we can dedicate all our time to make our code compile, instead of arguing where do closing parenthesis go, or how to capitalize a given identifier. And when we jump to implement a PR, or use a library, we don't ever have to feel: "yak, I'm so displeased by the author's arbitrary opinions about the style that are different than my arbitrary opinions".

Any style that is different is just it: a bad style. `nonstandard` suggests that there are acceptable alternatives. There are not, and there shouldn't ever be. 

With time more, and more people will be using Rust. They will be coming from different environments, with different preferences, etc. The community will spread and fracture - it's inevitable. We don't want to manually, and intrusively ask new developers each time: "Excuse me, we agreed on the style in Rust long time ago, we are all used to it now. We know you have 20 years of X experience and enjoy jour snakeCaseNames very much, but could you be nice and conform for preserve unity?" . I don't want to have these conversations. I would rather have the compiler send a bit rude, but impersonal "your style is bad, and you should feel bad" message, and then all of be able to fell "Oh, another awesome Rust-hacker, using the exactly same style as I do. How awesome!" all the time.

In extreme case, one day, we might wake up in a world where some bigger companies adopted Rust, and because they were previously doing X, they wrote their official rules to use X-like style in their Rust. And now this is "their Rust style", and it's not "bad", it's just "nonstandard".

Because of all the above, if the `bad_style` is to change, it should change to `bad_style_and_i_feel_bad_for_using_it`. ;)

**Comment by HeroesGrave** [comment]
A few more ideas:

`#[allow(casual_style)]` because ignoring style guides without good reason is unprofessional, but if you're not in a professional environment then it's probably okay.

`#[allow(no_style)]` because you're either following the style guidelines or you're not.

`#[allow(unconventional_style)]` and `#[allow(nonconformant_style)]` have no connotations but are still reasonably clear that the style is incorrect. They also have the added bonus of being longer to type.

I think it's important to convey that not following the style guidelines is bad, regardless of whether the message is blunt (`bad_style`) or a bit more subtle/tactful.

**Comment by boomlinde** [comment]
How about `ungood_style`?

**Comment by retep998** [comment]
`doubleplusungood_style`.

**Comment by wenjin21** [comment]
While I am very much aware of @ashleygwilliams story of introducing Rust to npm, I have my doubts on whether "new Rust users who feels bad and deterred from learning by `#[allow(bad_style)]` but feels better with an alias to `bad_style`" describes a significant part of the population.

I'd like to note that I am biased as I have always favoured the standard style, but a poll may be helpful here to find out whether such a change will actually have significant positive effects.

**Comment by letheed** [comment]
I don't think `free_style` has been proposed yet.
I don't really care, though I do support having a less judgmental alias.

**Comment by michael-zapata** [comment]
If people are deterred by that, I think it's a good idea to change it (Whether or not it affects a lot of people doesn't matter, really). Being more inclusive can't possibly be a bad thing. :)

**Comment by skade** [comment]
@wenjin21 There are multiple reasons for not calling non standard style not bad style, even beyond that. I do subscribe to Ashley's notion though, calling "beginner style" "bad style" _has repercussions_ (FWIW: I teach Rust to beginners regularly). Switching off the lint for beginners should not imply shaming at all, because it is a measure of reducing cognitive overload for a while.

Then, you basically have to 2 different cases:
1) Experienced programmers know the value of standard code and then quickly learn towards it. If they don't know, Rust won't teach them.
2) Absolute beginners don't know the value of standard code, especially when they are trying to just get things working. Which means you have to teach them. But that's a meta subject and not to be tought by rustc. Shaming beginners into something also never works.

Finally, tastes _will_ change over the evolution of the language and I'm certain that there will be a subcommunity evolving that follows a different coding standard. This is also not `bad_style`, although we don't have that style yet.

**Comment by est31** [comment]
> Finally, tastes will change over the evolution of the language and I'm certain that there will be a subcommunity evolving that follows a different coding standard. 

I don't think this is something Rust should aim for or support in any way. Let me reiterate that there is a difference between style like tabs vs spaces, which doesn't really escape your codebase, and naming style of your functions/types, which does escape your codebase, because literally every user of your library has to type your types sooner or later. If a library uses a "nonstandard" style for naming, its a clear deterrent for me to not use it, because I simply don't want to use its style, whereas I don't care whether the library uses tabs or spaces. Personally, I have a very non standard style in many ways, like I use tabs. However, I haven't disabled any `bad_style` lint nor do I intend to.

The point you do with beginners is better. However, I think that if they have `bad_style` in their codebase they will much more likely try to abandon that kind of style than if they had `nonstandard_style`.

**Comment by CodesInChaos** [comment]
*style* is pretty broad. I'd prefer something more specific like *naming* or *case*.

**Comment by skade** [comment]
@CodesInChaos we already have these, e.g.:

```rust
#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
```

This is a collective lint that includes all these at once.

**Comment by vojtechkral** [comment]
Let me in all politeness and for the benefit of a greater audience ask whoever is in charge (the lang team? the community team?) to not go too far in the whole social justice thing. While it is surely possible to not do enough in that direction, it is also definitely possible to go too far. This bug is already gaining attention on social media and if it were filed by someone outside the team my first impression would probably be that it was not meant seriously.

As to the issue at hand, I don't understand how and _why_ the lint `bad_style` , which is an output of a compiler processing some files, is being connected to a person or persons, because that's something that's absolutely not the purpose and meaning of a lint warning. A lint is not a piece of omniscient AI that scrutinizes someone's qualities or place in the society or whatever. How ridicuous a notion is that? Lint is just a fairly stupid(*) automated check of _code_ (**not** people) that doesn't have _any_ idea about people. It just processes some code and outputs a diagnostic, end of story. No shaming, no implications to anyone's worthiness.

Of course, it is entirely possible for someone to actually honestly have a serious psychological condition that causes all sorts of trouble in their life, but treating/accomodating for of such a condition is _galactically_ out of the scope of a compiler and, mind you, also probably even outside of what the community can do, since such cases usually are best handled by professionals with appropriate credentials rather than folk psychology.

*) Authors of rust lints, please forgive the remark, lints are great! :)

**Comment by pnkfelix** [comment]
Moderator note: I quickly skimmed over the comments here (there was some concern that the thread was getting detailed).

I didn't identify any comments that were out-of-line for the community.

Some commenters have registered their opinion that a change is not necessary here; but the members of the language team have [all weighed in](https://github.com/rust-lang/rust/issues/41646#issuecomment-303801050), so it seems clear that all of the language team members at the very least do not object to this change in principle.

Other commenters have suggested alternative names for the lint. I personally think bikeshedding the right choice of name  actually *is* a reasonable activity during the Final Comment Period (FCP). (I'll comment more about this in a second).

----

Anyway, I did discuss the locking of the thread with @carols10cents .

While I don't think the locking was strictly necessary (as mentioned above, there have not yet been any CoC violations), I also understand why she did it (the thread is getting undue attention from communities that are not beholden to our CoC), and I don't regard the locking itself as a CoC violation.

However, I also think that it would not make sense to have a final comment period of 10 days (which started five days ago, due to a certain [lang team member's](https://github.com/pnkfelix) tardiness in checking off ~~my~~ their box), where the comment thread was only open for five of the days.

So, what I propose is this: Lets leave the thread locked for "cooling off period." We'll treat the FCP as "on pause" while the thread is locked. When we re-open the thread, the final comment period will resume for another five days. Hopefully any community member who has a major concern to register regarding this issue, but cannot due to the lock-down, will be willing to wait for the thread to re-open.

**Comment by steveklabnik** [comment]
> I didn't identify any comments that were out-of-line for the community.

The comment by @vojtechkral is borderline calling people mentally ill. I find the 1984 references in bad taste, and outside of the context, derailing at best, but in-context, worse.

Speaking of context, (as noted by @vojtechkral and @pnkfelix both) this thread (thanks to @kmcallister) is currently being passed around lots of places that hate us . In cases like this, I personally would prefer moderation take a slightly heavier touch than usual; as it usually means that whoever the person who is in our community who is taking heat is taking it from multiple places. We can't stop the internet from doing what they'll do, but we can take a strong stance *inside* Rust spaces to both give them some breathing room and to let people know we have their backs.

This matters because if the story is "yeah, I mean when I comment on a Rust thread, it's mostly fine, but then it ends up getting linked on `WEBSITES` and not only do I get harassed elsewhere, but a ton of bad comments get left derailing my thread, and the mods say "this is bad enough to lock but not bad enough to suggest that anyone did anything wrong"," then we're going to have people not want to participate in big decisions in Rust. And that's likely a huge loss, and in fact, works *against* not only our stated goals, but also active initiatives we're working on. This isn't a theoretical thing, I can think of multiple previous times where this has happened.

Normally I'd just email the mod team with this kind of thing, but I think making this comment in public is important. That said, I also don't want to derail the thread any more either, so this is the only comment that I'll make about it.

**Comment by carols10cents** [comment]
Proposal for the name from notriddle via IRC: `non_standard_style` because it's more consistent with the names of `non_camel_case_types` and `non_snake_case`.

**Comment by pnkfelix** [comment]
*moderator note*: more than 24 hours have elapsed, so I'm ending the cooling off period and unlocking the issue so that FCP can resume.

**Comment by dpc** [comment]
So after some discussion on reddit I'd like to confirm official stance on the naming style.

Is Rust community OK with people picking different naming styles (typically because of personal preference)? How strongly do we discourage it as a community, if at all?

If the stance is "mild" or less then maybe `nonstandard` is indeed a more truthful word.

Also, I'd like to point out that `nonstandard_style` is longer, and thus more typing/noise for people that apply it sparsely where needed.

**Comment by joshtriplett** [comment]
On Wed, Jun 21, 2017 at 10:28:33AM -0700, Dawid Ciężarkiewicz wrote:
> So after some discussion on reddit I'd like to confirm official stance on the naming style.
> 
> Is Rust community OK with people picking different naming styles (typically because of personal preference)? How strongly do we discourage it as a community, if at all?

I think it's stronger than "use what you like, it's a personal
preference"; there's significant value to uniformity across the majority
of Rust codebases. It's more that, if you're working on code derived
from some other environment (such as Windows code, -sys code for a
library, etc) where there's also significant value in matching the names
from that environment, then attaching a stigma to that seems harsh. We
*want* to encourage people to integrate Rust with other environments,
after all.

So, something like "non_standard_style", "unconventional_style",
"non_rust_style", "non_rustic_style", or similar seems appropriate for
that.

**Comment by Manishearth** [comment]
It's also "people will probably avoid using your crates if it's using nonstandard style without good reason". ("good reason" can be for stuff like FFI bindings or when you need uniformity with existing APIs)

**Comment by est31** [comment]
> "good reason" can be for stuff like FFI bindings

Idk, but the FFI bindings (except for the -sys crates) I've encountered all changed names to the official Rust casing style.

**Comment by skade** [comment]
@est31 I think -sys is what @Manishearth is talking about. I'd call the parts making the API Rust-like "wrapper".

**Comment by Manishearth** [comment]
I'm talking about the -sys crates. (Or FFI crates which don't follow the sys model that have the bindings in the same crate as the wrapper)

Also, generated code for example may end up breaking these rules in corner cases. E.g. `foo__bar` is not considered snake case by the compiler. In Stylo we codegen function names for CSS properties by replacing `-` with `_`. So the function for setting the `font-size` property is `set_font_size`. But this means the function for setting `-x-lang` is `set__x_lang`, which hits the lint. We could special case code generation for this, but it seems really unnecessary; so we just disable this lint on these functions.

In Servo's script crate we use CamelCase function names for DOM methods (sometimes a tweaked convention is useful for drawing attention to things).

**Comment by sgrif** [comment]
Just to chime in here -- Diesel is a major user of "non-standard" style, Our generated code typically at minimum uses non camel case types. This is so our generated types have exactly the same name as they would have in your SQL so that `users::name` maps to `users.name` in SQL. We also avoid capitalizing in several cases because we don't want the user to care about whether something is a constant, unit struct, or local variable.

My point is that there are many legitimate use cases for "non-standard" style. I've always avoided `#[allow(bad_style)]` because that particular alias put a bad taste in my mouth. We've always preferred listing the 3 aliases instead. I like this change quite a bit. The idea that giving this a less sham-ey name will somehow lead to the Rust community being a mash-up of camel-case and snake case is completely ridiculous.

**Comment by chris-morgan** [comment]
@carols10cents `nonstandard_style` should be preferred to `non_standard_style` because language is a popularity contest, and [“nonstandard” is ahead of “non-standard”](https://books.google.com/ngrams/graph?content=nonstandard%2Cnon-standard&year_start=1900&year_end=2008&corpus=15). Language is funny in its inconsistencies.

**Comment by cbreeden** [comment]
Quoting @CodesInChaos
> style is pretty broad. I'd prefer something more specific like naming or case.

Quoting @nikomatsakis 
> For those readers who (like me) were not familiar with the bad_style group, 

### Naming

I'm sure I'm not the only one who, after learning about `bad_style`, was surprised about what it actually meant. I first thought `#![allow(bad_style)]` simply meant turn off all warnings.  Sure, casing for names is generally considered a part of _style_, but so is indentation, and many other things.  I did a quick check of all the lints described in `rustc -W help` and there isn't a single lint there that required to me look at the definition besides `bad_style`. I don't think `nonstandard_style` is any better. I'd recommend we don't use the word "style" at all in this lint, and give it a more descriptive name. For instance, how about `nonstandard_casing`.

One concern brought up, was that `nonstandard_casing` may not be general enough for an umbrella lint.  For instance, I could imagine a scenario where `non-ascii-idents` is accepted into the language, and we decide that we should lint against using some easily ambiguous codepoints, or zero width spaces, or something.  So perhaps `nonstandard_naming_convention`.

### Impact

Perhaps this was generally understood by everyone, but I think it was worth mentioning at least once.  A library author changing from `#![allow/deny(bad_style)]` to `#[allow/deny(new_name)]` is _i think_ generally accepted as a breaking change since it will require a bump in the minimum compiler version.  Fortunately, this can be fixed in a backwards compatible way by listing out all three lints.  Which is a little unfortunate, but also reasonable.

**Comment by Manishearth** [comment]
We're not actually removing bad_style though, and I wouldn't expect authors to change existing code for it.

I like nonstandard_naming_convention. bad_style is vague, nonstandard_style is less vague but still vague.

**Comment by lnicola** [comment]
Or maybe `nonstandard_naming` if `nonstandard_naming_convention` is too long. I don't think "naming" can be misinterpreted to mean something else.

**Comment by cbreeden** [comment]
@Manishearth oh, I thought the decision was to deprecate bad_style, which would include a lint.  It wouldn't require authors to change it, but it would be quite annoying to see a `bad_style` lint everytime winapi compiled for instance.

**Comment by retep998** [comment]
As I mentioned earlier, I don't really care what aliases you add. Just don't deprecate the existing lint causing warnings for crates that allow `bad_style`.

**Comment by eddyb** [comment]
@cbreeden @retep998 FWIW you can't see lint warnings from dependencies because Cargo passes the `--cap-lints allow` option for them, effectively silencing everything (except `forbid`, maybe?).

**Comment by Manishearth** [comment]
IIRC forbid is silenced too. This lets lint changes not be breaking changes because at worst they will break the current crate you are working on (and not some dependencies), and you can easily fix that crate.

**Comment by Manishearth** [comment]
> oh, I thought the decision was to deprecate bad_style, which would include a lint

no worries, this wasn't clear. When I mentioned "backcompat alias" I implicitly meant that it would not actually be deprecated.

**Comment by est31** [comment]
rfcbot is missing that one day though where the comment period was paused, no? So its only complete tomorrow.

**Comment by scottmcm** [comment]
Any of these ending in `_style` seem unhelpfully vague to me, especially once rustfmt's standard style becomes more widespread -- could it include indenting one day?  Who knows!

Another option: `unusual_casing`

**Comment by cbreeden** [comment]
The final comment period has be over for 20 days now.  Reading through the comments, it appears that most opposition for this change is the desire to maintain an "opinionated" lint, to communicate that it is strongly discouraged to form a habit of writing rust code using a non-idiomatic naming scheme.

Personally, I don't see this as an issue, since it requires opt-in and so I feel that the primary users of disabling this lint will either be:
1. Authors of wrapper libraries who prefer to keep the naming conventions of the library they are wrapping.  This is commonly seen in `-sys` libraries.
2. Individuals who are new the language, who would prefer to ignore some non-essential lints while they are learning the language.

In particular, it will require an conscious decision to ignore the lints for breaking the idiomatic naming scheme. I also feel that the individual lints that `bad_style` currently wraps is equally unopinionated: `NON_CAMEL_CASE_TYPES`, `NON_SNAKE_CASE`, `NON_UPPER_CASE_GLOBALS`.

I think one issue that hasn't been decided on yet is the actually name of the new lint.  I have already voiced my concerns that we should strive for a lint that more accurately describes the lint group for which it is wrapping, where the word `style` is generally too vague in this context.  Alternatives that have been proposed:
1. `nonstandard_casing`, and `non_standard_casing`.  (may have backwards compatibility issues if we wish to add lints from `non-ascii-idents`).
2. `nonstandard_naming`.
3. `unusual_casing`.

How should we proceed?

**Comment by nikomatsakis** [comment]
I definitely think we should go forward with the change. I am somewhat indifferent as to whether we adopt `non_standard_style` vs something else. Everything seems to have downsides -- style is a bit vague, but "casing" doesn't feel (to me) like a "real word", and "naming" seems off because we're not talking about the names themselves, just the, well, style in which they are written. I guess, in the interest of making progress here, I vote we just go with `non_standard_style`.

**Comment by aturon** [comment]
Note that what's needed next is a PR implementing the change. Anyone want to take that on?

**Comment by ashleygwilliams** [comment]
@aturon my offer still stands :) (been waiting for this moment, haha)

**Comment by aturon** [comment]
@ashleygwilliams You got it! @Manishearth is probably a good person to hit up if you have questions.

**Comment by ahmedcharles** [comment]
Just pointing out something that should've been obvious. The three lints that are under this one, all end in `case`, not `style`, so why should the group name end in `style`, which implies something broader than is actually the case, no pun intended. `non_standard_case` seems like it would be better.

**Comment by Manishearth** [comment]
The lint group may expand on the future though.

(a lot of recent RFCs have talked about introducing new style conventions along with a feature)

**Comment by ahmedcharles** [comment]
That could be backwards incompatible for both uses of `#[allow(bad_style)]` and `#[deny(bad_style)]` currently, though I'm not sure if the stability story has an exception for lints (probably does). But it would still be rather unfortunate to add things that are sufficiently different.

Beside, you could just have a hierarchy of groups, where a future group is created that's more general and adds this group.

**Comment by Manishearth** [comment]
Lints don't affect backwards compatibility as much due to `--cap-lints` being the default cargo behavior.

The heirarchy thing feels like a hack to me, and also ends up with two lint groups that are confusing.

(Anyway, this issue is now accepted, I don't think this is the venue to rehash this further)

**Comment by CounterPillow** [comment]
Why not `retarded_style`, named in honour of the original issue reporter?

**Comment by lnicola** [comment]
@CounterPillow Please don't do this, regardless of whether you agree or not with this change. You have no excuse for being impolite.

**Comment by CounterPillow** [comment]
@lnicola I identify as someone who has an excuse for being impolite. You can't dictate my identity.

**Comment by BurntSushi** [comment]
I've removed a couple comments that violate our CoC, and am temporarily locking this issue to prevent further trolling. We can re-open this in 24 hours.

**Comment by Boofysaurus** [comment]
BurntSushi I'm offended by your name
http://www.urbandictionary.com/define.php?term=burnt%20sushi&utm_source=search-action
please change it to CookedSushi, that will make me feel better :'(

**Comment by Boofysaurus** [comment]
Sorry my last comment was inappropriate I shouldn't have linked urban dictionary. however I find the name very offensive still.

**Comment by Manishearth** [comment]
This was fixed in https://github.com/rust-lang/rust/pull/48386

**Comment by carols10cents** [comment]
@Manishearth #48386 has [a comment from you](https://github.com/rust-lang/rust/pull/48386#issuecomment-367131248) saying that it doesn't fix this issue completely, reopening because I don't see any other linked PRs

**Comment by Manishearth** [comment]
Oops, sorry!!

**Comment by WiSaGaN** [comment]
> Moderator note: I've removed a couple comments that violate our CoC, and am temporarily locking this issue to prevent further trolling. We can re-open this in 24 hours.

While I agree with this naming change, I don't agree with moderator implying people are "trolling" when they voice their disagreement.

In Wikipedia, Troll is defined as
> In Internet slang, a troll is a person who starts quarrels or upsets people on the Internet to distract and sow discord by posting inflammatory and digressive, extraneous, or off-topic messages in an online community (such as a newsgroup, forum, chat room, or blog) with the intent of provoking readers into displaying emotional responses and normalizing tangential discussion, whether for the troll's amusement or a specific gain.

The disagreement in this thread may be unpleasant, or sometimes even inflammatory, but we need to have some concrete evidence to prove the *intent* of those messages are "provoking readers into displaying emotional responses and normalizing tangential discussion" before labeling them as "trolling", even more so when it's coming from moderators. This is especially important when we strive to achieve an inclusive community that welcomes diversity. True diversity is not about people with different colors of skin or gender with the same level of preferrance for how we should approach social progression, it should be about really including everyone who wants to make Rust better. This includes people who comes from a different culture and may not know different nuances in western / English expression, people who are not good at English to express their opinions as eloquantly as others, people who may not be able to express their frustration in a calm, articulating, and constructive way. Removing some of the remarks is sometimes necessary for a better community, but this should not be done assuming the intent of those participants, and we should not lable them as "trolls", "shills", "bots" or other things just because they may have a different opinion that is expressed in an undesirable way.

**Comment by retep998** [comment]
Good thing Github now allows people to hide comments rather than deleting them, so going forward we'll be able to benefit from the increased transparency and when actual troll posts are hidden people won't think the moderator team was incorrect in that decision.

**Comment by mbrubeck** [comment]
Please direct comments about moderation to the moderators or to new forum threads.
