### ISSUE TITLE
db-accelerate-2.0.0 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43660]
[db-accelerate](https://crates.io/crates/db-accelerate) version 2.0.0 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/db-accelerate-2.0.0/log.txt)):

```
error: failed to parse manifest at `/source/Cargo.toml`

Caused by:
  can't find `tests` test, specify test.path
```
cc @calebmer

**Comment by alexcrichton** [comment]
Fixed by https://github.com/rust-lang/cargo/pull/4389

**Comment by est31** [comment]
The bug still appears in `1.20.0-beta.2`: http://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/reg/db-accelerate-2.0.0/log.txt

**Comment by alexcrichton** [comment]
Not a regression I believe, the failure mode just changed. Tests don't work and depending on the crate works on beta/stable, closing.
