### ISSUE TITLE
prometheus-0.2.8 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43675]
[prometheus](https://crates.io/crates/prometheus) version 0.2.8 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/prometheus-0.2.8/log.txt)):

```
Aug 03 15:46:49.217 INFO kablam! error: failed to parse manifest at `/source/Cargo.toml`
Aug 03 15:46:49.217 INFO kablam! 
Aug 03 15:46:49.217 INFO kablam! Caused by:
Aug 03 15:46:49.217 INFO kablam!   can't find `benches` bench, specify bench.path
```
cc @prepor @siddontang

**Comment by overvenus** [comment]
Hi @est31 

I has sent a PR[1] for this issue, it should fix the `can't find` error on next prometheus release.

Thank you!

[1] https://github.com/pingcap/rust-prometheus/pull/110

**Comment by overvenus** [comment]
FYI, there is a workaround for this bug, get prometheus from the git repo, see more: https://github.com/pingcap/tikv/pull/2159/commits/a1c994e4e95b216641ef6659b9189932d3b2a04e :grinning:

**Comment by alexcrichton** [comment]
Fixed by https://github.com/rust-lang/cargo/pull/4389

**Comment by est31** [comment]
Still appears to happen on 1.20-beta.2: http://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/reg/prometheus-0.2.8/log.txt

**Comment by est31** [comment]
Version 0.3.0 is also affected: http://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/reg/prometheus-0.3.0/log.txt

**Comment by alexcrichton** [comment]
Not a regression I believe, the failure mode just changed. Depending on the crate works and otherwise the packaged version has an invalid manifest.
