### ISSUE TITLE
Regression in what path is chosen for error messages

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#45070]
```rust
#[macro_use]
extern crate serde_derive;

#[derive(Serialize)]
struct S;

fn main() {
    i32::from(""); // error
}
```

#### Error with rustc 1.21.0-beta.3 (ea1fd7d42 2017-09-15):

```
error[E0277]: the trait bound `i32: std::convert::From<&str>` is not satisfied
 --> src/main.rs:8:5
  |
8 |     i32::from(""); // error
  |     ^^^^^^^^^ the trait `std::convert::From<&str>` is not implemented for `i32`
```

#### Error with rustc 1.22.0-nightly (417c73891 2017-10-05):

```
error[E0277]: the trait bound `i32: _IMPL_SERIALIZE_FOR_S::_serde::export::From<&str>` is not satisfied
 --> src/main.rs:8:5
  |
8 |     i32::from(""); // error
  |     ^^^^^^^^^ the trait `_IMPL_SERIALIZE_FOR_S::_serde::export::From<&str>` is not implemented for `i32`
```

I would expect the error message to show `std::convert::From`, not Serde's re-export at least in code that has nothing to do with Serde.

**Comment by ExpHP** [comment]
https://github.com/rust-lang/rust/compare/d93036a04...dead08cb3

Only two big merges in this timeframe. cc @alexcrichton?

**Comment by alexcrichton** [comment]
Sorry I don't know what there may have led to this :(

**Comment by najamelan** [comment]
@dtolnay I have the impression this is fixed on 1.23, can you confirm?

**Comment by dtolnay** [comment]
Seems like it. Thanks!

**Comment by dtolnay** [comment]
Reopening because while the original code now gives a reasonable error, I am still seeing `serde::export` in error messages seemingly at random. With rustc 1.23.0-nightly (e97ba8328 2017-11-25):

```rust
extern crate serde;

fn main() {
    struct S;
    S.clone();
}
```

```
error[E0599]: no method named `clone` found for type `main::S` in the current scope
 --> src/main.rs:5:7
  |
4 |     struct S;
  |     --------- method `clone` not found for this
5 |     S.clone();
  |       ^^^^^
  |
  = help: items from traits can only be used if the trait is implemented and in scope
  = note: the following trait defines an item `clone`, perhaps you need to implement it:
          candidate #1: `serde::export::Clone`
```

Adding `extern crate chrono` before `extern crate serde` fixes the message, but adding it after and the message is still wrong.

**Comment by najamelan** [comment]
I also see error messages that change when the order of `use`  statements is changed, which was unexpected for me. But maybe that's for a different issue? I agree that in the code example you show above it is undesirable to mention serde in the error, but maybe I miss something fundamental about how serde interacts with compilation.

**Comment by dtolnay** [comment]
#46112 has some more examples of what looks like the same bug.

**Comment by dtolnay** [comment]
Fixed by #46708 and #46838.
