### ISSUE TITLE
`no_mangle`/`used` static is only present in output when in reachable module

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#47384]
Statics that are marked `no_mangle` and/or `used` only get to the linker if they are in a reachable module of a reachable crate. The static itself does not need to be used in code, only some function in the same module. This previously worked in our project, so this seems like a regression.

## Example
The issue is best explained with a small example crate named `bug_test`, which can be found [here](https://github.com/phil-opp/rust-issue-47384):

`src/lib.rs`:
```rust
pub mod foo {
    #[no_mangle]
    #[used]
    pub static STATIC: [u32; 10] = [1; 10];

    pub fn hello() {}
}

pub fn bar() {
    foo::hello(); // STATIC not present if commented out
}
```
`src/main.rs`:
```rust
extern crate bug_test;

fn main() {
    bug_test::bar(); // STATIC not present if commented out 
}
```

Linker script `linker.ld`:
```linker
SECTIONS
{
    .static : ALIGN(4)
    {
        KEEP(*(.rodata.STATIC));
    }
}
```

Build using:

```
RUSTFLAGS='-Z pre-link-args=-Tlinker.ld' cargo build
```
Show contents of `.static` section:

```
> objdump -s -j".static" target/debug/bug_test

target/debug/bug_test:     file format elf64-x86-64

Contents of section .static:
 3354c 01000000 01000000 01000000 01000000  ................
 3355c 01000000 01000000 01000000 01000000  ................
 3356c 01000000 01000000                    ........  
```

Comment out one of the `STATIC not present if commented out` lines and recompile. Then `STATIC` no longer exist in the output and the `.static` section is empty:

```
> objdump -s -j".static" target/debug/bug_test

target/debug/bug_test:     file format elf64-x86-64

objdump: section '.static' mentioned in a -j option, but not found in any input file
```

## Versions

```
> rustc --version
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
> cargo --version
cargo 1.26.0-nightly (008c36908 2018-04-13)
> ld --version
GNU ld (GNU Binutils for Ubuntu) 2.26.1
```

**Edit**: Added the `used` attribute.

**Comment by phil-opp** [comment]
cc @oli-obk

**Comment by nagisa** [comment]
Doesn’t seem like a bug to me. For several reasons.

The library `bug_test` is a `rlib`, so it has no guarantees as to what appears in the binary or what doesn’t. Eventually `rlib` probably is expected to not contain any executable code whatsoever and not use a linker, which would break your linker script approach either way.

With that in mind, Rust does not specify any guarantees with regards of linking to `rlib`s and `dylib`s. Only the output of `cdylib`, `staticlib` and, AFAIK, `obj` are specified in any way. In your scenario it is entirely up to Rust whether:

1) it uses a linker when generating code for the intermediate crates;
2) it emits any binary or linkable code into the rlib or just aggregates intermediate representations and generates all the code in one go during the final binary compilation;
3) it optimises out unused globals for the binary (in absence of preventative attributes such as `#[used]`) before they reach the linker.

**Comment by joshtriplett** [comment]
@petrochenkov I recall that as well, and that sounds accurate.

**Comment by oli-obk** [comment]
IIRC we tried both the used attribute and making it public and it gave us the same behaviour.

**Comment by phil-opp** [comment]
> IIRC we tried both the used attribute and making it public and it gave us the same behaviour.

Yes, `used` does not change anything. This behaves exactly the same:

```rust
// src/lib.rs

#![feature(used)]

pub mod foo {
    #[no_mangle]
    #[used]
    pub static STATIC: [u32; 10] = [1; 10];

    pub fn hello() {}
}

pub fn bar() {
    foo::hello(); // STATIC not present if commented out
}
```

**Comment by phil-opp** [comment]
So @japaric explained that this is a problem with our linker script and has nothing to do with the `no_mangle` and `used` attributes: https://github.com/rust-lang/rust/issues/40289#issuecomment-385609104. The fix is to add an `EXTERN(STATIC);` declaration to the linker script, which tells the linker to keep looking for a `STATIC` symbol, even if all other symbols are already resolved.

**Comment by dtolnay** [comment]
Reopening because people continue to have problems with `#[used]` statics failing to appear, even in use cases without a custom linker script.

- https://github.com/dtolnay/inventory/issues/7
- https://github.com/dtolnay/inventory/issues/9
- https://users.rust-lang.org/t/link-section-in-libraries-discarded/28349

**Comment by CJKay** [comment]
FYI I managed to work around this in my case by doing the following:

- In the linker script, specify `EXTERN(xyz)` where `xyz` is a symbol you are trying to export (you actually only need to do this for one symbol, I assume because it stops the linker from removing anything else in that library (object file?))
- Mark the symbol as `#[no_mangle]` and `pub`
- `pub use` the symbol from the binary module

Realistically, this is not a long-term solution - the first step is reasonable, but steps 2 and 3 are just hacks. There's no reason the symbol should have to be given an unmangled name, and definitely no reason the binary should have to pollute its own code to work around unusual linker behaviour.

Additionally, some of the time `rustc` warns that the `#[no_mangle]` is not used, but I can't reproduce that reliably.

**Comment by oli-obk** [comment]
> Additionally, some of the time rustc warns that the #[no_mangle] is not used, but I can't reproduce that reliably:

That should be fixed on master, can you confirm that it is fixed for you now?

**Comment by zachreizner** [comment]
I ran into this issue today, and strangely only in debug builds. With `--release`, the `#[used]` `static` items from an otherwise unreachable module appeared in the resulting binary. My theory is that the divergent behavior is due the default incremental builds in debug mode. Adding this to my `Cargo.toml` seems to fix this issue, but it feels way to brittle to rely on:

```toml
[profile.dev]
incremental = false
```

**Comment by Shnatsel** [comment]
This issue is still present for me. It occurs in release mode both with and without LTO. Using `#[link_section = "foo"]` doesn't help. Actually using the static in some other code does preserve it.

Comment out the `println!` with a function call to reproduce: https://github.com/Shnatsel/rust-audit/blob/master/hello-auditable/src/main.rs

Code I'm using for the static: https://github.com/Shnatsel/rust-audit/blob/master/auditable/src/lib.rs

**Comment by thomcc** [comment]
> Doesn’t seem like a bug to me.

If this is considered not a bug, would a `#[used(always)]` (or similar hammer) be viable? There are a lot of very cool use cases enabled by these sorts of things.

**Comment by nvzqz** [comment]
If we choose to go with `#[used(always)]`, I think it should be very clearly documented as to why `#[used]` doesn't always emit the symbol. I'm not a fan of making such a bandage since it's very surprising for `#[used]` to need a stronger hint.

**Comment by AsafFisher** [comment]
`#[link_section]` does not work in libraries on release mod. It does work on debug.

**Comment by ijackson** [comment]
This bug just bit me.  I have read the discussion and it is not clear to me (i) whether the lang team also think that this is a bug (ii) whether anyone has any proposed code to fix it, or just ideas?

**Comment by joshtriplett** [comment]
I personally do think it's a bug if a `pub` `#[used]` symbol doesn't appear in the final binary. (I think `#[no_mangle]` should be entirely orthogonal to this, even though today it may not be.)

**Comment by ChrisDenton** [comment]
Hmm, being passed to the linker is I think the strongest guarantee that can be made by default? I know I've sometimes relied on a symbol being passed to the linker but not appearing in the final binary.

At the very least there would need to be a way to choose between the two.

**Comment by thomcc** [comment]
> I personally do think it's a bug if a `pub` `#[used]` symbol doesn't appear in the final binary.

Worth noting that `pub` has nothing to do with it in the RFC: https://rust-lang.github.io/rfcs/2386-used.html. In general, I also think that part of the point of `#[used]` is for the non-public case.

That said, at the moment this bug definitely exists.

**Comment by Ereski** [comment]
+1 on this as it basically nukes a clean and reusable `ctor`/`dtor` solution to the problem of running a db server for tests.

**Comment by FloLo100** [comment]
Also stumbled over this bug. In our usecase the behaviour was very surprising:
We are developing a Network-server that will execute certain keywords. Available keywords are registered statically via macro using the linkme crate on the function that will execute the keyword. If a module contains only a few keywords and no other dependencies, it will be omitted in --release builds. We can currently only "fix" this by manually adding a dummy-function to every module and using it.

Because this introduces a difference in observable behaviour between release and debug builds it seems to very obviously be a bug to me. Honoring #[used] or similar would be an acceptable fix for us.

**Comment by nbdd0121** [comment]
I tested the code and it seems like:
* Regardless whether the lines are commented out, `STATIC` won't be present in the final binary (different from what the issue says)
* Regardless whether the lines are commented out, `STATIC` will be present in the object file.

It seems that the symbol is removed by GC sections.

The [RFC](https://rust-lang.github.io/rfcs/2386-used.html) of `#[used]` says:
> The `#[used]` attribute can be applied to static variables to keep them in the object files produced by rustc, even in the presence of LTO. Note that this does **not** mean that the static variable will make its way into the binary file emitted by the linker as the linker is free to drop symbols that it deems unused. In other words, the `#[used]` attribute does **not** affect the behavior of the linker.

This is also how GCC/Clang `__attribute__((used))` or G++/Clang++ `[[gnu::used]]` behave [[GCC]](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes) [[Clang]](https://clang.llvm.org/docs/AttributeReference.html#used). Therefore I conclude that `rustc` is behaving as intended and this is not a bug.

What is wanted is called `retain` in GCC/Clang. So this really is a feature request.

**Comment by inquisitivecrystal** [comment]
I'm nominating this for lang team consideration, to ensure that the current behavior is what is expected. It does sound like it matches the RFC, but some comments from lang team members suggest that it might not be what the lang team wants. If the way `#[used]` works now is fine, this can likely be closed. If the spec needs a change, perhaps this should be `C-feature-accepted` rather than `C-bug`?

**Comment by thomcc** [comment]
It's worth noting that the behavior here was made substantially worse in the [update to LLVM 13](https://github.com/rust-lang/rust/pull/87570), when we switched from the llvm.used annotation to llvm.compiler.used.

This was done to avoid a bug in older versions of the gold linker, but also effectively made `#[used]` much less useful, and arguably broke it entirely — certainly making the current issue title here "only present in output when in reachable module" an incomplete summary of the breakage (it's broken in more cases). This is frustrating, because it feels like compatibility with older versions of this linker took priority over the `#[used]` feature.

While the `#[used]` feature as written doesn't guarantee presence in the final binary, it definitely always felt like there would be a best-effort attempt to get it there, with any hedging being an acknowledgement that it's not actually possible for us to guarantee this in all (or even in many) cases.

**Comment by nbdd0121** [comment]
From comments in https://reviews.llvm.org/D97448 it sounds like before LLVM 13 there are no difference between `llvm.used` and `llvm.compiler.used` for ELF targets.

**Comment by inquisitivecrystal** [comment]
After conversing with @nbdd0121 on Zulip, it seems like there are a lot of limitations on what *can* be done here, especially given the varying features of different toolchains. It seems like it would probably be helpful to have `T-compiler` be part of the conversation as well, given that they are best positioned to understand the abilities of different toolchains. 

This is all a very long-winded way of saying that I'm nominating for T-compiler as well. Time to let the experts sort this out! I apologize if any of these nominations turn out to have been unneeded.

**Comment by trevyn** [comment]
@dtolnay I noticed you just archived the repos for [`inventory`](https://github.com/dtolnay/inventory), [`linkme`](https://github.com/dtolnay/linkme), [`gflags`](https://github.com/dtolnay/gflags), and [`typetag`](https://github.com/dtolnay/typetag), which I assume implies a deprecation. Is this issue the reason why?

**Comment by nikic** [comment]
There is https://github.com/rust-lang/rust/pull/91504 for adding a `#[used(retain)]` variant of the attribute.

**Comment by mitsuhiko** [comment]
Is there a specific reason that `#[used(retain)]` needs to exist instead of just making `#[used]` behave as if retain was set? Is there ever a reason you wouldn't want to retain it too?

**Comment by nikic** [comment]
@mitsuhiko Because both are desirable behaviors.

`#[used]` as specified just makes sure that the symbol makes it into the object file, but may still be subject to linker GC at that point. In this case, the purpose of `#[used]` is to tell the compiler that the symbol is referenced in some way that it does not see, but that *is* understood by the linker. A standard example is a use from inline assembly. Now imagine that inline assembly itself turns out to be unused, in which case the `#[used]` symbol also becomes unused, and you *want* the linker to GC it.

`#[used(retain)]` covers the case where the symbol is unused from the linker perspective as well, but you *still* want to keep it, e.g. because the section will be inspected externally. This is also a valid use-case, just a different one, and one that does not match the specified semantics of `#[used]`.

A complicating factor is that SHF_RETAIN is a very new addition to ELF, and will be either ignored by older toolchains (the lucky case) or lead to a miscompile.

As a side note, I believe that for the ctor case you mention in particular, plain `#[used]` is sufficient, because SHT_INIT_ARRAY sections should not be GCd. This counts as a reference understood by the linker.

**Comment by mitsuhiko** [comment]
It's pretty clear that at the moment sections for `linkme` as well as `ctor` are GCed. In particular the situation on my mac is that unless a function placed in `__mod_init_func` for macOS I have an example for where it gets discarded unless certain conditions are met (mainly that the function placed there is referenced by some other code in the crate).

The example where the linker somehow "knows" and understands what `#[used]` points is an interesting case but that should then not be the default at least from the perspective of Rust. I do understand though that the situation on ELF is problematic, but the core issue exists on other platforms as well.

**Comment by thomcc** [comment]
> #[used] as specified just makes sure that the symbol makes it into the object file, but may still be subject to linker GC at that point.

This is what may have been documented, but a large amount of code and a nontrivial chunk of the ecosystem (crates with several millions of downloads) has been built on this. It feels completely out of line with Rust's stability story to break that code without very careful consideration, which does not feel like it was made here.

> A standard example is a use from inline assembly. Now imagine that inline assembly itself turns out to be unused, in which case the #[used] symbol also becomes unused, and you want the linker to GC it.

This allows a small a code size optimization, which seems not very useful in practice, especially not when compared to `inventory`, `typetag`, `ctor` -- more specifically *keeping these previously working crates working*.

Also, ignoring the ecosystm the method used to build most Rust code, a `#[used]` *does* apply to the linker far more useful, and matches what the vast majority of users expect. (At a minimum, IMO we should be making a best-effort here)

---

Anyway, this actually confuses me even more now that I've looked in more. Why did the behavior on Mach-O targets happen at all? It seems to be exclusively downside with no upside:

1. Breaks compatibility with Clang and equivalence to `__attribute__((used))` (where this is guaranteed to emit a `N_NO_DEAD_STRIP` -- effectively required for many things given how aggressive `ld64 -dead_strip` is).

    (For clarity: The behavior clang has now is to emit `@llvm.compiler.used` on all targets that don't use Mach-O, and `@llvm.used` on targets that do)

2. Provides no actual benefit, as Gold only supports ELF targets (as that's presumably all it supports), and so changing to `@llvm.used` on Mach-O targets would not cause issues for it.

3. This just moves the breakage described from the old versions of Gold (failure to have static constructors get set up properly) onto the Mach-O targets (as `ctor`/`inventory became far less reliable, for the same reason).

    Assuming I'm interpreting https://reviews.llvm.org/D97448 correctly, the issue is that Gold was failing to include constructor fuctions in the correct section for them to run during initialization... It has been reported several times in various places that `ctor` and `inventory` became less reliable, which is in fact to be expected if we remove `N_NO_DEAD_STRIP`.

	In practice, perhaps this is confusion on your part. Placing the function pointer in the `__DATA,__mod_init_func` not sufficient to guarantee that it is part of the roots, unless you add flags to the section (typically `mod_init_funcs`, which yes really, is a different thing, and yes it's terrible, and I believe there's no way to apply this from `link_section`), or to the symbol (usually the N_NO_DEAD_STRIP, e.g. `__attribute__((used))`/`#[used]` flag).
	
	Sometimes the section flag is applied automatically to `__mod_init_func` sections, but it's very complex logic, and the fact that this is causing issues in the wild is unsurprising. (I'm hand-waving here becuase nobody wants to read 5 more paragraphs wrote here about how this seems to work)

4. This also renders unavailable several other interfaces on Darwin that require data be placed in specifically named sections. The documentation for these generally tells you to do this with `__attribute__((used))`, and has up until now worked with #[used].

5. Etc.

---

Finally: I don't believe it is cprrect to view the Rust reference as a set-in-stone specification such that we are free to make any changes to the implementation so long as they comply with the specification. These are extremely widely used crates, IMO so breakage should be avoided if at all possible.

Before looking through this in detail, it had been completely unclear to that Mach-O had this broken for what feels like no reason beyond that a reference document -- one which we generally have described as non-normative -- says that the behavior that works in practice is not guaranteed.

It is... very disappointing.

(*P.S. sorry if any of this came off as heated. I am a bit frustrated, but I get that we're all trying.*)

**Comment by nikic** [comment]
I should clarify that my comment above was exclusively about ELF behavior, I have no familiarity with MachO or COFF linker behavior. I think it doesn't help that this issue seems to conflate different platforms (ELF vs MachO), different use cases (ctor vs linkme) and different problems (linker GC vs potential cross-crate omission of the symbol), so it's hard to follow what any particular person is talking about.

So let me make my position here clear:
 * Both behaviors *should* be exposed, let me use the `#[used(compiler)]` and `#[used(linker)]` for them.
 * We *cannot* make `#[used(linker)]` the default on ELF, due to compatibility issues.
 * We *can* make `#[used(linker)]` the default on MachO and COFF. If this is required to make global ctors work on those platforms (ignoring cross-crate issues), then doing that seems entirely reasonable to me! We just need to document this properly as a per-platform guarantee.

In this case, `ctor` would be using `#[used]`, which gives it the necessary guarantees on all platforms (trivially on MachO/COFF, and on ELF because SHT_INIT_ARRAY is understood as a GC root by the linker) without breaking some of them (as `#[used(linker)]` would do with gold). `linkme` would use `#[used(linker)]` because it needs SHF_RETAIN to work at least LLD on ELF, because it will otherwise GC start/stop symbols.

Does that sound reasonable to you?

**Comment by Diggsey** [comment]
@nikic the bit that doesn't make sense to me is why any of the crates other than `linkme` would run into this issue unless there is a bug somewhere, since `linkme` is the only one where symbol usage is not visible to the linker, so for all the other crates `#[used(compiler)]` *should* be enough.

**Comment by thomcc** [comment]
> I should clarify that my comment above was exclusively about ELF behavior, I have no familiarity with MachO

... Oh. Sorry about that. Yes, this has... caused quite a few problems on the Apple targets 😅.

Also, I have heard reports that it caused breakage on ELF as well, and think that should be investigated. I'm going to assume from the rest of this that it doesn't (e.g. I'm assuming that prior to LLVM 13, `@llvm.used` and `@llvm.compiler.used` were compiled equivalently?).

> Does that sound reasonable to you?

The parts about making the default `#[used(linker)]` on MachO do, although I think we should do it independently of of the discussion around the broader guarantees around used. (I don't know as much about COFF, but my suspicion is that it makes sense there too).

This will just revert things (on these platforms) to how they worked prior to the LLVM 13 update, including the problem described in the older comments in this issue, since it's caused so much unintentional breakage. (I don't think we need to change the guarantees here *yet*, since we weren't guaranteeing them before).

Concretely: this is a big issue right now IMO, so I think we should do it as soon as possible to fix the breakage on these platforms, and at least consider a beta uplift for that patch if it's simple. (I could even do the work for this patch but have never touched this part of the code so I may not be the best person)

---

The rest of this is less urgent, IMO. That said, I somewhat disagree. I will continue to use the `#[used(compiler)]` and `#[used(linker)]` notation, although I think this would be quite a confusing to expose it for most users (it's very useful here, though).

My thoughts broadly:

- Having `#[used(compiler)]` be the default feels like a footgun unless it's an opt-in, realistically the way people build rust code is via combined compiler/linker invocation (that is, `cargo build`), and so `#[used(compiler)]` will have no impact.

- Having this be platform specific is also undesirable (although probably somewhat unavoidable at the extremes), especially if that decision is made because of a compatibility issue that will improve over time.

- Ideally, `#[used(linker)]` would be the default, and `#[used(compiler)]` would be an opt-in that cases which don't actually need the symbol can take advantage of. This is a change from how the feature is specified (which is a lang team call), but it brings it in line with the majority of uses, and what people assume `#[used]` means (I always assumed the notes that the linker could still remove it were just because it's hard to fully guarantee universally).

If `SHF_RETAIN` cannot be used for this (and it appears that it cannot), then this *could* be emulated by forcing the symbol to be referenced from something that *is* a GC root, like `.init_array`. I've done this before manually, but http://maskray.me/blog/2021-02-28-linker-garbage-collection has a fancy trick for it by using `R_$ARCH_NONE` relocations, which would be lower overhead on the arches supported (PPC/ARM/X86 for 32 and 64 bit as of LLVM 9, according to that blog). Elsewhere, having the compiler emit the equivalent of the manual approach would work as well.

(IMO we'd also want a `-Z` flag for controlling the use of elf retain, and eventually we'd turn it on by default, once the breakage is no longer concerning)

---

TLDR:

1. We should fix this on MachO ASAP, regardless of any broader guarantees
2. I believe theres a path forward for making `#[used]` default to `#[used(linker)]` without breaking old ELF.
3. Probably lang team's call.

**Comment by nbdd0121** [comment]
I digged deeper today to see why for the ELF target, the `KEEP` directive in the linker script couldn't prevent the linker from keeping it, and to my surprise that GC sections actually isn't the reason for its non-inclusion.

The actual reason that the item is discarded is that the CGU that contains the item isn't being referenced so the linker does not include the .o file that contains the `#[used]` item for linking at all. So the solution would be to surround the rlib file with `--whole-archive` and `--no-whole-archive`. Using `SHF_GNU_RETAIN` or the init_array hack wouldn't actually solve the issue because they won't affect how archives are searched by LD.

**Comment by thomcc** [comment]
That's somewhat of an unrelated issue that exists prior to the LLVM13 stuff. It also causes things like https://github.com/rust-lang/rust/issues/50007. I do agree that if we offer a stronger guarantee on `#[used]`, it would ideally include fixing that.

**Comment by nbdd0121** [comment]
I am aware that this isn't related to LLVM 13 changes, but I think the issues described by OP is caused by that. LLVM 13 only regresses that further for non-ELF targets.

**Comment by nagisa** [comment]
> Having #[used(compiler)] be the default feels like a footgun unless it's an opt-in, realistically the way people build rust code is via combined compiler/linker invocation (that is, cargo build), and so #[used(compiler)] will have no impact.

Having the attribute work in many cases but fail in very special other cases, even if rarely, sounds like perhaps even worse of a footgun to me. Unless we can guarantee that `#[used] = #[used(linker)]` will unconditionally work and always behave the same across targets, I feel like making things explode more readily is actually better in some ways. It forces people to notice bugs in their code, at the very least.

It seems like one option could be to tie stronger guarantees to the target tier system, but I think we ideally want to avoid this too.

---

To give some additional context: the original feature proposal for `#[used]` was always to be equivalent to `#[used(compiler)]` based on how the feature was described in its tracking issue https://github.com/rust-lang/rust/issues/40289 and the [RFC](https://github.com/rust-lang/rfcs/pull/2386).

**Comment by Ralith** [comment]
> Having the attribute work in many cases but fail in very special other cases, even if rarely, sounds like perhaps even worse of a footgun to me.

@thomcc seems to have illustrated a reasonable to work around lack of first-class target support for `#[used(linker)]. Are there cases where that can't be done?

**Comment by thomcc** [comment]
> Having the attribute work in many cases but fail in very special other cases, even if rarely, sounds like perhaps even worse of a footgun to me

Sure. This is actually why I am against it being `#[used(compiler)]`, which is *more* platform-dependent. Think of it this way: `#[used(compiler)]` means that *we're leaving the decision up to the linker*.

This will result in behavior that is both platform-dependent and unreliable. For example, `#[used(compiler)]` will work as `#[used(linker)]` if you insert into a section that that linker considers a GC root (as with on ELF). It may also work when you build your code as an executable, but not as a library -- your tests will pass, and external use will work under release build, but eventually it will stop...

Whereas `#[used(linker)]` is something that seems *much* easier to make robust and consistent across targets. There's usually a very clever target-specific way to do this in a fully-zero-cost manner, but... but in the case that there is not *we can just ensure that it's actually used*.

Which can can be done in one of many different ways[^1] -- it's basically what the programmer has to do if we don't, except they will often not be able to due to scope/visibility/not being able to come up with a mangled name that will not collide (and we can probably do it with less cost than they can).

[^1]: For example: Inserting a function that references it but does nothing in a linker GC root, if those exist (and a exported-but-mangled name if not). Several other ways as well when neither of those are viable, with various levels of annoyingness to implement.

Can we give it a 100% guarantee? It's probably bad to say "We 100% guarantee this will be in your output" since it will go through a tool we don't control. But I think we can make it very robust.  That said, for this to happen we'd also need to fix the various other issues where we decide to discard part of the code because it seems unreferenced, even though it needs to be exposed in some manner -- #50007, for example. In other words, `#[used(linker)]` has the same challenges that `#[no_mangle]`, and `#[export_name]` face (which will probably start biting people with `global_asm!` too...).

For a while now, rustc has had an issue where it's bad at keeping things around if they are for external use, but not used by Rust. This seems fixable, but might be tricky[^2]. We definitely need to fix this stuff eventually, though...

[^2]: We already have logic for whether or not a crate is used at all (which is used to decide to link in relevant native deps) -- IMO that also should decide whether or not that crate's symbols are exported, and `#[used]` items are included. That is, any use (such as `use foo_sys;` or `extern crate foo_sys;` and nothing else) is sufficient to link in `libfoo.a` (and necessary if there are no other uses despite it being in the crate graph).

---

> The original feature proposal for #[used] was always to be equivalent to #[used(compiler)] based on how the feature was described in its tracking issue https://github.com/rust-lang/rust/issues/40289 and the https://github.com/rust-lang/rfcs/pull/2386.

Yep, although I'm unsure I've ever seen it be used in a situation where this was actually okay, though. I'm sure they exist -- probably on embedded, but it's very niche. Essentially use I can remember requires that the symbol be present after linking, although sometimes it could get that without extra work from rustc, for example as with `.init_array`.

Also, the RFC also says:

> Most compilers provide a feature with the exact same semantics: usually in the form of a "used" attribute (e.g. `__attribute__((used))`) that can be applied to static variables.

Which, while probably not intended to be normative, implies you can expect uses of `__attribute__((used))` to be translated to `#[used]`. Also, the fact that they use the same name implies this as well.

**Comment by nikomatsakis** [comment]
(If lang team input is needed, please nominate, but I would very much appreciate a write-up that covers the precise proposal or question being asked, because this is a long thread and it will be hard for us to figure out what to read or not read.)

**Comment by inquisitivecrystal** [comment]
> (If lang team input is needed, please nominate, but I would very much appreciate a write-up that covers the precise proposal or question being asked, because this is a long thread and it will be hard for us to figure out what to read or not read.)

The thread has devolved into something of a mess, with a large number of questions and considerations. As the nominator, I think I'm probably responsible for producing a write-up. I'll have a go at that as soon as I can. Unfortunately, there's so much going on here that I don't understand that anything I produce is going to be a bit of a simplification, but I'll certainly try to present the core questions at issue.

**Comment by joshtriplett** [comment]
We discussed this at length in the @rust-lang/lang meeting. Based on our understanding of the issue, it sounds like there are two separate issues here:

1) The `#[used]` attribute has never guaranteed that a symbol will make it *through* the linker, and there are circumstances where it won't; we might want to either guarantee that or add a new attribute that guarantees that.
    - Complicating factors: the mechanism to make that guarantee on ELF platforms is quite new, and not fully supported, and can cause miscompilations. However, the mechanism on other platforms is supported, and for some use cases that would suffice. (In particular, constructors on ELF platforms don't need this because `.init_array` is already not GCed by the linker.)
2) There has been a regression in more recent versions of Rust, which has caused `#[used]` symbols to not even make it as far as the linker. This regression has broken several notable crates in the ecosystem, such as `ctor` and `linkme`.
    - It sounds like this may have something to do with LLVM changes, or changes in how we use LLVM, or possibly usage and handling of CGUs.

In our meeting today, we came to conclusions on these two items separately. We agreed that (2) is a bug, and should be fixed on the Rust side: `#[used]` should guarantee that a symbol gets as far as the linker. Based on our understanding of the issue, this *should* fix the regression and unbreak various crates. We'd like to see a fix for (2), and we'd be happy to review documentation improvements to `#[used]` to establish and clarify these semantics (with associated caveats and care).

Separately from that, we felt that (1) seemed worth solving as well, but that we should address that *separately* from the regression fix for (2). And for (1), we're not sure yet if we want to guarantee that `#[used]` makes it *through* the linker (especially given the current caveats about ELF support), or if we want to handle that via a separate attribute. We're hoping that (2) can get fixed as a regression fix, and that we can handle the design for (1) separately.

**Comment by joshtriplett** [comment]
Speaking for myself (without lang team hat), I'd be hesitant to adopt a design for `#[used]` that has substantially different semantics on different targets; in particular, making it mean "retain" on non-ELF platforms but not on ELF platforms seems error-prone and more difficult to work with. I'd prefer to have `#[used]` always mean one thing, and then add a different attribute for the other meaning; that may mean a crate wanting to take advantage of a special case or work around the limited ELF support for `SHF_RETAIN` may need to use `cfg`, but that seems fine.

I do think we should fix the regression though.

**Comment by mitsuhiko** [comment]
@joshtriplett it seems to me that in practice (after the regression was fixed) it will always mean different things on different platforms as not every platform’s linker will aggressively throw away unreferenced things. 

Anything involving the linker is likely to always have some platform specific stuff going on.

**Comment by Diggsey** [comment]
@mitsuhiko I think it can always be phrased in terms of "guarantees" in a platform independent way. eg. `#[used(linker)]` *guarantees* that a symbol will make it through the linker, but it's absense doesn't necessarily mean it will be thrown away either.

**Comment by nagisa** [comment]
There are use-cases in at least embedded space, where it is useful to guarantee that `#[used(compiler)]` does not force a symbol to make it through the linker. That said: this kind of guarantee probably isn't super relevant to the current T1/T2 targets; and once that sort of control is necessary, its probably a good time to look into the ways toolchain provides to customize the linker behaviour externally, anyway.

**Comment by FloLo100** [comment]
Would it be permissable to support #[used(linker)] on selected targets only? Alternatively, picking up @thomcc's ideas, every target should support symbol retention by adding a mock-function to the core module.

**Comment by thomcc** [comment]
@joshtriplett Yeah, I agree. In practice, I think the only one we have a shot at making consistent is ensuring the symbol makes it to the binary (e.g. what we've called `#[used(linker)]`).

The version that allows the symbol to be dropped (e.g. `#[used]` as specified, and what's been called `#[used(compiler)]`) leaves the behavior up to the linker, which is going to behave in a way that is platform-dependent, and frequently build configuration-dependent too.

> There are use-cases in at least embedded space, where it is useful to guarantee that `#[used(compiler)]` does not force a symbol to make it through the linker

This seems plausible and would be unfortunate. In practice it seems to usually be mostly for code size optimization. The examples in the RFC all generally cases where they don't need rustc to ask the linker to keep it, because they're going to do so with a linker script, and this seems like the common case. 

That said, these use cases are sensitive to code size, and I may be unaware of a reason it'd be a bigger problem. So perhaps would be nice to land a way to regain the `#[used(compiler)]` behavior at the same time as we stabilize a guarantee (and the code to enforce such a guarantee), if that's something we do.

**Comment by joshtriplett** [comment]
To clarify something here: the language team didn't make a decision *against* having `#[used]` mean `#[retain]`; rather, we'd like to separate the regression fix from any change to the semantics of `#[used]`.

**Comment by zseri** [comment]
@FloLo100
> Would it be permissable to support #[used(linker)] on selected targets only?

Although I certianly think that that's possible, I don't think it would be a good solution, because it would be brittle;
It might make sense (if this solution were to be chosen) that a `cfg` variable is added which would make it possible to determine if a platform is supported. I think it would be better if the compile would try hard to ensure that `#[used(linker)]` symbols are retained, even through the linker, even on unsupported platforms, maybe by means of referencing them via an auto-generated exported section/function,etc if at all possible. It's clear that it's impossible for Rust to 100% guarantee this to work (I suppose linker scripts can reliable break this if they want to), but trying to reliable implement this via work-arounds would lead to imo ugly, hard-to-maintain or brittle code.
As code used in practise often depends deeply on this to work (e.g. compile-time module/plugin systems or collecting of subcommands at compile-time or such...), it would make sense to fail compiling if it can't be supported (and any/most user-made workarounds would also fail).

**Comment by nbdd0121** [comment]
What would `#[used(linker)]` mean for staticlibs? In this case archive member selection is outside Rust's control (unlike rlibs that are used by bin/cdylib), so it seems impossible to "guarantee" a consistent `#[used(linker)]` behaviour.

**Comment by nbdd0121** [comment]
> I think there should be workarounds even for staticlibs, exploiting the fact that the `.ctors` and `.dtors` sections must already be treated specially by the linker. The compiler could auto-generate code that "uses" the symbol in question and adds it to the `.ctor` section.

This is not true. This simple gist will only produce "A" despite a ctor that prints B exists: https://gist.github.com/nbdd0121/0f0bae5f4e3e2b3b8695f51eee523f19. If an object file in an archive provides no undefined symbols then it is irrelevant and wouldn't participate in linking.

`.ctors` is no different from the `STATIC` symbol in OP's snippet: it is just a section that linker script uses `KEEP` directive. If the object file isn't being selected, then nothing can keep it around (not even SHF_RETAIN).

Plus, even if the object is indeed selected, then we still have no way to guarantee that it survives after linking. For example, if we use the ctor hack, then the symbols wouldn't survive if the target doesn't use ctors (e.g. baremetal application). SHF_RETAIN sections can still be discarded with `/DISCARD/` section, e.g. I often place `/DISCARD/ : { *.* }` at the end of my link script to throw away extra sections.

**Comment by nikic** [comment]
For the record, `#[used(compiler)]` and `#[used(linker)]` are now available behind `#![feature(used_with_arg)]`, tracked at https://github.com/rust-lang/rust/issues/93798.

**Comment by apiraino** [comment]
Issue was mentioned during T-compiler meeting [on Zulip](https://zulip-archive.rust-lang.org/stream/238009-t-compiler/meetings/topic/.5Bweekly.5D.202022-03-17.20.2354818.html#275660816)

@rustbot label -I-compiler-nominated

**Comment by carbotaniuman** [comment]
Alright I've figured it out, when implementing #94348, or rather after implementing it, and there's a lot of confounding variables that led me down several wrong paths. In short, `#[used]` does not inhibit internal linkage, which means LLVM is then free to optimize away the variable.

In a module such as this:
```
mod innter {
    #[used]
    static A: u8 = 5;
}
```
Rust currently generates LLVM IR like so:
```
@_ZN5inner6innter1A17h9c4a6d2c6b6d505cE = internal constant <{ [1 x i8] }> <{ [1 x i8] c"\05" }>, align 1, !dbg !0
@llvm.compiler.used = ......
```
The `internal constant` allows LLVM to remove the constant internally, and as such the `@llvm.compiler.used` annotation appears to have no impact. 

Currently, the workarounds are to either mark the static `#[no_mangle]`, or to make the static pub and actually use it.

All of dtolnay's links as well as Shnatsel's use case run into this bug. In this testing, I've yet to figure out where `#[used(linker)]` compared to `#[used]` actually made a difference in the final library.

https://github.com/rust-lang/rust/issues/47384#issuecomment-493690152
https://github.com/rust-lang/rust/issues/47384#issuecomment-667368981

**Comment by carbotaniuman** [comment]
If anyone read my last message, I think that's just my computer getting hit by cosmic rays/some hardware bug, because trying to reproduce the fix led to cascading failures across my Linux install, sigh, so much time wasted. Sorry for any noise.

Running everything again on my laptop now and the case where you're including a static into the final `main.rs` appears to work with `#[used(linker)]`. Everything else, such as `linkme`, `inventory` won't get solved with `#[used(linker)]` due to the linker behavior mentioned above, and it looks like it'll require proper compiler support.

**Comment by bjorn3** [comment]
Has this been fixed by https://github.com/rust-lang/rust/pull/95604?
