### ISSUE TITLE
Can't implement `From` or `Into` for custom wrapper type

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rust#49817]
This won't work:

```rust
pub struct Wrapper<T>(T);
impl<T> From<Wrapper<T>> for T {
    fn from(val: Wrapper<T>) -> T { val.0 }
}
```

and neither will:

```rust
pub struct Wrapper<T>(T);
impl<T> Into<T> for Wrapper<T> {
    fn into(self) -> T { self.0 }
}
```

In previous (post-1.0) versions of the compiler, the latter was able to be implemented, however, now it's seen as conflicting with `impl<T, U> Into<U> for T where U: From<T>`, which is definitely the correct behaviour.

But right now, not being able to implement `From` for this case seems very much to me like a bug.

**Comment by durka** [comment]
Do you happen to know which version(s)? They both fail in 1.0: https://godbolt.org/g/Cay61k

The coherence issue with implementing `From` is that a downstream crate might want to implement `From<Wrapper<TheirType>> for TheirType` and they get priority.

**Comment by clarcharr** [comment]
This should be fixed by #55437.

**Comment by leesongun** [comment]
It is still subject to the rule

2. No uncovered type parameters `P1..=Pn` may appear in `T0..Ti` (excluding `Ti`)

and both doesn't work. ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7bc601eca2b94f728b026a4555799456))

**Comment by clarfonthey** [comment]
Right, I closed it but for the wrong reason. It's still not okay with the inference rules.
