### ISSUE TITLE
Rustc does not warn about `use` with paths incompatible with `uniform_paths` for edition 2018

### ISSUE THREAD

**Issue by orium** [rust-lang/rust#53797]
Rustc does not warn about `use` with paths incompatible with `uniform_paths` for edition 2018.  This means that rustfix it will not fix your code for edition 2018.

To reproduce create the following project:

`Cargo.toml`: 
```toml
[package]
name = "foobar"
version = "0.0.0"
authors = ["Foo <example@example.com>"]

[dependencies]
criterion = "0.2"
```

`src/lib.rs`:
```rust
#![allow(unused)]
#![feature(rust_2018_preview, uniform_paths)]
extern crate criterion;
use criterion::Criterion;
```

If you run `cargo +nightly check` you will not get any warning, which means that when you run `cargo +nightly fix --edition` nothing will change, but the code is not compilable in rust 2018.  Change `Cargo.toml` to enable edition 2018 (by adding `cargo-features = ["edition"]` and `package.edition = "2018"`) and run `cargo +nightly build`:

```text
$ cargo +nightly build
[...]
error: `criterion` import is ambiguous
 --> src/lib.rs:4:5
  |
3 | extern crate criterion;
  | ----------------------- can refer to `self::criterion`
4 | use criterion::Criterion;
  |     ^^^^^^^^^ can refer to external crate `::criterion`
  |
  = help: write `::criterion` or `self::criterion` explicitly instead
  = note: relative `use` paths enabled by `#![feature(uniform_paths)]`
[...]
```

`cargo +nightly fix --edition` should have changed line 4 to `use ::criterion::Criterion`.

Ref: Bug in cargo: rust-lang/cargo#5905

**Comment by zackmdavis** [comment]
The error is emitted during name resolution:

https://github.com/rust-lang/rust/blob/ee73f80dc963707df3b3da82976556d64cac5752/src/librustc_resolve/resolve_imports.rs#L721-L733

To make this rustfix-able, we would want to reformulate the `.help` note as a [structured suggestion](https://rust-lang-nursery.github.io/rustc-guide/diag.html#suggestions) instead. (With the caveat that rustfix can't yet handle overlapping/alternative suggestions, so hopefully one of the "remove" or "`::cratename`" alternatives can be the canonical fix.)

**Comment by eddyb** [comment]
@zackmdavis That's not enough. What needs to happen is the canaries need to be injected in Rust 2015 *before* switching to Rust 2018, and that's where the correct suggestions can be generated, because we know what the user *meant* (in the working Rust 2015 code).

I've been meaning to do this ever since I realized it's actually plausible with the way the canaries are implemented, because we can inject them in more situations, and provide different diagnostics.

**Comment by nikomatsakis** [comment]
@eddyb what is the story with this one?

**Comment by eddyb** [comment]
@nikomatsakis I didn't get to it, but also I've started to doubt the idea of reusing canaries.
Maybe it'd be better to have a separate check for the name resolving in the same module, whenever the suggestions to add `crate::` are emitted?

cc @petrochenkov

**Comment by pnkfelix** [comment]
Discussed at compiler team meeting.

This seems important enough to resolve that it should remain on the RC2 milestone.

**Comment by nikomatsakis** [comment]
I just tested this locally and the most important instance (`criterion` conflicting with itself) was fixed in the meantime.

**Comment by eddyb** [comment]
The example works now, as the `extern crate` and the extern prelude entry with the same name are the same entity - we still *might* need to do some automatic migration for ambiguities involving local items, but it's lower priority I reckon.

**Comment by eddyb** [comment]
You can still reproduce this by having a local item (in the type/module namespace), with the same name, e.g. this triggers the error on the playground, on beta & nightly:
```rust
extern crate rayon;
mod foo {
    mod rayon {}
    use rayon::Scope;
}
```
I added `#![deny(rust_2018_compatibility)]` and got no errors, so `rustfix` wouldn't do anything.

**Comment by nikomatsakis** [comment]
OK, I'm going to re-open, but move to Rust 2018 Release milestone, since I think that we can probably address this with some targeted tweaks and it seems like it will not affect The Entire World.

**Comment by nikomatsakis** [comment]
BTW, there is discussion [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.2353797.20uniform.20path.20ambiguity) and in particular [starting around here](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/subject/.2353797.20uniform.20path.20ambiguity/near/136048221) we are talking about the new reproduction

**Comment by pnkfelix** [comment]
removing old nomination tag.

**Comment by pnkfelix** [comment]
visited for T-compiler triage. Marking P-high, since it is on the 2018 Release milestone.

**Comment by nikomatsakis** [comment]
@petrochenkov does your PR address this issue?

**Comment by petrochenkov** [comment]
>does your PR address this issue?

No, it doesn't.

**Comment by petrochenkov** [comment]
I haven't added any new lints on 2015 edition (which is this issue about), only uniform path reimplementation on 2018 edition.

**Comment by alexcrichton** [comment]
I've updated the OP to reflect the current status here

@nikomatsakis it sounds like on the discussion linked you had a strawman of how to fix this. Did you get a chance to test that out? Or is someone lined up to fix this perhaps in a different fashion?

**Comment by nikomatsakis** [comment]
I do think this is plausible to fix with a "quick hack". I might try to pull it off today, though I'm not sure how important it is. The original example no longer applies, and it's not clear how common the pattern described above is in real code.

**Comment by ehuss** [comment]
Another example, encountered by a user:

```rust
#![deny(rust_2018_compatibility)]
extern crate ptr;

pub mod foo {
    pub use std::ptr;
    pub use ptr::Shared;
}
```

Does not generate any errors/warnings, but fails to compile on 2018.

**Comment by nikomatsakis** [comment]
I think at this point we can close this bug -- we're not probably going to go back and make more changes here, the transition code seems to have worked "well enough". (On the other hand, we could leave it open to collect more examples that we may someday go back and fix, I suppose.)
