### ISSUE TITLE
Rust 1.31.0 fails to build using rust 1.30.1 compiled with system llvm (7.0)

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/rust#56505]
System llvm, and official rust releases not following llvm releases (rust being ahead of them) seems to be a trendy topic lately.
I have llvm 7.0.0 and rust 1.30.1 compiled with system llvm.
It can rebuilt itself just fine.
It cannot build rust 1.31.0 (configured to build with system llvm too, if that matters).

Here is the relevant part of the log, duting linking of stage0 rustc:

```
rustc-stable: /var/tmp/paludis/build/dev-lang-llvm-7.0.0/work/llvm-7.0.0.src/lib/Target/X86/X86AvoidStoreForwardingBlocks.cpp:493: void {anonymous}::X86AvoidSFBPass::buildCopies(int, llvm::MachineInstr*, int64_t, llvm::MachineInstr*, int64_t, int64_t, int64_t): Assertion `Size == 0 && "Wrong size division"' failed.
```

Compilation using official bootstrap rustc (the one downloaded by x.py) is ongoing and seems to work fine as of now.

**Comment by Keruspe** [comment]
Note that `rustc 1.31.0-beta.15 (4b3a1d911 2018-11-20)` built just fine using the same setup

**Comment by Keruspe** [comment]
Ok, so as one could expect, using the rustc 1.30.0 downloaded by x.py, I get the same failure for the stage1 rustc.

Looks like 1.31.0 is definitely broken with system llvm 7.0.0

**Comment by Keruspe** [comment]
Just saw that llvm 7.0.1 is due in a week, hopefully that'll fix stuff

**Comment by cuviper** [comment]
FWIW, I have no problem on Fedora 29 with its LLVM 7, and the only LLVM patches we have right now are build related (to cmake files and such).

One caution, there's a [known ABI incompatibility](https://bugs.llvm.org/show_bug.cgi?id=39427) between GCC and Clang in the LLVM headers.  If libLLVM.so is built with Clang while rustc's `src/rustllvm/` is built with GCC, or vice versa, then you'll have this problem.

**Comment by cuviper** [comment]
Oh, Fedora doesn't have LLVM debug assertions enabled though, and I suppose you do.

**Comment by Keruspe** [comment]
Only patches are build related here too, and both llvm and rust are built with gcc

**Comment by nikic** [comment]
Looks like https://bugs.llvm.org/show_bug.cgi?id=38743, not fixed yet.

**Comment by nikic** [comment]
The aforementioned bug has been fixed by https://github.com/llvm-mirror/llvm/commit/c3f9ab51440d34cbe3e113ae40c847f380a96845, you might want to try cherry-picking it.

**Comment by Keruspe** [comment]
Didn't try backporting that, but rustc 1.31.1 with llvm 7.0.1 still doesn't work as is.

Will try backporting the patch later

**Comment by Keruspe** [comment]
Works fine after backporting patch, thanks!
