### ISSUE TITLE
Dropped variables still included in generator type

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#57478]
```rust
struct Foo;
impl !Send for Foo {}

let _: impl Send = || {
    let guard = Foo;
    drop(guard);
    yield;
};
```

([full playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=40cf8544ae9dd8b93f9e30808e6366f6)) fails with

```
error[E0277]: `Foo` cannot be sent between threads safely
  --> src/main.rs:14:12
   |
14 |     let _: impl Send = || {
   |            ^^^^^^^^^ `Foo` cannot be sent between threads safely
   |
   = help: within `[generator@src/main.rs:14:24: 18:6 {Foo, ()}]`, the trait `std::marker::Send` is not implemented for `Foo`
   = note: required because it appears within the type `{Foo, ()}`
   = note: required because it appears within the type `[generator@src/main.rs:14:24: 18:6 {Foo, ()}]`
```

The guard should be dead and deallocated before the yield point so shouldn't appear in the generator type and affect the `Send`ness. Wrapping the guard in a new scope before the `yield` avoids this (included in the playground). First noticed [in relation to async functions on u.rl.o](https://users.rust-lang.org/t/mutexguard-cannot-be-sent-inside-future-generator/21584?u=nemo157).

**Comment by Aaron1011** [comment]
I'd like to work on this.

**Comment by Zoxc** [comment]
My plan for this is just to generate MIR for just the generator during type checking and then do the analysis on MIR. Currently that isn't very feasible given the current compiler structure.

**Comment by tmandry** [comment]
cc @rust-lang/lang, are we 100% sure we want to support this? The implication is there is going to be a "sharp edge" here when drops for certain locals move around relative to yield points (or vice versa).

It's also possible to work around it by turning your scope into a function call (possibly a closure that is immediately called).

**Comment by Nemo157** [comment]
You don't need a function call, just adding an actual scope around the variable that's dropped between yields is enough (this is included in the playground):

```rust
let _: impl Send = || {
    {
        let guard = Foo;
        drop(guard);
    }
    yield;
};
```

It makes sense to me why this is as it is and the solution could be just improved diagnostics telling users to add these extra scopes, it just seems like an unnecessary pain point for async functions.

**Comment by Nemo157** [comment]
After being reminded of this I realised this isn't really about "dropping" variables, it's about moving the variables out of the generator, any function that takes ownership should cause the variable to no longer be alive in the generator (this is the same thing since `drop` is just a trivial function to move the variable out, but being explicit about it might help others like me that didn't instantly make the connection):

```rust
struct Foo;
impl !Send for Foo {}

fn use_foo(_: Foo) {}

let _: impl Send = || {
    let guard = Foo;
    use_foo(guard);
    yield;
};
```

**Comment by oconnor663** [comment]
Another twist on the same problem might be using something like `ManuallyDrop`:

```rust
struct Foo;
impl !Send for Foo {}

let _: impl Send = || {
    let guard = ManuallyDrop::new(Foo);
    yield;
};
```

**Comment by tmandry** [comment]
Marking as AsyncAwait-OnDeck - this error can be confusing, and it may not be obvious how to work around it.

**Comment by nikomatsakis** [comment]
What exactly is the bug here? To improve error report, or to do more precise drops? If the latter, that's a tricky problem indeed, but also duplicated by other issues.

**Comment by tmandry** [comment]
The way I read the issue, it is about tracking drops more precisely. (What issues duplicate this?)

We should open a separate issue to track improving the error message.

**Comment by nikomatsakis** [comment]
@tmandry I'm not sure what issue is the "best duplicate" but I think we've been using https://github.com/rust-lang/rust/issues/57017 as a kind of stand-in for "more precise generator captures". It'd probably be good to create a generalized tracking issue that dives into the different sorts of cases, since it doesn't look like we're likely to get a generalized fix in the near-ish term.

**Comment by sug0** [comment]
Bump. Is anyone still working on this? This bug affects `async` code for obvious reasons, so I believe it should have higher priority.

**Comment by camsteffen** [comment]
> Yes, the liveness analysis I'm working on will fix this issue too.

@eholk How does this relate to #51003?

**Comment by eholk** [comment]
@camsteffen - I would say not very much. Originally I approached this issue in terms of liveness, but that ran into enough problems that I gave up on it. For example, in something like
```rust
let x = foo();
let y = &x;
use(y);
```
it's hard to realize that `y` being live implies that `x` is live too.

The solution I ended up going with works by tracking the ranges for which values are not dropped (see #91032).

I wouldn't let my work here deter you from working on #51003, and a lot of things about the liveness analysis pass will be tidier in MIR, so I'm in favor of moving the analysis there.

**Comment by xmh0511** [comment]
This issue has been fixed by https://github.com/rust-lang/rust/pull/107421/. See https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d729e04078319d7a3ba796d917fa4de2

**Comment by WaffleLapkin** [comment]
Closing as per the above comment.

**Comment by zjp-CN** [comment]
As a reminder to tell people the problem is not fully solved:
although this issue is treated as closed, the compiler still doesn't treat the dropped variables to be dead.

* https://github.com/rust-lang/rust/issues/128095#issuecomment-2248684338
* https://github.com/rust-lang/rust/issues/128095#issuecomment-2248493688
