### ISSUE TITLE
nightly regression: ambiguous import 

### ISSUE THREAD

**Issue by rukai** [rust-lang/rust#57539]
## main.rs
```rust
mod foo {
    mod simple_command {
        use simple_command;
        use crate::foo::*;
    }
}

mod bar {
}

fn main() {
}
```
## cargo.toml
```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]
edition = "2018"

[dependencies]
simple_command = "0.1"
```

On stable and `nightly-2018-12-29` the code compiles successfully.
On `nightly-2019-01-01` the code fails to compile with:
```
rubic@memes src$ cargo run
   Compiling foo v0.1.0 (/home/rubic/Foo/foo)
error[E0659]: `simple_command` is ambiguous (name vs any other name during import resolution)
 --> src/main.rs:3:13
  |
3 |         use simple_command;
  |             ^^^^^^^^^^^^^^ ambiguous name
  |
  = note: `simple_command` could refer to an extern crate passed with `--extern`
  = help: use `::simple_command` to refer to this extern crate unambiguously
note: `simple_command` could also refer to the module imported here
 --> src/main.rs:4:13
  |
4 |         use crate::foo::*;
  |             ^^^^^^^^^^^^^
  = help: use `self::simple_command` to refer to this module unambiguously

warning: unused import: `simple_command`
 --> src/main.rs:3:13
  |
3 |         use simple_command;
  |             ^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error: aborting due to previous error

For more information about this error, try `rustc --explain E0659`.
error: Could not compile `foo`.
```

At first I thought this was part of https://github.com/rust-lang/rust/issues/56316
but now I think it is different because it started happening on `nightly-2019-01-01` whereas that issue is from November.

This is currently causing ggez to fail to compile on nightly: https://github.com/ggez/ggez/pull/542

**Comment by Centril** [comment]
```rust
#![feature(uniform_paths)]

mod foo {
    mod simple_command {
        use simple_command;
        use crate::foo::*;
    }
}

mod bar {}

fn main() {}
```
With uniform paths, which will be in 1.32, this compiles, so this should resolve itself I think.

cc @petrochenkov

**Comment by petrochenkov** [comment]
So, this is indeed a regression from https://github.com/rust-lang/rust/pull/57160.

@Centril 
Looks like you missed the `[dependencies] simple_command = "0.1"` part, I'm still able to reproduce the error with uniform paths enabled.

**Comment by petrochenkov** [comment]
It's not obvious to me right away what behavior is right here, pre-#57160 or post-#57160.
I'll look in more detail.

**Comment by petrochenkov** [comment]
The ambiguity is reported correctly.
I.e. it's obvious that there's an ambiguity (the error message says what exactly), but before https://github.com/rust-lang/rust/pull/57160 the ambiguity wasn't detected due to "self-confirming" import `use simple_command` "standing in the way".
It's great that the fix got into 1.32 stable, so the time for which the issue existed on stable was minimized.

Minimized reproduction:
```rust
mod core {
    use core;
    use crate::*;
}

fn main() {}
```

**Comment by petrochenkov** [comment]
Test added in https://github.com/rust-lang/rust/pull/57551
