### ISSUE TITLE
rustup: rls cannot be downloaded for nightly

### ISSUE THREAD

**Issue by karasjoh000** [rust-lang/rust#57771]
hello everyone I wanted to update nightly rust and got this: 

```shell
[ Sat Jan 19 | 09:11 PM | forecast-service ]: rustup update && cargo update
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2019-01-20, rust version 1.33.0-nightly (0c0c58528 2019-01-19)
error: component 'rls' for target 'x86_64-apple-darwin' is unavailable for download
info: checking for self-updates

       stable-x86_64-apple-darwin unchanged - rustc 1.32.0 (9fda7c223 2019-01-16)
  nightly-x86_64-apple-darwin update failed - rustc 1.32.0-nightly (f4a421ee3 2018-12-13)

    Updating crates.io index
    Updating proc-macro2 v0.4.25 -> v0.4.26

```

update failed on nightly. 

Is nightly currently broken?

**Comment by jonhoo** [comment]
[Looks like](https://mexus.github.io/rustup-components-history/) both clippy and rls is missing from the two most recent nightlies (`2019-01-20` and `2019-01-20`). This is probably related to the build failure [seen here](https://rust-lang-nursery.github.io/rust-toolstate/). Don't know if this is related to https://github.com/rust-lang/rust/pull/57765?

**Comment by jonhoo** [comment]
Fwiw, this comment is relevant: https://github.com/rust-lang/rls/issues/641#issuecomment-446302145

**Comment by jonhoo** [comment]
Looks like clippy is fixed by https://github.com/rust-lang/rust/pull/57756. RLS was broken by https://github.com/rust-lang/rust/pull/57747, but I can't seem to find any tracking issue for fixing it?

**Comment by mati865** [comment]
RLS fix is on it's way https://github.com/rust-lang/rust/pull/57805.

**Comment by goral09** [comment]
For me it still fails:
```
rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2019-02-11, rust version 1.34.0-nightly (0b7af2668 2019-02-10)
error: component 'rls' for target 'x86_64-unknown-linux-gnu' is unavailable for download
info: checking for self-updates

       stable-x86_64-unknown-linux-gnu unchanged - rustc 1.32.0 (9fda7c223 2019-01-16)
  nightly-x86_64-unknown-linux-gnu update failed - rustc 1.33.0-nightly (ceb251214 2019-01-16)
```

Is there a deterministic way for solving this?

**Comment by mati865** [comment]
It was fixed but broke once more, it's kind of expected on nightly to break from time to time.
New fix: https://github.com/rust-lang/rust/pull/58337

If Rustup got option to update to the latest nightly with required components this would be less problematic.
Issue for this feature: https://github.com/rust-lang/rustup.rs/issues/1628

**Comment by mati865** [comment]
RLS is available, this issue can be closed.

**Comment by ThatsGobbles** [comment]
It seems that this is still happening for me on nightly?

`mark@rche:~$ rustup component add rls
error: component 'rls' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel 'nightly'`

**Comment by awestlake87** [comment]
Yeah, it's happening again. Going off of @mati865 I used the toolchain from March 21st

```bash
rustup toolchain add nightly-2019-03-21
rustup default nightly-2019-03-21
rustup component add rls
```

**Comment by leeola** [comment]
Still like that it seems. Is there a good way to see what dates rls (or any component) are working? Anther thread suggested https://rust-lang.github.io/rustup-components-history/x86_64-apple-darwin.html - but that only goes back 8 days and as of today RLS isn't working on _any_ of those days haha.

I'm not sure what nightlies have RLS.

**Comment by mati865** [comment]
@leeola recent changes broke `compiletest-rs` which broke Clippy which in turn broke RLS.

**Comment by dessalines** [comment]
It might be good to list which is the most recently working nightly on the readme here.

**Comment by CraZySacX** [comment]
Rust Toolstate shows current status:  https://rust-lang-nursery.github.io/rust-toolstate/

**Comment by Xanewok** [comment]
Unfortunately this is on and off and the current state can be checked at the link above. To reduce the turnaround it'd be good to decouple RLS from Clippy at some point (#59761).

**Comment by hecool108** [comment]
My solution is:
1 check the last available nightly version contains  'rls'
2 `rustup toolchain add nightly-2020-05-15` it's 2020-05-15 in my case.
3 `rustup default nightly-2020-05-15` this very important step, can't make it work if you skip this.
4 `rustup component add rls`

After this, rls had been installed on my mac.

If you're like me using vs code rust extension, press shift+cmd+p, run "Rust : start the rust server".
After you see the green triangle on the bottom of vs code, your code completion and hover-docs should work like a pony.
