### ISSUE TITLE
Unable to resolve breakpoints when debugging a unit test in a lib target

### ISSUE THREAD

**Issue by mchernyavsky** [rust-lang/rust#59907]
## Environment

* **Operating system:** macOS Mojave 10.14.4
* **Rust toolchain:** nightly-x86_64-apple-darwin
* **Rustc version:** 1.35.0-nightly (96d700f1b 2019-04-10)

## Problem description

On macOS, when you build tests (with `cargo test --no-run`) in a lib target, and right after that run LLDB on the test binary, the debugger unable to resolve breakpoints.

### Example project:
* `Cargo.toml`:
```toml
[package]
name = "sandbox"
version = "0.1.0"
edition = "2018"
```
* `src/main.rs`:
```rust
fn main() {}

#[test]
fn test() { assert_eq!(2 + 2, 5) }
```
* `src/lib.rs`:
```rust
#[test]
fn test() { assert_eq!(2 + 2, 4) }
```
### Test script (bash):
* `test.sh`:
```bash
#!/usr/bin/env bash
rm -rf target
EXE="$(cargo test --no-run --message-format=json --lib test 2>/dev/null | jq -r '.executable')"
sleep "$1"
lldb "$EXE" <<< "b test"
```

* Delay 1 second before running the LLDB:
```bash
> ./test.sh 1
(lldb) target create "/Users/mikhail.chernyavsky/Workspace/rust-sandbox/target/debug/sandbox-5d25a79faaa6e465"
Current executable set to '/Users/mikhail.chernyavsky/Workspace/rust-sandbox/target/debug/sandbox-5d25a79faaa6e465' (x86_64).
(lldb) b test
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
```

* Delay 2 seconds before running the LLDB:
```bash
> ./test.sh 2
(lldb) target create "/Users/mikhail.chernyavsky/Workspace/rust-sandbox/target/debug/sandbox-5d25a79faaa6e465"
Current executable set to '/Users/mikhail.chernyavsky/Workspace/rust-sandbox/target/debug/sandbox-5d25a79faaa6e465' (x86_64).
(lldb) b test
Breakpoint 1: where = sandbox-5d25a79faaa6e465`sandbox::test::h95a153b117ba44e2 + 11 at lib.rs:2:23, address = 0x00000001000017bb
```

## P.S.
I also noticed that the `*.dSYM` file is not listed in the `filenames` field:
```bash
> cargo test --no-run --message-format=json --lib test 2>/dev/null | jq -r '.filenames'
[
  "/Users/mikhail.chernyavsky/Workspace/rust-sandbox/target/debug/sandbox-5d25a79faaa6e465"
]
```

For example, build unit tests in bin target:
```bash
> cargo test --no-run --message-format=json --bin sandbox 2>/dev/null | jq -r '.filenames'
[
  "/Users/mikhail.chernyavsky/Workspace/rust-sandbox/target/debug/deps/libsandbox-006b5c7138cbbb04.rlib"
]
[
  "/Users/mikhail.chernyavsky/Workspace/rust-sandbox/target/debug/sandbox-94b9126e8bd84c57",
  "/Users/mikhail.chernyavsky/Workspace/rust-sandbox/target/debug/sandbox-94b9126e8bd84c57.dSYM"
]
```

**Comment by stepan-romankov** [comment]
Any plans for this? Still doesn't work in 1.39

**Comment by jiegec** [comment]
I think this issue should be moved to cargo. This is how dSYM uplifting works for binaries: 

https://github.com/rust-lang/cargo/blob/e618d47a1765ca18d1601d4cf891a55a34d23aed/src/cargo/core/compiler/build_context/target_info.rs#L260-L269

**Comment by kwhrtsk** [comment]
I tried to make a simple workaround to avoid this problem with VSCode (CodeLLDB).

https://github.com/kwhrtsk/rust-lldb-workaround

Any other workarounds?

**Comment by jiegec** [comment]
This should be fixed by rust-lang/cargo#7965

**Comment by tamerh** [comment]
After upgrading the Rust seems I am still having this problem
