### ISSUE TITLE
rustc endless loop on some constant casts

### ISSUE THREAD

**Issue by antifuchs** [rust-lang/rust#67539]
I bisected nightlies to figure out when my [pull request's tests](https://github.com/antifuchs/nonzero_ext/pull/7) started breaking on nightly. The following is the template `cargo-bisect-rustc` gave me.

# Regression found in the compiler

searched nightlies: from nightly-2019-10-01 to nightly-2019-12-22
regressed nightly: nightly-2019-11-20
searched commits: from https://github.com/rust-lang/rust/commit/3e525e3f6d9e85d54fa4c49b52df85aa0c990100 to https://github.com/rust-lang/rust/commit/618b01f9fa0a6b4e7e2ce5b3409abe104b80c4a8
regressed commit: https://github.com/rust-lang/rust/commit/d1da8023dafd3e277b5a4c5475aa2cb199a176b9
source code: https://github.com/antifuchs/nonzero_ext/pull/7

## Instructions

I tried the following on macOS and linux (in CI):

1. Check out the repo & branch of that pull request
2. Run `cargo +nightly test --test=compiletest` with a nightly version later than d1da8023dafd3e277b5a4c5475aa2cb199a176b9, that is >= `nightly-2019-11-20`

## Error

The compile test (provided by trybuild) does not terminate - rustc seems to be running forever, consuming 99% of my CPU all the while.

Since the instructions to repro are a bit convoluted (and massive), I'll try and boil down the repro case a little bit.

**Comment by antifuchs** [comment]
Here's a playground link that better illustrates the failure. It builds with `stable`, but loops endlessly on `nightly`: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=eb03f3a6297979be89be032bbb558d38

**Comment by antifuchs** [comment]
(Never mind that the code is wrong: casting a negative number to `usize` is pretty messed up and seems to work only by chance; however, having the compiler endless-loop is suboptimal) (:

**Comment by antifuchs** [comment]
Reduced further to https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1ca768b40e5cb223899e540c4c5dab4a (:

**Comment by oli-obk** [comment]
similar "endless" loop: https://github.com/rust-lang/rust/issues/63952

The problem here is that you have an overflow essentially giving you `let _ = [(); usize::max_value()];`, which... const prop will then try to turn into a constant

cc @wesleywiser

**Comment by oli-obk** [comment]
for arrays of zsts we can solve this, but if you used `u8` we'd actually need to allocate and do some operations. Maybe we should make mir building for repeat expressions not have its own [`Rvalue` variant](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/mir/enum.Rvalue.html#variant.Repeat) but instead just convert `[X; N]` to MIR of the following form

```rust
let mut x = MaybeUninit::<[T; N]>::uninit();
for i in &mut x {
    *x = X;
}
let x = x.assert_initialized();
```

**Comment by wesleywiser** [comment]
I thought this might have been fixed by #66394, but because it's a ZST, it doesn't trigger that logic. It would probably be easy to extend that logic to include large arrays of ZSTs.

**Comment by oli-obk** [comment]
While we could fix this just for const prop, we'd still have the same problem in const eval, so we should consider a general solution.

**Comment by RalfJung** [comment]
> Maybe we should make mir building for repeat expressions not have its own Rvalue variant but instead just convert [X; N] to MIR of the following form

That would solve tons of problems I think. Having a single MIR statement turn into a loop in the interpreter is pretty suboptimal anyway -- usually every statement should have a fixed upper bound on its execution time.

As an interim solution we could probably [skip this part](https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/librustc_mir/interpret/step.rs#L208) for arrays of ZST.

**Comment by RalfJung** [comment]
Or probably it makes more sense to [skip this loop](https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/librustc_mir/interpret/memory.rs#L865) if the size is 0.

**Comment by oli-obk** [comment]
Or we just make the first line of https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/librustc_mir/interpret/memory.rs#L825-L832 be `if size == Size::ZERO || length == 0 { return Ok(()) }`

That way we can even remove https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/librustc_mir/interpret/step.rs#L208

**Comment by RalfJung** [comment]
> Or we just make the first line of 

No, we have to still check those pointers to not be dangling.

**Comment by oli-obk** [comment]
I thought writes of zsts to dangling pointers is fine?

Though yea, I'm unsure about writing zero elements of non-zsts to a destination.

**Comment by RalfJung** [comment]
Oh wait, looks like we expect the caller to check that. Hm.

I'd probably bail out after getting `src_bytes` and `dest_bytes`, if `dest_bytes.is_empty()` or so.

**Comment by RalfJung** [comment]
> I thought writes of zsts to dangling pointers is fine?

Not always, no. If the pointer is a `Pointer` (not an integer), but dangling, it's UB even with ZST. Also see [this test](https://github.com/rust-lang/miri/blob/a3ea1cb4581970396635fce82182555003083b62/tests/compile-fail/dangling_zst_deref.rs).

**Comment by oli-obk** [comment]
Ok, so to any implementor: basically bail out from just before https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/librustc_mir/interpret/memory.rs#L849 if `dest_bytes.is_empty()` and leave a comment explaining that this is an optimization to not run anything for zsts. You can reference this issue, too.

**Comment by wesleywiser** [comment]
It looks to me like the compiler is busy validating every `()` in the array. Bailing out if `dest_bytes.is_empty()` doesn't seem to make any difference at all. However, if I add a case for

```rust
ty::Tuple(t) if t.len() == 0 => true
```

to this match

https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/librustc_mir/interpret/validity.rs#L587

then the compilation completes  in ~0.2 seconds. I'm not sure that's a valid fix though. Do we actually need to validate every ZST in the array?

**Comment by RalfJung** [comment]
Well, the ZST could be `!` or an empty enum, so we certainly can't skip all ZST.

**Comment by wesleywiser** [comment]
Ah, yeah that's a great point. I believe `ty::Tuple(t) if t.len() == 0` will only match the unit type. Perhaps it's worth including a special case for that?

**Comment by oli-obk** [comment]
Well... any zst that is not uninhabited can do this early bail out, so I think checking with https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TyCtxt.html#method.is_ty_uninhabited_from_any_module for uninhabitedness and then checking the element's zst-ness would work

**Comment by RalfJung** [comment]
I wouldn't use `!uninhabited` as a witness for things to be inhabited... this requires that there is no conservatism at all in the uninhabitedness check. (Also I have no idea what that function does.^^ The implementation talks about... forests?!?)

**Comment by antifuchs** [comment]
Huh, so. From the behavior I reported in https://github.com/bheisler/criterion.rs/issues/377, it looks like the buggy change made it to 1.41.0 stable, but the fix didn't? My crate's benchmark compilation is currently hanging with what looks like these exact symptoms.
