### ISSUE TITLE
`std::iter::Skip::count` can overflow even if the iterator would return less that `usize::max_value()` items

### ISSUE THREAD

**Issue by ollie27** [rust-lang/rust#68139]
`std::iter::Skip::count` currently calls `count` on the inner iterator but that can overflow even if the `Skip` itself doesn't return more that `usize::max_value()` items.

For example:

```rust
(0..usize::max_value()).chain(0..10).skip(usize::max_value()).count()
```

This should return `10` but currently triggers an `attempt to add with overflow` (or returns `0` if overflow checks are disabled).

This is caused by https://github.com/rust-lang/rust/blob/1389494ac145a84dba025ff65969f7ab150c3f02/src/libcore/iter/adapters/mod.rs#L1817-L1820 which was added in #25035 which was merged between versions 1.0 and 1.1.

**Comment by clarfon** [comment]
This could probably be fixed by calling `self.iter.nth(self.n)` and then relying on `self.iter.count()` as usual.

**Comment by JohnTitor** [comment]
@clarfon I think it doesn't fix because `nth(usize::max_value() - 1)` is very slow, right?

**Comment by clarfon** [comment]
Should be overridden for ranges though.
