### ISSUE TITLE
llvm-tools component no longer works on master

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#73602]
`rustup-toolchain-install-master -n master -f -c rustc-dev -c llvm-tools` fails with

```
error: found no file in folder `llvm-tools-nightly-x86_64-unknown-linux-gnu/llvm-tools` when extracting component `llvm-tools`
```

The folder name is actually `llvm-tools-preview`. `-c llvm-tools-preview` does not exist.

This makes it impossible to e.g. build clippy out of tree

This seems to be related to https://github.com/rust-lang/rust/pull/72000 , but RTIM definitely worked back then, so something else has changed.

cc @Mark-Simulacrum @cuviper

**Comment by Mark-Simulacrum** [comment]
Hm maybe this was fixed since then? It seems to be working for me as of today.

```
$ rustup-toolchain-install-master -n master -f -c rustc-dev -c llvm-tools
fetching master commit hash...
detecting the channel of the `d8ed1b03c202d77248eb0d335062f46026fc29c4` toolchain...
downloading <https://rust-lang-ci2.s3-us-west-1.amazonaws.com/rustc-builds/d8ed1b03c202d77248eb0d335062f46026fc29c4/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz>...
47.34 MB / 47.34 MB [=========================================================================================================================================================================] 100.00 % 12.49 MB/s
downloading <https://rust-lang-ci2.s3-us-west-1.amazonaws.com/rustc-builds/d8ed1b03c202d77248eb0d335062f46026fc29c4/rustc-dev-nightly-x86_64-unknown-linux-gnu.tar.xz>...
71.31 MB / 71.31 MB [=========================================================================================================================================================================] 100.00 % 12.19 MB/s
downloading <https://rust-lang-ci2.s3-us-west-1.amazonaws.com/rustc-builds/d8ed1b03c202d77248eb0d335062f46026fc29c4/llvm-tools-nightly-x86_64-unknown-linux-gnu.tar.xz>...
18.84 MB / 18.84 MB [=========================================================================================================================================================================] 100.00 % 12.11 MB/s
downloading <https://rust-lang-ci2.s3-us-west-1.amazonaws.com/rustc-builds/d8ed1b03c202d77248eb0d335062f46026fc29c4/rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz>...
15.95 MB / 15.95 MB [=========================================================================================================================================================================] 100.00 % 14.27 MB/s
toolchain `master` is successfully installed!
```

**Comment by Manishearth** [comment]
Possibly!

**Comment by Manishearth** [comment]
hmm, i was still getting the same error, but it went away after I updated RTIM
