### ISSUE TITLE
E0121 suggests the use of the unique type of a returned function/closure rather than a fn pointer or a Fn trait

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-lang/rust#80179]
I tried this code:

```rust
fn f() -> i32 {
    0
}

fn returns_fn_pointer() -> _ {
    f
}
```

The resulting diagnostic suggests replacing `_` with `fn() -> i32 {f}`, the unique type of `f()`:

```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> src/lib.rs:5:28
  |
5 | fn returns_fn_pointer() -> _ {
  |                            ^
  |                            |
  |                            not allowed in type signatures
  |                            help: replace with the correct return type: `fn() -> i32 {f}`
```

This, of course, doesn't work:
```
error: expected item, found `{`
 --> src/lib.rs:5:44
  |
5 | fn returns_fn_pointer() -> fn() -> i32 {f} {
  |                                            ^ expected item

```

I'd expect the diagnostic to suggest replacing `_` with `fn() -> i32` or `impl Fn() -> i32`, both of which compile successfully.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (2225ee1b6 2020-12-11)
binary: rustc
commit-hash: 2225ee1b62ff089917434aefd9b2bf509cfa087f
commit-date: 2020-12-11
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

**Comment by PatchMixolydic** [comment]
This also seems to happen with closures:
```rust
fn returns_closure() -> _ {
    || 5
}
```

```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> src/lib.rs:1:25
  |
1 | fn returns_closure() -> _ {
  |                         ^
  |                         |
  |                         not allowed in type signatures
  |                         help: replace with the correct return type: `[closure@src/lib.rs:2:5: 2:9]`
```

**Comment by ThePuzzlemaker** [comment]
Function pointers are now working, but it looks like closures will be a bit harder of a task.
```rust
fn f() -> i32 { 0 }
fn g() -> _ { f } 
```
```rust
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> <anon>:2:11
  |
2 | fn g() -> _ { f }
  |           ^
  |           |
  |           not allowed in type signatures
  |           help: replace with the correct return type: `fn() -> i32`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0121`.
```

**Comment by ThePuzzlemaker** [comment]
This brings up some questions though, unfortunately. For example, this code has the same type of issue:
```rust
fn f() -> i32 { 0 }
fn g() -> () { f }
```
This code brings up this diagnostic:
```rust
error[E0308]: mismatched types
 --> <anon>:2:16
  |
2 | fn g() -> () { f }
  |           --   ^ expected `()`, found fn item
  |           |
  |           expected `()` because of return type
  |
  = note: expected unit type `()`
               found fn item `fn() -> i32 {f}`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
 ```
And to be honest, these diagnostics aren't entirely incorrect—that *is* the return type, it's just not valid syntax. Using a function pointer would be taking that unique type and coercing it into a function pointer or non-unique closure type.

Arguably, it should have something like `` help: this looks like a fn item, try using a function pointer: `fn() -> i32` ``, but doing this would end up meaning changing a lot of typeck code. I'm not really sure how to go through with this considering these things (as I'm not really too experienced with rustc code and therefore might mess up a bit of things).

**Comment by PatchMixolydic** [comment]
For errors like E0308, it would make sense to state the actual type since that is the root cause of the issue (functions cannot be coerced to `()`). E0121, however, suggests replacing `_` with the type it gives you, which falls apart in the face of these unnameable types. This can be a papercut to people who don't know how to return a function pointer/closure and become confused when the suggestion fails to compile.

This is probably problematic, since changing the `Display` impl of types (it seems like that's what's being used per [`rustc_typeck::collect::fn_sig`]) would likely mess up E0308 and other similar diagnostics.

[`rustc_typeck::collect::fn_sig`]: https://github.com/rust-lang/rust/blob/b1964e60b72c2d10e9fd4e801990f8af3f306ac0/compiler/rustc_typeck/src/collect.rs#L1546

I haven't looked into the underlying issue personally, but I can see a few options:

* Don't emit a suggestion for closures or functions. This is the simplest solution and would preserve the other typecheck-related diagnostics, but may be unhelpful to those who rely on E0121 as a simulacrum of [typed holes].
* Add [the fix to suggest using a fn pointer](https://github.com/rust-lang/rust/issues/80179#issuecomment-748757322) if the returned value is a function, but don't emit a suggestion for closures. I'm not sure of the depth of changes necessary for just this, and again, I'm not sure if this meshes well with other diagnostics. Notably, this does at least sidestep the likely complex issue of trying to determine which Fn trait to suggest.
* Emit a different suggestion for closures and possibly functions along the lines of `consider using a Fn, FnOnce, or FnMut trait bound. For more information on Fn traits, see...`.

[typed holes]: https://downloads.haskell.org/~ghc/7.10.1/docs/html/users_guide/typed-holes.html

**Comment by ThePuzzlemaker** [comment]
I think that I'll probably do this I guess:
- If it's a function, suggest a function pointer, but also add that suggestion about a Fn/FnOnce/FnMut trait bound
- If it's a closure, suggest a Fn/FnOnce/FnMut trait bound as well

**Comment by ThePuzzlemaker** [comment]
Should I link to the [Rust by Example on closure output types](https://doc.rust-lang.org/nightly/rust-by-example/fn/closures/output_parameters.html) or maybe the [`std` documentation for `Fn`](https://doc.rust-lang.org/nightly/std/ops/trait.Fn.html)?

**Comment by PatchMixolydic** [comment]
Rust by Example or [The Book](https://doc.rust-lang.org/book/ch13-01-closures.html#storing-closures-using-generic-parameters-and-the-fn-traits) would probably be preferable since they explain Fn, FnMut, and FnOnce in one place, but I'm not certain if there's any precedent or policy about linking to them in diagnostics.

**Comment by ThePuzzlemaker** [comment]
Alright. Does this look good?
Function definition:
```rust
fn f() -> i32 { 0 }
fn g() -> _ { f }
```
```rust
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> <anon>:2:11
  |
2 | fn g() -> _ { f }
  |           ^
  |           |
  |           not allowed in type signatures
  |           help: replace with the correct return type: `fn() -> i32`
  |
  = help: also consider using a `Fn`, `FnMut`, or `FnOnce` trait bound
  = note: For more information on using `Fn` traits with function outputs, see https://doc.rust-lang.org/rust-by-example/fn/closures/output_parameters.html

error: aborting due to previous error

For more information about this error, try `rustc --explain E0121`.
```
I'll get closures in a bit, cause my rustc dev build decided to die on me and I have to completely rebuild it :slightly_frowning_face:

**Comment by PatchMixolydic** [comment]
👍 Looks good to me, but I'd like to emphasize that I'm not ready a contributor, so take this with a grain of salt.

**Comment by ThePuzzlemaker** [comment]
Closures:
```rust
fn f() -> _ { || 0 }
```
```rust
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> <anon>:1:11
  |
1 | fn f() -> _ { || 0 }
  |           ^ not allowed in type signatures
  |
  = help: consider using an `Fn`, `FnMut`, or `FnOnce` trait bound
  = note: For more information on using `Fn` traits with function outputs, see https://doc.rust-lang.org/rust-by-example/fn/closures/output_parameters.html

error: aborting due to previous error

For more information about this error, try `rustc --explain E0121`.
```

**Comment by ThePuzzlemaker** [comment]
I think I'm going to remove the `Fn`(`Mut`/`Once`) from function definitions as it's kind of not strictly necessary as it's a return type, not an input param

**Comment by PatchMixolydic** [comment]
Thank you so much for all of your hard work!

Just a nitpick: [it seems like the note should start with a lowercase letter](https://rustc-dev-guide.rust-lang.org/diagnostics.html#diagnostic-output-style-guide).

**Comment by ThePuzzlemaker** [comment]
Yeah, camelid noted that in a Zulip thread related to this so I fixed that.

**Comment by PatchMixolydic** [comment]
This still fails on generators ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7ac611ca1bd560116d4b9a804817ad20)):

```rust
#![feature(generators)]

fn foo() -> _ {
    || yield i32
}
```

```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> src/lib.rs:3:13
  |
3 | fn foo() -> _ {
  |             ^
  |             |
  |             not allowed in type signatures
  |             help: replace with the correct return type: [generator@src/lib.rs:4:5: 4:18 {i32, ()}]
```

I'm working on a PR to fix this as well as making this suggestion and E0308's `try adding a return type` suggestion use the same mechanism for checking if a type is suggestable directly.

@rustbot claim

**Comment by PatchMixolydic** [comment]
Moving this to #80844

@rustbot release-assignment
