### ISSUE TITLE
rustdoc: Add [src] links for type aliases

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#81311]
Type aliases don't seem to have [src] links currently; see for example [`rustc_data_structures::fx::FxHashMap`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/fx/type.FxHashMap.html):

![image](https://user-images.githubusercontent.com/37223377/105615048-58178480-5d82-11eb-9950-ae291caedee0.png)

**Comment by jyn514** [comment]
I looked around in the source a bit - this should have been generated around https://github.com/rust-lang/rust/blob/72c7b7026742766998655eba95fca984046c0288/src/librustdoc/html/render/mod.rs#L1741, so I expect the issue is that https://github.com/rust-lang/rust/blob/72c7b7026742766998655eba95fca984046c0288/src/librustdoc/html/render/mod.rs#L1650 is returning `None` for some reason.

**Comment by LeSeulArtichaut** [comment]
Rustdoc successfully generates an `[src]` link for `Bar`:
```rust
pub struct Foo;
pub type Bar = Foo;
```

**Comment by LeSeulArtichaut** [comment]
`rustc_data_structures::fx::FxHashMap` probably doesn't work because it's a reexport from `rustc_hash` which is not documented in the published nightly-rustc docs.

By contrast, [`FxIndexMap`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/fx/type.FxIndexMap.html), which is defined directly in `rustc_data_structures`, has a `[src]` link.

**Comment by LeSeulArtichaut** [comment]
The following does reproduce the bug:

#### a/lib.rs
```rust
pub struct Foo;
pub type Bar = Foo;
```

#### b/lib.rs
```rust
pub use a::{Foo, Bar};
```

Here, both `Foo` and`Bar` will appear without an `[src]` link, so this is not an issue with type aliases but with the way external sources are handled.

What could be done instead is having an `[src]` pointing at the re-export instead of having no link, unsure if that sounds good, @camelid what do you think?

**Comment by jyn514** [comment]
Hmm, maybe rustdoc should fall back to showing the re-export if the original definition isn't available.

**Comment by camelid** [comment]
> The following does reproduce this issue:
> 
> 
> 
> #### a/lib.rs
> 
> ```rust
> 
> pub struct Foo;
> 
> pub type Bar = Foo;
> 
> ```
> 
> 
> 
> #### b/lib.rs
> 
> ```rust
> 
> pub use a::{Foo, Bar};
> 
> ```
> 
> 
> 
> Here, both `Foo` and`Bar` will appear without an `[src]` link, so this is not an issue with type aliases but with the way external sources are handled.
> 
> 
> 
> What could be done instead is having an `[src]` pointing at the re-export instead of having no link, unsure if that sounds good, @camelid what do you think?

Yeah, that seems good.

**Comment by camelid** [comment]
> Here, both `Foo` and`Bar` will appear without an `[src]` link, so this is not an issue with type aliases but with the way external sources are handled.

Hmm, I'm not sure if this is right. [`rustc_hir::def_id::CrateNum`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/def_id/enum.CrateNum.html) has a `[src]` link, but that's a re-export of [`rustc_span::def_id::CrateNum`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/def_id/enum.CrateNum.html). The `[src]` link of the re-export points to the source of the dependency.

I'm not sure why it's working in this case but not your repro...

**Comment by LeSeulArtichaut** [comment]
> Hmm, I'm not sure if this is right. [`rustc_hir::def_id::CrateNum`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/def_id/enum.CrateNum.html) has a `[src]` link, but that's a re-export of [`rustc_span::def_id::CrateNum`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/def_id/enum.CrateNum.html). The `[src]` link of the re-export points to the source of the dependency.

The difference is that here, `rustc_span` is documented. In my example, you need to document `b` with `--no-deps` to reproduce the issue.

**Comment by camelid** [comment]
Ah, I see what you mean 👍

**Comment by jyn514** [comment]
If https://github.com/rust-lang/rust/issues/41903 is implemented, it should also fix this issue.

**Comment by camelid** [comment]
It looks like that issue has been closed as intended behavior?

**Comment by jyn514** [comment]
Yup, I commented here before it had been closed.

**Comment by lolgeny** [comment]
I'll try doing this
@rustbot claim

**Comment by vramana** [comment]
![image](https://user-images.githubusercontent.com/3112509/160231568-f169bf20-6838-40b1-8f18-ac025b13a33e.png)


https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/fx/type.FxHashMap.html

Seems like this issue is solved.

**Comment by jyn514** [comment]
It looks like at some point bootstrap started passing `-Zrustdoc-map` to cargo, so rustdoc now knows where `rustc_hash` is and can link to it. The original issue is not solved though, that re-exports of undocumented items will not have a `source` link generated. Here's an MCVE:
```rust
// inner crate
pub type DMatrix = Vec<u32>;

// outer crate
pub use inner::DMatrix;
```
![image](https://user-images.githubusercontent.com/23638587/160249934-0c880b10-a01e-4c3e-809b-fa352bfd8222.png)

**Comment by vramana** [comment]
@jyn514 Can I work on this issue?

**Comment by jyn514** [comment]
Sure :) use `@rustbot claim` so other people know you're working on it.

**Comment by vramana** [comment]
The problem appears to be with generate href for the undocumented item in `href_from_span` (context.rs)
  We recieve krate variable as ExternalLocation::Unkown.
  
https://github.com/rust-lang/rust/blob/8834629b861cd182be6b914d4e6bc5958160debc/src/librustdoc/html/render/context.rs#L327-L338

This in turn is caused may be incorrect Cache population. `populate` (cache.rs)
  
https://github.com/rust-lang/rust/blob/8834629b861cd182be6b914d4e6bc5958160debc/src/librustdoc/formats/cache.rs#L154-L161

When cache is populated, the crate location (ExternalLocation) is set as Unknown. For crates linked via workspace, they are classified as local by checking crate name exists in destination path. For other external crates, we deduce it from tcx.
  
https://github.com/rust-lang/rust/blob/8834629b861cd182be6b914d4e6bc5958160debc/src/librustdoc/clean/types.rs#L213-L221

But `tcx.get_atts(did)` is an empty array when crate is hosted on directly on github.  Apparently this is expected according to @jyn514 
  
We probably need to modify `href_from_span`(context.rs) to handle the `ExternalLocation::Unkown` case. I don't know have any ideas on how to fix this. I'll unassign myself from this issue. 

My test repo to reproduce the issue https://github.com/vramana/test-rustdoc-link
