### ISSUE TITLE
incremental ICE: slice-pattern-const.rs

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#83085]
### Code
code is reduced from `./src/test/ui/pattern/usefulness/slice-pattern-const.rs`
```Rust
fn main() {
    const BOO: &[u8; 0] = &[];
    match &[] {
        BOO => (),
        b"" => (),
        _ => (), 
    }
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (b3e19a221 2021-03-12)
binary: rustc
commit-hash: b3e19a221e63dcffdef87e12eadf1f36a8b90295
commit-date: 2021-03-12
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 12.0.0
```

### Error output
`rustc  ./src/test/ui/pattern/usefulness/slice-pattern-const.rs  -Cincremental=/tmp/a  -Zincremental-verify-ich=yes `
```
thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing }, value: Const { ty: &[u8; 0], val: Value(Scalar(alloc4)) } }
- dep-node: deref_const(425d79d9606e812c-e24fed75a464eb8f)', /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/compiler/rustc_query_system/src/query/plumbing.rs:605:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (b3e19a221 2021-03-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z incremental-verify-ich=yes -C incremental

query stack during panic:
#0 [check_match] match-checking `main`
#1 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing }, value: Const { ty: &[u8; 0], val: Value(Scalar(alloc4)) } }
- dep-node: deref_const(425d79d9606e812c-e24fed75a464eb8f)', /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/compiler/rustc_query_system/src/query/plumbing.rs:605:5
stack backtrace:
   0:     0x7f125f2a5930 - std::backtrace_rs::backtrace::libunwind::trace::hfe3b1cace85e87d8
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f125f2a5930 - std::backtrace_rs::backtrace::trace_unsynchronized::h542330af06479043
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f125f2a5930 - std::sys_common::backtrace::_print_fmt::h6b88726367858985
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f125f2a5930 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcd76ce6b485adbea
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f125f313b6f - core::fmt::write::h127419eb46f2ecc9
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/core/src/fmt/mod.rs:1092:17
   5:     0x7f125f299a42 - std::io::Write::write_fmt::h0facb64ef2e7f5d8
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/io/mod.rs:1567:15
   6:     0x7f125f2a9675 - std::sys_common::backtrace::_print::h7bf1633ea5421f7b
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f125f2a9675 - std::sys_common::backtrace::print::h5cc4d09049928ba5
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f125f2a9675 - std::panicking::default_hook::{{closure}}::h9e84dc005bfc9fc7
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/panicking.rs:208:50
   9:     0x7f125f2a91d3 - std::panicking::default_hook::h123278a03b1f796b
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/panicking.rs:225:9
  10:     0x7f125fa92d4b - rustc_driver::report_ice::h036d06dbb7c2c24c
  11:     0x7f125f2a9de0 - std::panicking::rust_panic_with_hook::h4040631aa6c7bc27
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/panicking.rs:595:17
  12:     0x7f125f2a9957 - std::panicking::begin_panic_handler::{{closure}}::h02a17b22ac092d08
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/panicking.rs:497:13
  13:     0x7f125f2a5dec - std::sys_common::backtrace::__rust_end_short_backtrace::h6063b024443b5852
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7f125f2a98b9 - rust_begin_unwind
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/panicking.rs:493:5
  15:     0x7f125f26e03b - std::panicking::begin_panic_fmt::h10b51f96d6207ff1
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/panicking.rs:435:5
  16:     0x7f1261c47da8 - rustc_query_system::query::plumbing::force_query_with_job::he0f620158da8d803
  17:     0x7f1261beb287 - rustc_query_system::query::plumbing::get_query_impl::h5ba77d45521abab0
  18:     0x7f1261d11e49 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::deref_const::hd9f581011854b940
  19:     0x7f12612caff6 - rustc_mir_build::thir::pattern::const_to_pat::ConstToPat::recur::h20f1a06016ab4591
  20:     0x7f12612c8e76 - rustc_mir_build::thir::pattern::const_to_pat::ConstToPat::to_pat::h027d34b801cda3ca
  21:     0x7f126129f449 - rustc_infer::infer::InferCtxtBuilder::enter::hb716717d19b47fc3
  22:     0x7f12612aa49f - rustc_mir_build::thir::pattern::const_to_pat::<impl rustc_mir_build::thir::pattern::PatCtxt>::const_to_pat::h7f756f11508cf237
  23:     0x7f12612a962f - rustc_mir_build::thir::pattern::PatCtxt::lower_lit::h2f85917bbfe176c4
  24:     0x7f12612a7523 - rustc_mir_build::thir::pattern::PatCtxt::lower_pattern::h8c1f2b4cac0de295
  25:     0x7f12612d249e - rustc_mir_build::thir::pattern::check_match::MatchVisitor::lower_pattern::hbfd7ad67af9d1b7b
  26:     0x7f12612b62c5 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hf1613ec32b2be86b
  27:     0x7f12612d18fc - <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr::h7d8d6d6c0aea7f2d
  28:     0x7f12612d170c - <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr::h7d8d6d6c0aea7f2d
  29:     0x7f12612d133e - rustc_mir_build::thir::pattern::check_match::check_match::hd138e73ddabdea33
  30:     0x7f1261d352d5 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::ha56d3193e9b0a359
  31:     0x7f12611bdc79 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h97b34b421882c18c
  32:     0x7f1261179219 - rustc_query_system::query::plumbing::force_query_with_job::h3de7e20808f5a4ea
  33:     0x7f1261155991 - rustc_query_system::query::plumbing::get_query_impl::h7c789892a2cbbbf6
  34:     0x7f12611cdcdc - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_match::h4d058915c0f72337
  35:     0x7f1260e64ed4 - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners::h4e8afbfc856b57be
  36:     0x7f12618537e6 - rustc_session::utils::<impl rustc_session::session::Session>::time::hbda29d4d07c62a8f
  37:     0x7f1261860b57 - rustc_interface::passes::analysis::h98b4a9527b987636
  38:     0x7f126031bdda - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h30b34c9dcb235b07
  39:     0x7f1261ceeec0 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h8d236d21d15844b7
  40:     0x7f1261c795d7 - rustc_data_structures::stack::ensure_sufficient_stack::h481edf0a8747b17d
  41:     0x7f1261c472e1 - rustc_query_system::query::plumbing::force_query_with_job::hdbdc575a4c5075f8
  42:     0x7f1261bdcb74 - rustc_query_system::query::plumbing::get_query_impl::h212b99521679522b
  43:     0x7f1261d0fb3f - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::h202822fb7a810e61
  44:     0x7f126184e3d0 - rustc_interface::passes::QueryContext::enter::h1dff05902f17c58a
  45:     0x7f1261820ecd - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h8ab0a704bae2634f
  46:     0x7f126181b5b4 - rustc_span::with_source_map::h512fd197bcd2b7c3
  47:     0x7f12618206a3 - scoped_tls::ScopedKey<T>::set::hd407f010a973eb63
  48:     0x7f1261821eb1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c42279179caa5db
  49:     0x7f126183d285 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd56f564efc764ea1
  50:     0x7f125f2b9258 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd8ea7ada17dfa868
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/alloc/src/boxed.rs:1546:9
  51:     0x7f125f2b9258 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h91ce3a636c58b978
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/alloc/src/boxed.rs:1546:9
  52:     0x7f125f2b9258 - std::sys::unix::thread::Thread::new::thread_start::h2e193c2e23720fdf
                               at /rustc/b3e19a221e63dcffdef87e12eadf1f36a8b90295/library/std/src/sys/unix/thread.rs:71:17
  53:     0x7f125f1c2299 - start_thread
  54:     0x7f125f0d7053 - clone
  55:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (b3e19a221 2021-03-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z incremental-verify-ich=yes -C incremental

query stack during panic:
#0 [check_match] match-checking `main`
#1 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by oli-obk** [comment]
The problem is that the representation changes (the alloc id changes), but the thing still hashes to the same stable hash representation. This will get fixed by value trees for things representable by value trees. For things that are not structural match, I guess we could stop going via a query and just invoke the `deref_const` function directly?

**Comment by matthiaskrgr** [comment]
Still crashing with `rustc 1.59.0-nightly (34926f0a1 2021-12-22)`

**Comment by matthiaskrgr** [comment]
@rustbot prioritize  
We are getting duplicates reported every couple months now and people sink a lot of time into reducing and analyzing these.

Original code still reproduces the problem.
Obviously also reproduces on stable compiler 

````
thread '<unnamed>' panicked at 'forcing query with already existing `DepNode`
- query-key: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing, constness: NotConst }, value: Val(Scalar(alloc5), &[u8; 0]) }
- dep-node: deref_mir_constant(58168a8023dae660-4b49ccbada1af725)', /rustc/ec56537c4325ce5b798fc3628cbdd48ba4949ae5/compiler/rustc_query_system/src/dep_graph/graph.rs:316:9
stack backtrace:
````

**Comment by oli-obk** [comment]
I just looked at this today, because I accidentally fixed it. While that fix doesn't actually resolve the underlying issue, I am now working on the valtree changes that should fix this for good.

**Comment by apiraino** [comment]
If it helps, [another MCVE](https://github.com/rust-lang/rust/issues/101518#issuecomment-1239218663) from #101518

**Comment by sffc** [comment]
https://github.com/rust-lang/rust/issues/93470 also has a different MCVE

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2383085.20incremental.20ICE.3A.20slice-pattern-const.2Ers)).

@rustbot label -I-prioritize +P-medium

**Comment by matthiaskrgr** [comment]
For some reason, this example no longer reproduces this ICE
````rust
fn main() {
    const BOO: &[u8; 0] = &[];
    match &[] {
        BOO => (),
        b"" => (),
        _ => (), 
    }
}
````

but this one still does:

````rust
#[derive(PartialEq, Eq)]
struct Id<'a> {
    ns: &'a str,
}
fn visit_struct() {
    let id = Id { ns: "random1" };
    const FLAG: Id<'static> = Id {
        ns: "needs_to_be_the_same",
    };
    match id {
        FLAG => {}
        _ => {}
    }
}
fn visit_struct2() {
    let id = Id { ns: "random2" };
    const FLAG: Id<'static> = Id {
        ns: "needs_to_be_the_same",
    };
    match id {
        FLAG => {}
        _ => {}
    }
}

fn main() {}
````

**Comment by JohnTitor** [comment]
cc @cjgillot as they have a PR related to this issue.

**Comment by bgeron** [comment]
Workaround: `CARGO_INCREMENTAL=0 cargo clippy`

**Comment by JohnTitor** [comment]
Triage: The latter snippet is now fixed on the latest nightly, @rustbot labels: +E-needs-test

**Comment by oli-obk** [comment]
This was fixed (or made significantly harder to trigger) in https://github.com/rust-lang/rust/pull/111913

I'm working on eliminating all possible avenues for it to happen, but I don't know if we can actually hit it anymore

**Comment by deepu105** [comment]
I'm still seeing this in latest stable (1.72.0 (5680fa18f 2023-08-23)) and nightly (1.74.0-nightly (ef85656a1 2023-08-21))

My repo is here (https://github.com/kdash-rs/kdash) seems to be coming from this [struct](https://github.com/kdash-rs/kdash/blob/main/src/app/key_binding.rs#L73) 

```
cargo clippy -- -D warnings                  
    Checking kdash v0.4.2 (/home/deepu/Workspace/oss-libs/kdash)
thread 'rustc' panicked at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/compiler/rustc_query_system/src/dep_graph/graph.rs:350:9:
forcing query with already existing `DepNode`
- query-key: (ByRef { alloc: ConstAllocation { .. }, offset: Size(0 bytes) }, app::key_binding::KeyBindings)
- dep-node: try_destructure_mir_constant_for_diagnostics(25020fabe91a9fa9-7d50578dbeffb2d6)
stack backtrace:
   0:     0x7fa5509630fc - std::backtrace_rs::backtrace::libunwind::trace::h9e6789d755ef2e35
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fa5509630fc - std::backtrace_rs::backtrace::trace_unsynchronized::hb3533227af2eed61
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fa5509630fc - std::sys_common::backtrace::_print_fmt::hc7dbc1325a62fad4
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fa5509630fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he15329baacfb890f
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fa5509c93bc - core::fmt::rt::Argument::fmt::he237d6d4e685b998
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/core/src/fmt/rt.rs:138:9
   5:     0x7fa5509c93bc - core::fmt::write::h70fc50f283d0f28f
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/core/src/fmt/mod.rs:1094:21
   6:     0x7fa550955c1e - std::io::Write::write_fmt::hddcd4db09551f1e4
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/io/mod.rs:1714:15
   7:     0x7fa550962ee4 - std::sys_common::backtrace::_print::h79b5981c192eb87e
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fa550962ee4 - std::sys_common::backtrace::print::h4e1fc678281db5ea
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fa550965fda - std::panicking::panic_hook_with_disk_dump::{{closure}}::h2f6637765d241d6e
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/panicking.rs:278:22
  10:     0x7fa550965cc7 - std::panicking::panic_hook_with_disk_dump::hdf84cf3f221731ff
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/panicking.rs:312:9
  11:     0x7fa553b0e0b9 - <rustc_driver_impl[f90d201525556a1f]::install_ice_hook::{closure#0} as core[e05ed4681f3f1168]::ops::function::FnOnce<(&core[e05ed4681f3f1168]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7fa550966880 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h18e5faf377bd4349
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/alloc/src/boxed.rs:2021:9
  13:     0x7fa550966880 - std::panicking::rust_panic_with_hook::hdde37fc27effc37e
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/panicking.rs:733:13
  14:     0x7fa550966607 - std::panicking::begin_panic_handler::{{closure}}::h41ca50b22928812a
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/panicking.rs:621:13
  15:     0x7fa550963626 - std::sys_common::backtrace::__rust_end_short_backtrace::hb14e175cfd12d751
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7fa550966352 - rust_begin_unwind
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/panicking.rs:617:5
  17:     0x7fa5509c57c3 - core::panicking::panic_fmt::h24b3f94e75b12286
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/core/src/panicking.rs:67:14
  18:     0x7fa5543d205e - rustc_query_system[b0fd70450df1e068]::query::plumbing::try_execute_query::<rustc_query_impl[4db14ce04f98fad6]::DynamicConfig<rustc_query_system[b0fd70450df1e068]::query::caches::DefaultCache<(rustc_middle[767f7e5b95c87cd]::mir::interpret::value::ConstValue, rustc_middle[767f7e5b95c87cd]::ty::Ty), rustc_middle[767f7e5b95c87cd]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[4db14ce04f98fad6]::plumbing::QueryCtxt, true>
  19:     0x7fa554490673 - rustc_query_impl[4db14ce04f98fad6]::query_impl::try_destructure_mir_constant_for_diagnostics::get_query_incr::__rust_end_short_backtrace
  20:     0x55c77f0fab8b - clippy_utils[209275f6e866e132]::consts::field_of_struct
  21:     0x55c77f0f9201 - <clippy_utils[209275f6e866e132]::consts::ConstEvalLateContext>::expr
  22:     0x55c77f0f8d16 - <clippy_utils[209275f6e866e132]::consts::ConstEvalLateContext>::expr
  23:     0x55c77f0eaff0 - <clippy_utils[209275f6e866e132]::hir_utils::SpanlessHash>::hash_expr
  24:     0x55c77f0ebebc - <clippy_utils[209275f6e866e132]::hir_utils::SpanlessHash>::hash_expr
  25:     0x55c77f0ece71 - clippy_utils[209275f6e866e132]::hir_utils::hash_expr
  26:     0x55c77ef03a47 - clippy_utils[209275f6e866e132]::search_same::<&rustc_hir[81704b56aff4101e]::hir::Expr, clippy_lints[ab95249b62b18b7a]::copies::lint_same_cond::{closure#0}, clippy_lints[ab95249b62b18b7a]::copies::lint_same_cond::{closure#1}>
  27:     0x55c77ed9c794 - <clippy_lints[ab95249b62b18b7a]::copies::CopyAndPaste as rustc_lint[1ace33a67ecac712]::passes::LateLintPass>::check_expr
  28:     0x7fa553f118f9 - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_expr::{closure#0}
  29:     0x7fa553f12268 - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_block
  30:     0x7fa553f1190d - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_expr::{closure#0}
  31:     0x7fa553f1190d - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_expr::{closure#0}
  32:     0x7fa553f12268 - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_block
  33:     0x7fa553f1190d - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_expr::{closure#0}
  34:     0x7fa553f11609 - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_nested_body
  35:     0x7fa553f11bac - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_fn
  36:     0x7fa553f59681 - rustc_hir[81704b56aff4101e]::intravisit::walk_expr::<rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass>>
  37:     0x7fa553f1190d - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_expr::{closure#0}
  38:     0x7fa553f11609 - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_nested_body
  39:     0x7fa553f11bac - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_fn
  40:     0x7fa553f59cdd - rustc_hir[81704b56aff4101e]::intravisit::walk_item::<rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass>>
  41:     0x7fa553f0f7f8 - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_nested_item
  42:     0x7fa553f58a4a - rustc_hir[81704b56aff4101e]::intravisit::walk_mod::<rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass>>
  43:     0x7fa553f0f7f8 - <rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass> as rustc_hir[81704b56aff4101e]::intravisit::Visitor>::visit_nested_item
  44:     0x7fa553f58a4a - rustc_hir[81704b56aff4101e]::intravisit::walk_mod::<rustc_lint[1ace33a67ecac712]::late::LateContextAndPass<rustc_lint[1ace33a67ecac712]::late::RuntimeCombinedLateLintPass>>
  45:     0x7fa552cd5deb - <rustc_session[a57911635946098c]::session::Session>::time::<(), rustc_lint[1ace33a67ecac712]::late::check_crate::{closure#0}::{closure#0}>
  46:     0x7fa552cd4aa9 - <core[e05ed4681f3f1168]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[27d2f6b8fe428ec0]::passes::analysis::{closure#5}::{closure#1}::{closure#2}> as core[e05ed4681f3f1168]::ops::function::FnOnce<()>>::call_once
  47:     0x7fa552cd481f - <core[e05ed4681f3f1168]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[27d2f6b8fe428ec0]::passes::analysis::{closure#5}::{closure#1}> as core[e05ed4681f3f1168]::ops::function::FnOnce<()>>::call_once
  48:     0x7fa552cd4248 - <rustc_session[a57911635946098c]::session::Session>::time::<(), rustc_interface[27d2f6b8fe428ec0]::passes::analysis::{closure#5}>
  49:     0x7fa552cd1fc7 - rustc_interface[27d2f6b8fe428ec0]::passes::analysis
  50:     0x7fa55302ba4a - rustc_query_impl[4db14ce04f98fad6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[4db14ce04f98fad6]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[767f7e5b95c87cd]::query::erase::Erased<[u8; 1usize]>>
  51:     0x7fa55302ba39 - <rustc_query_impl[4db14ce04f98fad6]::query_impl::analysis::dynamic_query::{closure#2} as core[e05ed4681f3f1168]::ops::function::FnOnce<(rustc_middle[767f7e5b95c87cd]::ty::context::TyCtxt, ())>>::call_once
  52:     0x7fa553318188 - rustc_query_system[b0fd70450df1e068]::query::plumbing::try_execute_query::<rustc_query_impl[4db14ce04f98fad6]::DynamicConfig<rustc_query_system[b0fd70450df1e068]::query::caches::SingleCache<rustc_middle[767f7e5b95c87cd]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4db14ce04f98fad6]::plumbing::QueryCtxt, true>
  53:     0x7fa553317ce4 - rustc_query_impl[4db14ce04f98fad6]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  54:     0x7fa552dd6c13 - <rustc_interface[27d2f6b8fe428ec0]::queries::QueryResult<&rustc_middle[767f7e5b95c87cd]::ty::context::GlobalCtxt>>::enter::<core[e05ed4681f3f1168]::result::Result<(), rustc_span[9b5bef724011fe8f]::ErrorGuaranteed>, rustc_driver_impl[f90d201525556a1f]::run_compiler::{closure#1}::{closure#2}::{closure#6}>
  55:     0x7fa552dd5bea - <rustc_interface[27d2f6b8fe428ec0]::interface::Compiler>::enter::<rustc_driver_impl[f90d201525556a1f]::run_compiler::{closure#1}::{closure#2}, core[e05ed4681f3f1168]::result::Result<core[e05ed4681f3f1168]::option::Option<rustc_interface[27d2f6b8fe428ec0]::queries::Linker>, rustc_span[9b5bef724011fe8f]::ErrorGuaranteed>>
  56:     0x7fa552dd2f18 - std[5f485339d878b58d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[27d2f6b8fe428ec0]::util::run_in_thread_pool_with_globals<rustc_interface[27d2f6b8fe428ec0]::interface::run_compiler<core[e05ed4681f3f1168]::result::Result<(), rustc_span[9b5bef724011fe8f]::ErrorGuaranteed>, rustc_driver_impl[f90d201525556a1f]::run_compiler::{closure#1}>::{closure#0}, core[e05ed4681f3f1168]::result::Result<(), rustc_span[9b5bef724011fe8f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e05ed4681f3f1168]::result::Result<(), rustc_span[9b5bef724011fe8f]::ErrorGuaranteed>>
  57:     0x7fa552dd26a5 - <<std[5f485339d878b58d]::thread::Builder>::spawn_unchecked_<rustc_interface[27d2f6b8fe428ec0]::util::run_in_thread_pool_with_globals<rustc_interface[27d2f6b8fe428ec0]::interface::run_compiler<core[e05ed4681f3f1168]::result::Result<(), rustc_span[9b5bef724011fe8f]::ErrorGuaranteed>, rustc_driver_impl[f90d201525556a1f]::run_compiler::{closure#1}>::{closure#0}, core[e05ed4681f3f1168]::result::Result<(), rustc_span[9b5bef724011fe8f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e05ed4681f3f1168]::result::Result<(), rustc_span[9b5bef724011fe8f]::ErrorGuaranteed>>::{closure#1} as core[e05ed4681f3f1168]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  58:     0x7fa5509711e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6086e9a313a3964c
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/alloc/src/boxed.rs:2007:9
  59:     0x7fa5509711e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h930455f80652281f
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/alloc/src/boxed.rs:2007:9
  60:     0x7fa5509711e5 - std::sys::unix::thread::Thread::new::thread_start::hbdbfdb70d010bf36
                               at /rustc/ef85656a10657ba5e4f7fe2931a4ca6293138d51/library/std/src/sys/unix/thread.rs:108:17
  61:     0x7fa55068c9eb - <unknown>
  62:     0x7fa550710ebc - <unknown>
  63:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

note: please attach the file at `/home/deepu/Workspace/oss-libs/kdash/rustc-ice-2023-08-26T06:18:22.625765324Z-30816.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [try_destructure_mir_constant_for_diagnostics] destructuring MIR constant
#1 [analysis] running analysis passes on this crate
end of query stack
note: Clippy version: clippy 0.1.73 (ef85656 2023-08-21)

error: could not compile `kdash` (bin "kdash")
```

**Comment by theCapypara** [comment]
I am also encountering this issue in 1.72.0:
```
thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: (ByRef { alloc: ConstAllocation { .. }, offset: Size(0 bytes) }, database_rw::IndexTag)
- dep-node: try_destructure_mir_constant_for_diagnostics(73691b0231b10194-e3e7b2beeaf2870e)', /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/compiler/rustc_query_system/src/dep_graph/graph.rs:351:9
stack backtrace:
   0:     0x7f4e27962b61 - std::backtrace_rs::backtrace::libunwind::trace::he648b5c8dd376705
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f4e27962b61 - std::backtrace_rs::backtrace::trace_unsynchronized::h5da3e203eef39e9f
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4e27962b61 - std::sys_common::backtrace::_print_fmt::h8d28d3f20588ae4c
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f4e27962b61 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd9a5b0c9c6b058c0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f4e279c977f - core::fmt::rt::Argument::fmt::h0afc04119f252b53
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
   5:     0x7f4e279c977f - core::fmt::write::h50b1b3e73851a6fe
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f4e279554a7 - std::io::Write::write_fmt::h184eaf275e4484f0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/io/mod.rs:1714:15
   7:     0x7f4e27962975 - std::sys_common::backtrace::_print::hf58c3a5a25090e71
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f4e27962975 - std::sys_common::backtrace::print::hb9cf0a7c7f077819
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f4e27965753 - std::panicking::default_hook::{{closure}}::h066adb2e3f3e2c07
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:269:22
  10:     0x7f4e279654e4 - std::panicking::default_hook::h277fa2776900ff14
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:288:9
  11:     0x7f4e2ac6756b - <rustc_driver_impl[10725d833993dc31]::install_ice_hook::{closure#0} as core[f12ae36cc2e1ecf0]::ops::function::FnOnce<(&core[f12ae36cc2e1ecf0]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f4e27965f7e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h09cad52ea08435f2
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:2007:9
  13:     0x7f4e27965f7e - std::panicking::rust_panic_with_hook::hceaf38da6d9db792
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:709:13
  14:     0x7f4e27965d07 - std::panicking::begin_panic_handler::{{closure}}::h2bce3ed2516af7df
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
  15:     0x7f4e27962fc6 - std::sys_common::backtrace::__rust_end_short_backtrace::h090f3faf8f98a395
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
  16:     0x7f4e27965a52 - rust_begin_unwind
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
  17:     0x7f4e279c59f3 - core::panicking::panic_fmt::h4ec8274704d163a3
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
  18:     0x7f4e2b53abc5 - rustc_query_system[5a9d202ec1d2890c]::query::plumbing::try_execute_query::<rustc_query_impl[7f6201a046a7a363]::DynamicConfig<rustc_query_system[5a9d202ec1d2890c]::query::caches::DefaultCache<(rustc_middle[4cadb439cfabc8cf]::mir::interpret::value::ConstValue, rustc_middle[4cadb439cfabc8cf]::ty::Ty), rustc_middle[4cadb439cfabc8cf]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[7f6201a046a7a363]::plumbing::QueryCtxt, true>
  19:     0x7f4e2b5b83a2 - rustc_query_impl[7f6201a046a7a363]::query_impl::try_destructure_mir_constant_for_diagnostics::get_query_incr::__rust_end_short_backtrace
  20:     0x562567cff92f - clippy_utils[9fa82ae0af62f35d]::consts::field_of_struct
  21:     0x562567cfddfa - <clippy_utils[9fa82ae0af62f35d]::consts::ConstEvalLateContext>::expr
  22:     0x562567d92166 - <clippy_utils[9fa82ae0af62f35d]::hir_utils::SpanlessHash>::hash_expr
  23:     0x562567d92399 - <clippy_utils[9fa82ae0af62f35d]::hir_utils::SpanlessHash>::hash_expr
  24:     0x562567d93e41 - clippy_utils[9fa82ae0af62f35d]::hir_utils::hash_expr
  25:     0x562567b5a84a - <clippy_lints[cd65760e4a7ded1c]::copies::CopyAndPaste as rustc_lint[9d740a8528938e29]::passes::LateLintPass>::check_expr
  26:     0x7f4e2b0a9206 - <rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass as rustc_lint[9d740a8528938e29]::passes::LateLintPass>::check_expr
  27:     0x7f4e2b03e6a6 - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass>>::with_lint_attrs::<<rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_expr::{closure#0}::{closure#0}>
  28:     0x7f4e2b03f98c - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_expr
  29:     0x7f4e2b03fa99 - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_block
  30:     0x7f4e2b03e6b1 - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass>>::with_lint_attrs::<<rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_expr::{closure#0}::{closure#0}>
  31:     0x7f4e2b03f98c - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_expr
  32:     0x7f4e2b03fde5 - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_nested_body
  33:     0x7f4e2b03ffca - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_fn
  34:     0x7f4e2b00dd8e - rustc_hir[c7c79bd3af2232c6]::intravisit::walk_trait_item::<rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass>>
  35:     0x7f4e2b040baa - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_nested_trait_item
  36:     0x7f4e2b00f225 - rustc_hir[c7c79bd3af2232c6]::intravisit::walk_item::<rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass>>
  37:     0x7f4e2b0406b7 - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_nested_item
  38:     0x7f4e2b00e7f8 - rustc_hir[c7c79bd3af2232c6]::intravisit::walk_mod::<rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass>>
  39:     0x7f4e2b0406b7 - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_nested_item
  40:     0x7f4e2b00e7f8 - rustc_hir[c7c79bd3af2232c6]::intravisit::walk_mod::<rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass>>
  41:     0x7f4e2b0406b7 - <rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass> as rustc_hir[c7c79bd3af2232c6]::intravisit::Visitor>::visit_nested_item
  42:     0x7f4e2b00e7f8 - rustc_hir[c7c79bd3af2232c6]::intravisit::walk_mod::<rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::late::RuntimeCombinedLateLintPass>>
  43:     0x7f4e2a03002e - rustc_lint[9d740a8528938e29]::late::late_lint_crate::<rustc_lint[9d740a8528938e29]::BuiltinCombinedLateLintPass>
  44:     0x7f4e2a02f448 - <rustc_session[c98e5f13e8087e38]::session::Session>::time::<(), rustc_lint[9d740a8528938e29]::late::check_crate<rustc_lint[9d740a8528938e29]::BuiltinCombinedLateLintPass, rustc_interface[7e6a9899d53a1fe5]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>
  45:     0x7f4e2a02f2d3 - <rustc_session[c98e5f13e8087e38]::session::Session>::time::<(), rustc_interface[7e6a9899d53a1fe5]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  46:     0x7f4e2a02ee0f - <core[f12ae36cc2e1ecf0]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[7e6a9899d53a1fe5]::passes::analysis::{closure#5}::{closure#1}> as core[f12ae36cc2e1ecf0]::ops::function::FnOnce<()>>::call_once
  47:     0x7f4e2a02e800 - <rustc_session[c98e5f13e8087e38]::session::Session>::time::<(), rustc_interface[7e6a9899d53a1fe5]::passes::analysis::{closure#5}>
  48:     0x7f4e2a02d2d7 - rustc_interface[7e6a9899d53a1fe5]::passes::analysis
  49:     0x7f4e2a07dcfa - rustc_query_impl[7f6201a046a7a363]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7f6201a046a7a363]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4cadb439cfabc8cf]::query::erase::Erased<[u8; 1usize]>>
  50:     0x7f4e2a07dce9 - <rustc_query_impl[7f6201a046a7a363]::query_impl::analysis::dynamic_query::{closure#2} as core[f12ae36cc2e1ecf0]::ops::function::FnOnce<(rustc_middle[4cadb439cfabc8cf]::ty::context::TyCtxt, ())>>::call_once
  51:     0x7f4e2a419d8c - rustc_query_system[5a9d202ec1d2890c]::query::plumbing::try_execute_query::<rustc_query_impl[7f6201a046a7a363]::DynamicConfig<rustc_query_system[5a9d202ec1d2890c]::query::caches::SingleCache<rustc_middle[4cadb439cfabc8cf]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[7f6201a046a7a363]::plumbing::QueryCtxt, true>
  52:     0x7f4e2a419934 - rustc_query_impl[7f6201a046a7a363]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  53:     0x7f4e2a12ddf2 - <rustc_interface[7e6a9899d53a1fe5]::queries::QueryResult<&rustc_middle[4cadb439cfabc8cf]::ty::context::GlobalCtxt>>::enter::<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}::{closure#2}::{closure#4}>
  54:     0x7f4e2a12ca97 - <rustc_interface[7e6a9899d53a1fe5]::interface::Compiler>::enter::<rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}::{closure#2}, core[f12ae36cc2e1ecf0]::result::Result<core[f12ae36cc2e1ecf0]::option::Option<rustc_interface[7e6a9899d53a1fe5]::queries::Linker>, rustc_span[14af2d27fb997609]::ErrorGuaranteed>>
  55:     0x7f4e2a129cc5 - rustc_span[14af2d27fb997609]::set_source_map::<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_interface[7e6a9899d53a1fe5]::interface::run_compiler<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  56:     0x7f4e2a129736 - <scoped_tls[a7f541bbfecfca9d]::ScopedKey<rustc_span[14af2d27fb997609]::SessionGlobals>>::set::<rustc_interface[7e6a9899d53a1fe5]::interface::run_compiler<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}>::{closure#0}, core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>>
  57:     0x7f4e2a128cfc - std[7c7acd4e376d60d3]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7e6a9899d53a1fe5]::util::run_in_thread_pool_with_globals<rustc_interface[7e6a9899d53a1fe5]::interface::run_compiler<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}>::{closure#0}, core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>>
  58:     0x7f4e2a4a1305 - <<std[7c7acd4e376d60d3]::thread::Builder>::spawn_unchecked_<rustc_interface[7e6a9899d53a1fe5]::util::run_in_thread_pool_with_globals<rustc_interface[7e6a9899d53a1fe5]::interface::run_compiler<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}>::{closure#0}, core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>>::{closure#1} as core[f12ae36cc2e1ecf0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  59:     0x7f4e27970435 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc0b1022758ecac73
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  60:     0x7f4e27970435 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0c9654ebe7ad657e
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  61:     0x7f4e27970435 - std::sys::unix::thread::Thread::new::thread_start::h04c8e9c7d83d3bd5
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys/unix/thread.rs:108:17
  62:     0x7f4e2748c9eb - <unknown>
  63:     0x7f4e27510dfc - <unknown>
  64:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: rustc 1.72.0 (5680fa18f 2023-08-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [try_destructure_mir_constant_for_diagnostics] destructuring MIR constant
#1 [analysis] running analysis passes on this crate
end of query stack
```

**Comment by Diggsey** [comment]
I'm seeing this on 1.73.0:

```
thread 'rustc' panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\compiler\rustc_query_system\src\dep_graph\graph.rs:350:9:
forcing query with already existing `DepNode`
- query-key: Canonical { value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [Binder { value: OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 0, kind: BrAnon(None) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(None) })), bound_vars: [] }, Binder { value: OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 2, kind: BrAnon(None) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(None) })), bound_vars: [] }, Binder { value: TraitPredicate(<aerosol::Aero<aerosol::frunk::HCons<platformed_types::config::Environment, aerosol::frunk::HCons<sqlx::Pool<sqlx::Postgres>, aerosol::frunk::HCons<cookie::Key, aerosol::frunk::HCons<platformed_types::config::FrontendEnvironment, aerosol::frunk::HCons<notifications::NotificationsService, aerosol::frunk::HCons<postmark::reqwest::PostmarkClient, aerosol::frunk::HCons<external_authorization_providers::ExternalAuthorizationProviders, aerosol::frunk::HCons<document_source_connectors::DocumentSourceConnectors, aerosol::frunk::HCons<crm_connectors::CrmConnectors, aerosol::frunk::HCons<pusher::Pusher, aerosol::frunk::HNil>>>>>>>>>>> as axum::extract::FromRef<S>>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<S as std::marker::Sync>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<S as std::marker::Send>, polarity:Positive), bound_vars: [] }, Binder { value: TraitPredicate(<S as std::marker::Sized>, polarity:Positive), bound_vars: [] }, Binder { value: OutlivesPredicate(auth::apikey::ApikeyAuthenticated, ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(None) })), bound_vars: [] }], reveal: UserFacing }, value: Normalize { value: [async block@backend\src\auth\apikey.rs:29:5: 29:94] } }, max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }] }
- dep-node: type_op_normalize_ty(360ae829af484bfb-a874e7aaa9bc6668)
stack backtrace:
   0:     0x7ff801fd738a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c22c4185b55f04
   1:     0x7ff80200bb5b - core::fmt::write::h8a7f6edbcadee319
   2:     0x7ff801fccc51 - <std::io::IoSlice as core::fmt::Debug>::fmt::h0ee392ef0f96e369
   3:     0x7ff801fd710a - std::sys_common::backtrace::lock::h134eeaadb35136bd
   4:     0x7ff801fda8ca - std::panicking::default_hook::h81d7caaa8c7a40b4
   5:     0x7ff801fda538 - std::panicking::default_hook::h81d7caaa8c7a40b4
   6:     0x7ffff950d77e - <tracing_subscriber[610e65fa1e67acd7]::fmt::format::Writer>::write_fmt
   7:     0x7ff801fdb1cc - std::panicking::rust_panic_with_hook::h8ac326f3b5470b08
   8:     0x7ff801fdaf2d - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h353ca2f9698f73b3
   9:     0x7ff801fd8049 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c22c4185b55f04
  10:     0x7ff801fdac30 - rust_begin_unwind
  11:     0x7ff802040d85 - core::panicking::panic_fmt::hb3ce2a19a4187054
  12:     0x7ffff81d79e0 - rustc_query_impl[4ba43568455dd7ab]::profiling_support::alloc_self_profile_query_strings
  13:     0x7ffff81ab7ca - rustc_query_impl[4ba43568455dd7ab]::profiling_support::alloc_self_profile_query_strings
  14:     0x7ffff92e84b2 - <rustc_middle[b5332b31642963de]::ty::Ty as rustc_trait_selection[9902775d3ca89432]::traits::query::type_op::normalize::Normalizable>::type_op_method
  15:     0x7ffff8db94a4 - <rustc_middle[b5332b31642963de]::mir::Location as rustc_borrowck[fb846e6ad746f446]::type_check::NormalizeLocation>::to_locations
  16:     0x7ffff8d52981 - <rustc_borrowck[fb846e6ad746f446]::borrow_set::BorrowSet>::get_index_of
  17:     0x7ffff8ccbecb - <rustc_borrowck[fb846e6ad746f446]::MirBorrowckCtxt>::consume_operand
  18:     0x7ffff8cc3f53 - <rustc_ast[65138fc56adf9c85]::ast::Mutability as rustc_mir_build[17142fd2530d5213]::thir::cx::expr::ToBorrowKind>::to_borrow_kind
  19:     0x7ffff8e6319f - <rustc_query_impl[4ba43568455dd7ab]::plumbing::QueryCtxt as rustc_query_system[c38485a12e398234]::query::QueryContext>::load_side_effects
  20:     0x7ffff8e9584f - <rustc_query_impl[4ba43568455dd7ab]::plumbing::QueryCtxt as rustc_query_system[c38485a12e398234]::query::QueryContext>::load_side_effects
  21:     0x7ffff8f363e2 - <rustc_query_impl[4ba43568455dd7ab]::plumbing::QueryCtxt as rustc_query_system[c38485a12e398234]::query::QueryContext>::load_side_effects
  22:     0x7ffff8ebf512 - <rustc_query_impl[4ba43568455dd7ab]::plumbing::QueryCtxt as rustc_query_system[c38485a12e398234]::query::QueryContext>::load_side_effects
  23:     0x7ffff80d8423 - <rustc_borrowck[fb846e6ad746f446]::constraint_generation::ConstraintGeneration as rustc_middle[b5332b31642963de]::mir::visit::Visitor>::visit_statement
  24:     0x7ffff8d74c4d - <rustc_borrowck[fb846e6ad746f446]::universal_regions::UniversalRegionIndices>::insert_late_bound_region
  25:     0x7ffff8d52e33 - <rustc_borrowck[fb846e6ad746f446]::borrow_set::BorrowSet>::get_index_of
  26:     0x7ffff8ccbecb - <rustc_borrowck[fb846e6ad746f446]::MirBorrowckCtxt>::consume_operand
  27:     0x7ffff8cc3f53 - <rustc_ast[65138fc56adf9c85]::ast::Mutability as rustc_mir_build[17142fd2530d5213]::thir::cx::expr::ToBorrowKind>::to_borrow_kind
  28:     0x7ffff8e6319f - <rustc_query_impl[4ba43568455dd7ab]::plumbing::QueryCtxt as rustc_query_system[c38485a12e398234]::query::QueryContext>::load_side_effects
  29:     0x7ffff8e9584f - <rustc_query_impl[4ba43568455dd7ab]::plumbing::QueryCtxt as rustc_query_system[c38485a12e398234]::query::QueryContext>::load_side_effects
  30:     0x7ffff8f363e2 - <rustc_query_impl[4ba43568455dd7ab]::plumbing::QueryCtxt as rustc_query_system[c38485a12e398234]::query::QueryContext>::load_side_effects
  31:     0x7ffff8ebf512 - <rustc_query_impl[4ba43568455dd7ab]::plumbing::QueryCtxt as rustc_query_system[c38485a12e398234]::query::QueryContext>::load_side_effects
  32:     0x7ffff8582dea - once_cell[d15d86c0a05b271b]::imp::initialize_or_wait
  33:     0x7ffff5716d2f - time_core[9f5980238a4d8d4f]::util::is_leap_year
  34:     0x7ffff57320f8 - rustc_interface[1fce9354a182ed1c]::passes::analysis
  35:     0x7ffff815ee7d - rustc_query_impl[4ba43568455dd7ab]::profiling_support::alloc_self_profile_query_strings
  36:     0x7ffff8172849 - rustc_query_impl[4ba43568455dd7ab]::profiling_support::alloc_self_profile_query_strings
  37:     0x7ffff81748b5 - rustc_query_impl[4ba43568455dd7ab]::profiling_support::alloc_self_profile_query_strings
  38:     0x7ffff81c8637 - rustc_query_impl[4ba43568455dd7ab]::profiling_support::alloc_self_profile_query_strings
  39:     0x7ffff818dbac - rustc_query_impl[4ba43568455dd7ab]::profiling_support::alloc_self_profile_query_strings
  40:     0x7ffff56dd891 - rustc_driver_impl[1e281a1232643afa]::args::arg_expand_all
  41:     0x7ffff56ebd6d - <rustc_middle[b5332b31642963de]::ty::SymbolName as core[480aa84f3feba9e5]::fmt::Debug>::fmt
  42:     0x7ffff56e91c6 - <rustc_middle[b5332b31642963de]::ty::SymbolName as core[480aa84f3feba9e5]::fmt::Debug>::fmt
  43:     0x7ffff56ea806 - <rustc_middle[b5332b31642963de]::ty::SymbolName as core[480aa84f3feba9e5]::fmt::Debug>::fmt
  44:     0x7ff801fee3ec - std::sys::windows::thread::Thread::new::h75a9ed52a5af2748
  45:     0x7ff8d24a7344 - BaseThreadInitThunk
  46:     0x7ff8d31a26b1 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.73.0 (cc66ad468 2023-10-03) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [type_op_normalize_ty] normalizing `[async block@backend\src\auth\apikey.rs:29:5: 29:94]`
#1 [mir_borrowck] borrow-checking `auth::apikey::<impl at backend\src\auth\apikey.rs:22:1: 22:52>::from_request_parts::{closure#0}`
#2 [mir_borrowck] borrow-checking `auth::apikey::<impl at backend\src\auth\apikey.rs:22:1: 22:52>::from_request_parts`
#3 [analysis] running analysis passes on this crate
end of query stack
```

**Comment by Diggsey** [comment]
The top of the query stack points to this attribute:
```rust
#[tracing::instrument(name = "extractor.apikey_authenticated", level = "info", skip_all)]
```

Bizarrely, if I comment out this attribute and re-compile, then everything is fine. Then if I uncomment it again, and compile again, everything works correctly. (Until I next do a build from scratch that is...)
