### ISSUE TITLE
Server at http://rust-lang.org/ is not HTTP/1.1 compliant

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#8435]
## Steps to reproduce

1. Open a TCP connection to rust-lang.org, port 80. (You can use `telnet rust-lang.org 80`)
2. Send a request like this:

    ```
    GET http://rust-lang.org/ HTTP/1.1
    Host: rust-lang.org

    ```

## Expected result

Response should be 301 Moved Permanently with the location header set to `http://www.rust-lang.org/`.

## Actual result

```
HTTP/1.1 302 Found
Date: Sat, 10 Aug 2013 08:00:11 GMT
Server: Apache/2.2.16 (Debian)
X-Powered-By: PHP/5.3.3-7+squeeze16
Location: http://www.rust-lang.orghttp://rust-lang.org/
Vary: Accept-Encoding
Content-Length: 0
Content-Type: text/html

```

There are two problems with this:

- 302 Found, rather than 301 Moved Permanently, is semantically incorrect.

- Location shows that it's taken the Request-URI verbatim rather than interpreting it correctly as an absoluteURI. (RFC 2616 says that "all HTTP/1.1 servers MUST accept the absoluteURI form in requests".)

**Comment by beatgammit** [comment]
This is still an issue, and going to http://rust-lang.org gives me [this](http://imgur.com/s4akw7t).

Since rust has now reached 1.0-alpha, I imagine more and more people will be visiting the home page and accidentally getting the default Apache "It works!" page.

I assume that if the correct `301` error were returned my browser would be appropriately redirected.

**Comment by dignati** [comment]
+1

I sometimes get this on OS X 10.10 with Google Chrome 41.0.2267.0 dev (64-bit)

**Comment by beatgammit** [comment]
It looks like part of this is fixed since going to http://rust-lang.org works now. I'm guessing the `Location` header was wrong before and is now correct, but I can't remember what it was set to before.

However, the status code is still `302` when it should probably be `301`.

**Comment by BigBoneDaddy** [comment]
@dignati Why is it only the sometimes that it happens? Why not all the times?

**Comment by Stebalien** [comment]
Still an issue (still returning `Location: http://www.rust-lang.orghttp://rust-lang.org`). This should probably be moved to https://github.com/rust-lang/rust-www

**Comment by steveklabnik** [comment]
Yup, let's move it.
