### ISSUE TITLE
[ER] Array bound test for capped index

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#84902]
Title: 
Currently certain optimizations are brittle:

```rust
pub fn foo(arr: &[u32; 100], mut i: usize) -> u32 {
    if i >= 100 { i = 0; }
    arr[i]
}

pub fn bar(arr: &[u32; 100], mut i: usize) -> u32 {
    if i >= arr.len() { i = 0; }
    arr[i]
}
```

rustc 1.54.0-nightly (716394d65 2021-05-03) gives:

```asm
foo:
    push    rax
    mov     rax, rdi
    xor     edi, edi
    cmp     rsi, 99
    cmovbe  rdi, rsi
    cmp     rdi, 99
    ja      .LBB0_2
    mov     eax, dword ptr [rax + 4*rdi]
    pop     rcx
    ret
.LBB0_2:
    lea     rdx, [rip + .L__unnamed_1]
    mov     esi, 100
    call    qword ptr [rip + core::panicking::panic_bounds_check@GOTPCREL]
    ud2


bar:
    xor     eax, eax
    cmp     rsi, 99
    cmovbe  rax, rsi
    mov     eax, dword ptr [rdi + 4*rax]
    ret
```

**Comment by nikic** [comment]
Godbolt: https://rust.godbolt.org/z/4GefGqsMP

I think I already fixed this one upstream.

**Comment by leonardo-m** [comment]
> Godbolt: https://rust.godbolt.org/z/4GefGqsMP
> 
> I think I already fixed this one upstream.

with rustc 1.54.0-nightly (6d395a1c2 2021-05-13) I'm still seeing the bound test.

**Comment by nikic** [comment]
Right, it would need an LLVM upgrade.

**Comment by clubby789** [comment]
This is now optimal on stable
@rustbot label +A-llvm
