### ISSUE TITLE
UX/UI rustdoc error: "impl FromIterator for Result" is not documented on FromIterator page

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/rust#92641]
I opened documentation of FromIterator ( https://doc.rust-lang.org/std/iter/trait.FromIterator.html ), then I scrolled to section "Implementors" and found this implementation:
```rust
impl<A, E, V> FromIterator<Result<A, E>> for Result<V, E>
where
    V: FromIterator<A>,
```
This implementation was not documented on this page. I clicked "[src]" and was able to see docs in source. So, I thought that there is some bug in rustdoc, which causes this docs not to render. Then I opened page on Result ( https://doc.rust-lang.org/std/result/enum.Result.html ) and (susprisiongly) found that this impl is documented there! So, for unknown reasons rustdoc shows this doc on Result page, but doesn't show it on FromIterator page

**Comment by fmease** [comment]
This issue seems to have been fixed at some unknown point in time. It should be closed.

`Result` [is now documented](https://doc.rust-lang.org/std/iter/trait.FromIterator.html#impl-FromIterator%3CResult%3CA%2C%20E%3E%3E) as an implementor on the `FromIterator` page.
For completeness, [here is the link](https://doc.rust-lang.org/std/result/enum.Result.html#impl-FromIterator%3CResult%3CA%2C%20E%3E%3E) to the `FromIterator` impl on the `Result` page.

**Comment by safinaskar** [comment]
@fmease , I still don't see docs at link you provided. I mean I see implementation itself, but I don't see docs, i. e. I don't see text "Takes each element in the `Iterator`: if it is an `Err`, no further..."

My browser is Google Chrome 103.0.5060.53 on Debian Stretch

**Comment by fmease** [comment]
Oh my bad, I misread the issue.

The documentation *Takes each element  […]* is not being shown on the `FromIterator` page because it belongs to the method `from_iter` and not to the `impl` block and rustdoc doesn't display any associated items (like in this case `from_iter`) in a trait's *Implementors* sections but only the “headers” of `impl` blocks (to save disk space and reduce render time I think).

All in all, this doesn't appear to be a rustdoc issue.
However, the question might still remain whether the doc comments should be moved from the method to the `impl` block. Not sure. The current locations looks fine to me.

**Comment by safinaskar** [comment]
@fmease , thanks for explanation.

I think rustdoc should show full docs in implementors. Or at least provide a link to full docs. In current form this docs are too hard to find

**Comment by lolbinarycat** [comment]
clarifying this issue because it took me a bit to understand:

if you go to the "implementors"  section on a trait page, you will simply get a list of impl items, along with any documentation that appears *on the block itself*:

![Image](https://github.com/user-attachments/assets/2954a477-0e84-4aff-99d4-94ae0ffb2589)

if you go to the "trait implementations" section on a type page, you will get a *collapsible* list of impl blocks, *including the contents of the impl block, such as documentation on method implemenations*:

![Image](https://github.com/user-attachments/assets/8f7c3048-4b27-44d0-a198-9d12095a04ad)

this inconsistency is confusing, since, for traits that have only a single method, implementors sometimes document details of their implementation on that method, and sometimes they do so on the impl block itself.
