### ISSUE TITLE
rustc_resolve: entered unreachable code in resolve_rustdoc_path

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#96012]
### Code

"all of rustdoc"

### Meta

`rustc --version --verbose`: rustc 1.62.0 (23a96e02d 2022-04-13) 

@rustbot label +T-rustdoc +A-resolve

### Error output

See the logs for https://github.com/rust-lang-ci/rust/runs/6005865530?check_suite_focus=true.

@petrochenkov this may not be worth investigating until I find a way to reproduce locally - just tagging you in case it's a simple fix.

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'internal error: entered unreachable code', compiler/rustc_resolve/src/lib.rs:1834:67
stack backtrace:
   0:     0x7f919bf11b72 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h40f8f3daa23f431e
   1:     0x7f919bf774a8 - core::fmt::write::h42d747535ccbaf5b
   2:     0x7f919bf02031 - std::io::Write::write_fmt::h495dbdc99589b77c
   3:     0x7f919bf14ea6 - std::panicking::default_hook::{{closure}}::h1f2cfb3a6707d9fe
   4:     0x7f919bf14aa5 - std::panicking::default_hook::h07bf01758e423d7c
   5:     0x7f919d0828fa - rustc_driver[9c3f2120bbf7371d]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:     0x7f918f29eb09 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hff3a3945c56c0b18
   7:     0x7f918f2ca3fb - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::hd8f4bb99054a635a
   8:     0x7f919bf157cd - std::panicking::rust_panic_with_hook::h85a296a572b16b0f
   9:     0x7f919bf15619 - std::panicking::begin_panic_handler::{{closure}}::h1b6f091ffeaf8dfa
  10:     0x7f919bf12114 - std::sys_common::backtrace::__rust_end_short_backtrace::h6654ca9f5c52ca6c
  11:     0x7f919bf15349 - rust_begin_unwind
  12:     0x7f919bec80e3 - core::panicking::panic_fmt::h7e15babac27fb630
  13:     0x7f919bec7fad - core::panicking::panic::h59ba1f41023369f0
  14:     0x7f91a144590b - <rustc_resolve[5e2eeef38d5b363f]::Resolver>::resolve_rustdoc_path
  15:     0x55d80d768ac0 - <rustdoc[234ebe4e4ad05f8c]::passes::collect_intra_doc_links::early::EarlyDocLinkResolver>::load_links_in_attrs
  16:     0x55d80d769144 - <rustdoc[234ebe4e4ad05f8c]::passes::collect_intra_doc_links::early::EarlyDocLinkResolver as rustc_ast[70b27e4311c19868]::visit::Visitor>::visit_item
  17:     0x55d80d7776fa - rustc_ast[70b27e4311c19868]::visit::walk_item::<rustdoc[234ebe4e4ad05f8c]::passes::collect_intra_doc_links::early::EarlyDocLinkResolver>
  18:     0x55d80d76918e - <rustdoc[234ebe4e4ad05f8c]::passes::collect_intra_doc_links::early::EarlyDocLinkResolver as rustc_ast[70b27e4311c19868]::visit::Visitor>::visit_item
  19:     0x55d80d7776fa - rustc_ast[70b27e4311c19868]::visit::walk_item::<rustdoc[234ebe4e4ad05f8c]::passes::collect_intra_doc_links::early::EarlyDocLinkResolver>
  20:     0x55d80d76918e - <rustdoc[234ebe4e4ad05f8c]::passes::collect_intra_doc_links::early::EarlyDocLinkResolver as rustc_ast[70b27e4311c19868]::visit::Visitor>::visit_item
  21:     0x55d80d70d72a - <rustc_interface[4431ea57bd42aced]::passes::boxed_resolver::BoxedResolver>::access::<rustdoc[234ebe4e4ad05f8c]::main_options::{closure#0}::{closure#0}::{closure#0}, rustdoc[234ebe4e4ad05f8c]::core::ResolverCaches>
  22:     0x55d80d5fc001 - <rustc_interface[4431ea57bd42aced]::interface::Compiler>::enter::<rustdoc[234ebe4e4ad05f8c]::main_options::{closure#0}::{closure#0}, core[734429170246c524]::result::Result<(), rustc_errors[65f611344d5dc886]::ErrorGuaranteed>>
  23:     0x55d80d412296 - rustc_span[c84b1e53812dd887]::with_source_map::<core[734429170246c524]::result::Result<(), rustc_errors[65f611344d5dc886]::ErrorGuaranteed>, rustc_interface[4431ea57bd42aced]::interface::create_compiler_and_run<core[734429170246c524]::result::Result<(), rustc_errors[65f611344d5dc886]::ErrorGuaranteed>, rustdoc[234ebe4e4ad05f8c]::main_options::{closure#0}>::{closure#1}>
  24:     0x55d80d5ff063 - rustc_interface[4431ea57bd42aced]::interface::create_compiler_and_run::<core[734429170246c524]::result::Result<(), rustc_errors[65f611344d5dc886]::ErrorGuaranteed>, rustdoc[234ebe4e4ad05f8c]::main_options::{closure#0}>
  25:     0x55d80d44b7da - rustdoc[234ebe4e4ad05f8c]::main_options
  26:     0x55d80d7af2db - <scoped_tls[9d249f0f2ce07b71]::ScopedKey<rustc_span[c84b1e53812dd887]::SessionGlobals>>::set::<rustdoc[234ebe4e4ad05f8c]::main_args::{closure#0}, core[734429170246c524]::result::Result<(), rustc_errors[65f611344d5dc886]::ErrorGuaranteed>>
  27:     0x55d80d64eb2f - std[801cb7f74ea44579]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[4431ea57bd42aced]::util::run_in_thread_pool_with_globals<rustdoc[234ebe4e4ad05f8c]::main_args::{closure#0}, core[734429170246c524]::result::Result<(), rustc_errors[65f611344d5dc886]::ErrorGuaranteed>>::{closure#0}, core[734429170246c524]::result::Result<(), rustc_errors[65f611344d5dc886]::ErrorGuaranteed>>
  28:     0x55d80d6f7769 - <<std[801cb7f74ea44579]::thread::Builder>::spawn_unchecked_<rustc_interface[4431ea57bd42aced]::util::run_in_thread_pool_with_globals<rustdoc[234ebe4e4ad05f8c]::main_args::{closure#0}, core[734429170246c524]::result::Result<(), rustc_errors[65f611344d5dc886]::ErrorGuaranteed>>::{closure#0}, core[734429170246c524]::result::Result<(), rustc_errors[65f611344d5dc886]::ErrorGuaranteed>>::{closure#1} as core[734429170246c524]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  29:     0x7f919bf21f83 - std::sys::unix::thread::Thread::new::thread_start::hadd5bbf9df9317ed
  30:     0x7f919be3f609 - start_thread
  31:     0x7f919bbf8163 - clone
  32:                0x0 - <unknown>
```

</p>
</details>

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/blob/f38c5c8e5d76ea9a87fece143425ef7c703c706a/compiler/rustc_resolve/src/lib.rs#L1826-L1835

**Comment by petrochenkov** [comment]
This should be fixed either by https://github.com/rust-lang/rust/pull/95681 or by https://github.com/rust-lang/rust/pull/95887.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/95681 is in the commit history for https://github.com/rust-lang/rust/commit/23a96e02d620767e71ce4810a925e92db595a497, but I can try again when https://github.com/rust-lang/rust/pull/95887 is merged :+1:

**Comment by bonsairobo** [comment]
Related to #108762

I have a reliable repro of this panic (`cargo clean` does not fix), but I'm compiling a different crate (bevy_reflect). The ICE is accompanied by failures to resolve a crate that should exist. Both issues appear to be fixed in toolchain v1.73. I have not been able to reproduce this anywhere other than my NixOS environment, but I'm aware of one other Bevy user that has run into this issue.

```
rustc --version
rustc 1.72.1 (d5c2e9c34 2023-09-13)
```

I'm using NixOS, but only `rustup` was installed via nixpkgs. My toolchain was installed with `rustup`.

# Repro

```
git clone https://github.com/bevyengine/bevy
cd bevy/crates/bevy_reflect
git checkout aced6aff041555b97d97c96381b551527569881f
cargo check --all-features
```

If you try this on NixOS, you will likely need to create a `flake.nix` containing at least the following:

<details>
<summary> flake.nix </summary>

  ```nix
  {
    description = "NixOS environment";
  
    inputs = {
      nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    };
  
    outputs = {
      self,
      nixpkgs,
    }: let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      devShell.${system} = with pkgs;
        mkShell rec {
          # Rust binaries need to be able to link and load some system libraries.
          buildInputs = [
            pkg-config
            udev
          ];
          LD_LIBRARY_PATH = lib.makeLibraryPath buildInputs;
        };
    };
  }
  ```
</details>

And then `git add flake.nix` and `nix develop` before it will take effect.

<details>
<summary> Error logs </summary>

```
error[E0463]: can't find crate for `bevy_crevice_derive`
 --> crates/bevy_crevice/src/glsl.rs:3:9
  |
3 | pub use bevy_crevice_derive::GlslStruct;
  |         ^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `bevy_crevice_derive`
  --> crates/bevy_crevice/src/std140.rs:18:9
   |
18 | pub use bevy_crevice_derive::AsStd140;
   |         ^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `bevy_crevice_derive`
  --> crates/bevy_crevice/src/std430.rs:16:9
   |
16 | pub use bevy_crevice_derive::AsStd430;
   |         ^^^^^^^^^^^^^^^^^^^ can't find crate

error: cannot determine resolution for the import
 --> crates/bevy_crevice/src/std140/dynamic_uniform.rs:5:21
  |
5 | use crate::std140::{AsStd140, Std140};
  |                     ^^^^^^^^

error: cannot determine resolution for the import
 --> crates/bevy_crevice/src/std140/sizer.rs:4:21
  |
4 | use crate::std140::{AsStd140, Std140};
  |                     ^^^^^^^^

error: cannot determine resolution for the import
 --> crates/bevy_crevice/src/std140/writer.rs:7:21
  |
7 | use crate::std140::{AsStd140, Std140, WriteStd140};
  |                     ^^^^^^^^

error: cannot determine resolution for the import
 --> crates/bevy_crevice/src/std430/sizer.rs:4:21
  |
4 | use crate::std430::{AsStd430, Std430};
  |                     ^^^^^^^^

error: cannot determine resolution for the import
 --> crates/bevy_crevice/src/std430/writer.rs:7:21
  |
7 | use crate::std430::{AsStd430, Std430, WriteStd430};
  |                     ^^^^^^^^

error[E0432]: unresolved imports `crate::std140::AsStd140`, `crate::std140::AsStd140`, `crate::std140::AsStd140`, `crate::std430::AsStd430`, `crate::std430::AsStd430`
 --> crates/bevy_crevice/src/std140/dynamic_uniform.rs:5:21
  |
5 | use crate::std140::{AsStd140, Std140};
  |                     ^^^^^^^^
  |
 ::: crates/bevy_crevice/src/std140/sizer.rs:4:21
  |
4 | use crate::std140::{AsStd140, Std140};
  |                     ^^^^^^^^
  |
 ::: crates/bevy_crevice/src/std140/writer.rs:7:21
  |
7 | use crate::std140::{AsStd140, Std140, WriteStd140};
  |                     ^^^^^^^^
  |
 ::: crates/bevy_crevice/src/std430/sizer.rs:4:21
  |
4 | use crate::std430::{AsStd430, Std430};
  |                     ^^^^^^^^
  |
 ::: crates/bevy_crevice/src/std430/writer.rs:7:21
  |
7 | use crate::std430::{AsStd430, Std430, WriteStd430};
  |                     ^^^^^^^^

thread 'rustc' panicked at 'internal error: entered unreachable code', compiler/rustc_resolve/src/lib.rs:1910:67
stack backtrace:
   0:     0x7ffff3912b51 - std::backtrace_rs::backtrace::libunwind::trace::h66dc1c6acf794faa
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ffff3912b51 - std::backtrace_rs::backtrace::trace_unsynchronized::ha80d20099a67f790
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ffff3912b51 - std::sys_common::backtrace::_print_fmt::h7b959d43f35f16d4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7ffff3912b51 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdaa196410d9ee0b9
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ffff39796ff - core::fmt::rt::Argument::fmt::h0ddfbbe8be3f80d0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/rt.rs:138:9
   5:     0x7ffff39796ff - core::fmt::write::h66b3c629f3d623e4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/mod.rs:1094:21
   6:     0x7ffff3905497 - std::io::Write::write_fmt::hb6d80fba4115e0c2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/io/mod.rs:1714:15
   7:     0x7ffff3912965 - std::sys_common::backtrace::_print::h1a49cfb0cf3cce17
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7ffff3912965 - std::sys_common::backtrace::print::hca95c2d0055e42a2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7ffff3915743 - std::panicking::default_hook::{{closure}}::hc03c01c56bca600c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:269:22
  10:     0x7ffff39154d4 - std::panicking::default_hook::hb2cb5315b6634f1c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:288:9
error[E0463]: can't find crate for `bevy_reflect_derive`
 --> crates/bevy_reflect/src/type_uuid.rs:1:9
  |
1 | pub use bevy_reflect_derive::TypeUuid;
  |         ^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `bevy_reflect_derive`
 --> crates/bevy_reflect/src/impls/glam.rs:5:5
  |
5 | use bevy_reflect_derive::{impl_from_reflect_value, impl_reflect_struct, impl_reflect_value};
  |     ^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `bevy_reflect_derive`
 --> crates/bevy_reflect/src/impls/std.rs:8:5
  |
8 | use bevy_reflect_derive::{impl_from_reflect_value, impl_reflect_value};
  |     ^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `bevy_reflect_derive`
  --> crates/bevy_reflect/src/lib.rs:49:9
   |
49 | pub use bevy_reflect_derive::*;
   |         ^^^^^^^^^^^^^^^^^^^ can't find crate

  11:     0x7ffff6c6b60b - rustc_driver_impl[e91af841be79713a]::install_ice_hook::{closure#0}
  12:     0x7ffff3915f6e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb3a915ffd78277c6
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
  13:     0x7ffff3915f6e - std::panicking::rust_panic_with_hook::h75cd912a39a34e8a
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:709:13
  14:     0x7ffff3915cb1 - std::panicking::begin_panic_handler::{{closure}}::h1498b46f7849e167
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:595:13
  15:     0x7ffff3912fb6 - std::sys_common::backtrace::__rust_end_short_backtrace::hd36a39b27b98086b
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
  16:     0x7ffff3915a42 - rust_begin_unwind
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
  17:     0x7ffff3975973 - core::panicking::panic_fmt::h98ef273141454c23
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
  18:     0x7ffff3975a03 - core::panicking::panic::hf53fd8b0bfa5848e
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:117:5
  19:     0x7ffff5c9831d - <rustc_resolve[1095f176748759de]::Resolver>::resolve_rustdoc_path
  20:     0x7ffff5c96d50 - <rustc_resolve[1095f176748759de]::late::LateResolutionVisitor>::resolve_and_cache_rustdoc_path
  21:     0x7ffff5c92ea7 - <rustc_resolve[1095f176748759de]::late::LateResolutionVisitor>::resolve_doc_links
  22:     0x7ffff5c819d2 - <rustc_resolve[1095f176748759de]::Resolver>::late_resolve_crate
  23:     0x7ffff5c80bf3 - <rustc_session[7bc6f0e7ff11a78e]::session::Session>::time::<(), <rustc_resolve[1095f176748759de]::Resolver>::resolve_crate::{closure#0}>
  24:     0x7ffff5c7de26 - rustc_interface[9522ab489a5f66e6]::passes::resolver_for_lowering
  25:     0x7ffff608f47a - rustc_query_impl[e7af9ba2ee20c49a]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e7af9ba2ee20c49a]::query_impl::resolver_for_lowering::dynamic_query::{closure#2}::{closure#0}, rustc_middle[fbd75b4db2cdb7e6]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7ffff608f469 - <rustc_query_impl[e7af9ba2ee20c49a]::query_impl::resolver_for_lowering::dynamic_query::{closure#2} as core[63ccc595abf60ca6]::ops::function::FnOnce<(rustc_middle[fbd75b4db2cdb7e6]::ty::context::TyCtxt, ())>>::call_once
  27:     0x7ffff63ba02d - rustc_query_system[8b63fd0ca5778b73]::query::plumbing::try_execute_query::<rustc_query_impl[e7af9ba2ee20c49a]::DynamicConfig<rustc_query_system[8b63fd0ca5778b73]::query::caches::SingleCache<rustc_middle[fbd75b4db2cdb7e6]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[e7af9ba2ee20c49a]::plumbing::QueryCtxt, true>
  28:     0x7ffff65abd30 - rustc_query_impl[e7af9ba2ee20c49a]::query_impl::resolver_for_lowering::get_query_incr::__rust_end_short_backtrace
  29:     0x7ffff6123a70 - <rustc_interface[9522ab489a5f66e6]::queries::QueryResult<&rustc_middle[fbd75b4db2cdb7e6]::ty::context::GlobalCtxt>>::enter::<&rustc_data_structures[bf281432ed14a641]::steal::Steal<(rustc_middle[fbd75b4db2cdb7e6]::ty::ResolverAstLowering, alloc[1f40c6002c873f6d]::rc::Rc<rustc_ast[aa587559a0856461]::ast::Crate>)>, rustc_driver_impl[e91af841be79713a]::run_compiler::{closure#1}::{closure#2}::{closure#2}>
  30:     0x7ffff61224ab - <rustc_interface[9522ab489a5f66e6]::interface::Compiler>::enter::<rustc_driver_impl[e91af841be79713a]::run_compiler::{closure#1}::{closure#2}, core[63ccc595abf60ca6]::result::Result<core[63ccc595abf60ca6]::option::Option<rustc_interface[9522ab489a5f66e6]::queries::Linker>, rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>>
  31:     0x7ffff611f7b5 - rustc_span[ca0c6fb73220b455]::set_source_map::<core[63ccc595abf60ca6]::result::Result<(), rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>, rustc_interface[9522ab489a5f66e6]::interface::run_compiler<core[63ccc595abf60ca6]::result::Result<(), rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>, rustc_driver_impl[e91af841be79713a]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  32:     0x7ffff611f226 - <scoped_tls[35a2f59988e0a19c]::ScopedKey<rustc_span[ca0c6fb73220b455]::SessionGlobals>>::set::<rustc_interface[9522ab489a5f66e6]::interface::run_compiler<core[63ccc595abf60ca6]::result::Result<(), rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>, rustc_driver_impl[e91af841be79713a]::run_compiler::{closure#1}>::{closure#0}, core[63ccc595abf60ca6]::result::Result<(), rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>>
  33:     0x7ffff611e7ec - std[74d10c9f32099e86]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[9522ab489a5f66e6]::util::run_in_thread_pool_with_globals<rustc_interface[9522ab489a5f66e6]::interface::run_compiler<core[63ccc595abf60ca6]::result::Result<(), rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>, rustc_driver_impl[e91af841be79713a]::run_compiler::{closure#1}>::{closure#0}, core[63ccc595abf60ca6]::result::Result<(), rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[63ccc595abf60ca6]::result::Result<(), rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>>
  34:     0x7ffff64a53b5 - <<std[74d10c9f32099e86]::thread::Builder>::spawn_unchecked_<rustc_interface[9522ab489a5f66e6]::util::run_in_thread_pool_with_globals<rustc_interface[9522ab489a5f66e6]::interface::run_compiler<core[63ccc595abf60ca6]::result::Result<(), rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>, rustc_driver_impl[e91af841be79713a]::run_compiler::{closure#1}>::{closure#0}, core[63ccc595abf60ca6]::result::Result<(), rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[63ccc595abf60ca6]::result::Result<(), rustc_span[ca0c6fb73220b455]::ErrorGuaranteed>>::{closure#1} as core[63ccc595abf60ca6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  35:     0x7ffff3920425 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hde6e666388faa495
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
  36:     0x7ffff3920425 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9b6389e489a4842f
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
  37:     0x7ffff3920425 - std::sys::unix::thread::Thread::new::thread_start::hcab660740b858b1f
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys/unix/thread.rs:108:17
  38:     0x7ffff36b4dd4 - start_thread
  39:     0x7ffff37369b0 - __clone3
  40:                0x0 - <unknown>
  ```

</details>
