### ISSUE TITLE
rustdoc-json: Invalid output for function returning public item from private module

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#96161]
```rust
#![feature(no_core)]
#![no_core]
mod secret {
    pub struct Secret;
}

pub fn get_secret() -> secret::Secret {
    secret::Secret
}
```

Produces (redacted for clairty, [full here](https://gist.github.com/aDotInTheVoid/24b8314ae8e6d83d9ac19ef8cefdfd03))

```json
{
    "includes_private": false,
    "index": {
        "0:0": {
            "id": "0:0",
            "inner": {
                "is_crate": true,
                "items": [
                    "0:4"
                ]
            },
            "kind": "module",
            "name": "hashbrown",
            "visibility": "public"
        },
        "0:4": {
            "id": "0:4",
            "inner": {
                "decl": {
                    "inputs": [],
                    "output": {
                        "inner": {
                            "id": "0:2",
                            "name": "secret::Secret"
                        },
                        "kind": "resolved_path"
                    }
                }
            },
            "kind": "function",
            "name": "get_secret",
            "visibility": "public"
        }
    },
    "root": "0:0"
}
```

Where `0:2` is a dangling `Id`.

This fails `check_missing_items.py` with output `Type contained an invalid ID: 0:2`

IMO the best way would be to include these "Hidden" items, as the items they have can still be called, even if their is no publicly visable way to write their type. 
([eg](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4a208918bd73f7fcc4a5a7ed0002164a))

This would also improve the HTML, which currently doesnt give links to such items. However it's unclear how to document such an item that doesn't appear in a path.

cc @craftspider

@rustbot modify labels: +T-rustdoc +A-rustdoc-json

**Comment by CraftSpider** [comment]
This is basically the same as the other issues which led to me opening my current PR that proposes not stripping modules in rustdoc-json. I need to fix the current issues with that branch at some point, and it should fix this as it will prevent there every being dangling items.

**Comment by aDotInTheVoid** [comment]
What is #93518 blocked on? I can't tell from the comments.

**Comment by GuillaumeGomez** [comment]
#93518 as is doesn't solve this issue. I'm currently working on it.
